{
  "hash": "eafd0b3dc39047b697af962c039477d8",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n\n\n\n# Model comparison {#sec-DEB}\n\n## Data importation\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath_fig <- here::here(\"fig/DEB_Models\")\n\nf_write_DEB_models()\n\npath_A_FLYw <- here::here(\"mod/A_DEB_FLYw\")\npath_B_FLYe <- here::here(\"mod/B_DEB_FLYe\")\npath_C_CWYe <- here::here(\"mod/C_DEB_CWYe\")\npath_D_CWKe <- here::here(\"mod/D_DEB_CWKe\")\npath_E_CLYe <- here::here(\"mod/E_DEB_CLYe\")\npath_F_CLKe <- here::here(\"mod/F_DEB_CLKe\")\npath_G_FLKe <- here::here(\"mod/G_DEB_FLKe\")\npath_H_FWKe <- here::here(\"mod/H_DEB_FWKe\")\n\nl_Experiments_fit <- c(\n  \"Bart2019_XP1_1\",  \n  \"Bart2019_XP1_2\",  \n  #\"Bart2019_XP2\",\n  \"Bart2019_XP3\",   \n  \"Bart2019_XP4_1\",\n  \"Bart2019_XP4_2\",\n  \"Bart2019_XP5\", \n  \"Bart2020\",\n  #\"Gollot2026_lufa\"\n  \"Gollot2026_dens_D1\",\n  \"Gollot2026_dens_D2\",\n  \"Gollot2026_dens_D2b\",\n  \"Gollot2026_dens_D5\",\n  \"Gollot2026_dens_D7\"\n  )\n\nAdults_alone <- FALSE\n\ndf_data_fit <- f_import_data_DEB(l_Experiments_fit, Adults_alone) \n\nExperiments_carac <- f_get_experiments()\nl_Experiments_tot <- Experiments_carac$l_Experiments_tot\nl_carac <- Experiments_carac$l_carac\ndf_carc_exp <- Experiments_carac$df_carc_exp\n```\n:::\n\n\n\n\n\n## Model fits\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNbIter <- 30000\nOM_diff <- TRUE\nRTOL <- 1e-7\nATOL <- 1e-6\n\n######### A FLYw ###############################################################\n\nseeds <- c(C1 = 3333, C2 = 3666, C3 = 2212)\n\ntext_priors <- '\nDistrib (Fm,           LogUniform,         0.0001,        10);\nDistrib (pAm,          TruncNormal_cv,        100,      0.2,      40,    2000);\nDistrib (r_pAm_pM,     TruncNormal_cv,        0.8,      0.1,     0.1,       2);\nDistrib (v,            TruncNormal_cv,    0.18505,      0.1,   0.001,       2);\nDistrib (kap,          Uniform,                 0,        1);\nDistrib (Ehp,          TruncNormal_cv,        100,      0.2,      20,     300);\nDistrib (E_coc,        TruncNormal_cv,         30,      0.2,       1,     300);\nDistrib (rOM_ClxHorse, LogUniform,        0.00001,      0.3);\nDistrib (dv,           TruncNormal_cv,          1,      0.05,       0,      4);\nDistrib (wE,           LogUniform,              1,      1000);\n\n# Calcul des vraissemblances\nDistrib (Sigma_W, TruncNormal,  5, 1, 0.01, 100);'\n\ntext_likelihood <- 'Likelihood (Weight,   Normal, Prediction(Weight), Sigma_W);  \nLikelihood (Reproduction, Poisson, Prediction(Reproduction));'\n\nf_In_tot(path_A_FLYw, l_Experiments_fit, Adults_alone, \n         text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)\n\n######### B FLYe ###############################################################\n\nseeds <- c(C1 = 3313, C2 = 5050, C3 = 6863)\n\ntext_priors <- '\nDistrib (Fm,           LogUniform,         0.0001,        10);\nDistrib (pAm,          TruncNormal_cv,        100,      0.2,      40,    2000);\nDistrib (r_pAm_pM,     TruncNormal_cv,        0.8,      0.1,     0.1,       2);\nDistrib (v,            TruncNormal_cv,    0.18505,      0.1,   0.001,       2);\nDistrib (kap,          Uniform,                 0,        1);\nDistrib (Ehp,          TruncNormal_cv,        100,      0.2,      20,     300);\nDistrib (E_coc,        TruncNormal_cv,         30,      0.2,       1,     300);\nDistrib (rOM_ClxHorse, LogUniform,        0.00001,      0.3);\nDistrib (dv,           TruncNormal_cv,          1,      0.05,       0,      4);\nDistrib (de,           LogUniform,    0.000000001,      0.1);\n\n# Calcul des vraissemblances\nDistrib (Sigma_W, TruncNormal,  5, 1, 0.01, 100);'\n\ntext_likelihood <- 'Likelihood (Weight,   Normal, Prediction(Weight), Sigma_W);  \nLikelihood (Reproduction, Poisson, Prediction(Reproduction));'\n\nf_In_tot(path_B_FLYe, l_Experiments_fit, Adults_alone, \n         text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)\n\n######### C CWYe ###############################################################\n\nseeds <- c(C1 = 2291, C2 = 8809, C3 = 7007)\n\ntext_priors <- '\nDistrib (Fm,           LogUniform,         0.0001,        10);\nDistrib (pAm,          TruncNormal_cv,        100,      0.2,      40,    2000);\nDistrib (r_pAm_pM,     TruncNormal_cv,        0.8,      0.1,     0.1,       2);\nDistrib (v,            TruncNormal_cv,    0.18505,      0.1,   0.001,       2);\nDistrib (kapJ,         Uniform,                 0,        1);\nDistrib (kapA,         Uniform,                 0,        1);\nDistrib (Ehp,          TruncNormal_cv,        100,      0.2,      20,     300);\nDistrib (E_coc,        TruncNormal_cv,         30,      0.2,       1,     300);\nDistrib (rOM_ClxHorse, LogUniform,        0.00001,      0.3);\nDistrib (dv,           TruncNormal_cv,          1,      0.05,       0,      4);\nDistrib (de,           LogUniform,     0.000000001,     0.1);\nDistrib (tau,          TruncNormal_cv,          7,      0.5,       0,      50);\n\n# Calcul des vraissemblances\nDistrib (Sigma_W, TruncNormal,  5, 1, 0.01, 100);'\n\ntext_likelihood <- 'Likelihood (Weight,   Normal, Prediction(Weight), Sigma_W);  \nLikelihood (Reproduction, Poisson, Prediction(Reproduction));'\n\nf_In_tot(path_C_CWYe, l_Experiments_fit, Adults_alone, \n         text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)\n\n######### D CWKe ###############################################################\n\nseeds <- c(C1 = 3320, C2 = 6636, C3 = 1283)\n\ntext_priors <- '\nDistrib (Fm,           LogUniform,         0.0001,      10);\nDistrib (pAm,          TruncNormal_cv,        100,      0.2,      40,    2000);\nDistrib (r_pAm_pM,     TruncNormal_cv,        0.8,      0.1,     0.1,       2);\nDistrib (v,            TruncNormal_cv,    0.18505,      0.1,   0.001,       2);\nDistrib (kapJ,         Uniform,                 0,        1);\nDistrib (kapA,         Uniform,                 0,        1);\nDistrib (Ehp,          TruncNormal_cv,        100,      0.2,      20,     300);\nDistrib (E_coc,        TruncNormal_cv,         30,      0.2,       1,     300);\nDistrib (rOM_ClxHorse, LogUniform,        0.00001,      0.3);\nDistrib (K,            Uniform,            0.0001,        1);\nDistrib (dv,           TruncNormal_cv,          1,      0.05,       0,      4);\nDistrib (de,           LogUniform,     0.000000001,     0.1);\nDistrib (tau,          TruncNormal_cv,          7,      0.5,       0,      50);\n\n# Calcul des vraissemblances\nDistrib (Sigma_W, TruncNormal,  5, 1, 0.01, 100);'\n\ntext_likelihood <- 'Likelihood (Weight,   Normal, Prediction(Weight), Sigma_W);  \nLikelihood (Reproduction, Poisson, Prediction(Reproduction));'\n\nf_In_tot(path_D_CWKe, l_Experiments_fit, Adults_alone, \n         text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)\n\n######### E CLYe ###############################################################\n\nseeds <- c(C1 = 8809, C2 = 6336, C3 = 5809)\n\ntext_priors <- '\nDistrib (Fm,           LogUniform,         0.0001,        10);\nDistrib (pAm,          TruncNormal_cv,        100,      0.2,      40,    2000);\nDistrib (r_pAm_pM,     TruncNormal_cv,        0.8,      0.1,     0.1,       2);\nDistrib (v,            TruncNormal_cv,    0.18505,      0.1,   0.001,       2);\nDistrib (kapJ,         Uniform,                 0,        1);\nDistrib (kapA,         Uniform,                 0,        1);\nDistrib (Ehp,          TruncNormal_cv,        100,      0.2,      20,     300);\nDistrib (E_coc,        TruncNormal_cv,         30,      0.2,       1,     300);\nDistrib (rOM_ClxHorse, LogUniform,        0.00001,      0.3);\nDistrib (dv,           TruncNormal_cv,          1,      0.05,       0,      4);\nDistrib (de,           LogUniform,     0.000000001,     0.1);\nDistrib (tau,          TruncNormal_cv,          7,      0.5,       0,      50);\n\n# Calcul des vraissemblances\nDistrib (Sigma_W, TruncNormal,  5, 1, 0.01, 100);'\n\ntext_likelihood <- 'Likelihood (Weight,   Normal, Prediction(Weight), Sigma_W);  \nLikelihood (Reproduction, Poisson, Prediction(Reproduction));'\n\nf_In_tot(path_E_CLYe, l_Experiments_fit, Adults_alone, \n         text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)\n\n######### F CLKe ###############################################################\n\nseeds <- c(C1 = 3030, C2 = 6646, C3 = 1212)\n\ntext_priors <- '\nDistrib (Fm,           LogUniform,         0.0001,        10);\nDistrib (pAm,          TruncNormal_cv,        100,      0.2,      40,    2000);\nDistrib (r_pAm_pM,     TruncNormal_cv,        0.8,      0.1,     0.1,       2);\nDistrib (v,            TruncNormal_cv,    0.18505,      0.1,   0.001,       2);\nDistrib (kapJ,         Uniform,                 0,        1);\nDistrib (kapA,         Uniform,                 0,        1);\nDistrib (Ehp,          TruncNormal_cv,        100,      0.2,      20,     300);\nDistrib (E_coc,        TruncNormal_cv,         30,      0.2,       1,     300);\nDistrib (rOM_ClxHorse, LogUniform,        0.00001,      0.3);\nDistrib (K,            Uniform,           0.00001,        2);\nDistrib (dv,           TruncNormal_cv,          1,      0.05,       0,      4);\nDistrib (de,           LogUniform,     0.000000001,     0.1);\nDistrib (tau,          TruncNormal_cv,          7,      0.5,       0,      50);\n\n# Calcul des vraissemblances\nDistrib (Sigma_W, TruncNormal,  5, 1, 0.01, 100);'\n\ntext_likelihood <- 'Likelihood (Weight,    Normal, Prediction(Weight), Sigma_W);  \nLikelihood (Reproduction, Poisson, Prediction(Reproduction));'\n\nf_In_tot(path_F_CLKe, l_Experiments_fit, Adults_alone, \n         text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)\n\n######### G FLKe ###############################################################\n\nseeds <- c(C1 = 3133, C2 = 6666, C3 = 1212)\n\ntext_priors <- '\nDistrib (Fm,           LogUniform,         0.0001,        10);\nDistrib (pAm,          TruncNormal_cv,        100,      0.2,      40,    2000);\nDistrib (r_pAm_pM,     TruncNormal_cv,        0.8,      0.1,     0.1,       2);\nDistrib (v,            TruncNormal_cv,    0.18505,      0.1,   0.001,       2);\nDistrib (kap,          Uniform,                 0,        1);\nDistrib (Ehp,          TruncNormal_cv,        100,      0.2,      20,     300);\nDistrib (E_coc,        TruncNormal_cv,         30,      0.2,       1,     300);\nDistrib (rOM_ClxHorse, LogUniform,        0.00001,      0.3);\nDistrib (K,            Uniform,           0.00001,        2);\nDistrib (dv,           TruncNormal_cv,          1,      0.05,       0,      4);\nDistrib (de,           LogUniform,    0.000000001,      0.1);\n\n# Calcul des vraissemblances\nDistrib (Sigma_W, TruncNormal,  5, 1, 0.01, 100);'\n\ntext_likelihood <- 'Likelihood (Weight,   Normal, Prediction(Weight), Sigma_W);  \nLikelihood (Reproduction, Poisson, Prediction(Reproduction));'\n\nf_In_tot(path_G_FLKe, l_Experiments_fit, Adults_alone, \n         text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)\n\n######### H FWKe ###############################################################\n\nseeds <- c(C1 = 3133, C2 = 6666, C3 = 1212)\n\ntext_priors <- '\nDistrib (Fm,           LogUniform,         0.0001,        10);\nDistrib (pAm,          TruncNormal_cv,        100,      0.2,      40,    2000);\nDistrib (r_pAm_pM,     TruncNormal_cv,        0.8,      0.1,     0.1,       2);\nDistrib (v,            TruncNormal_cv,    0.18505,      0.1,   0.001,       2);\nDistrib (kap,          Uniform,                 0,        1);\nDistrib (Ehp,          TruncNormal_cv,        100,      0.2,      20,     300);\nDistrib (E_coc,        TruncNormal_cv,         30,      0.2,       1,     300);\nDistrib (rOM_ClxHorse, LogUniform,        0.00001,      0.3);\nDistrib (K,            Uniform,           0.00001,        2);\nDistrib (dv,           TruncNormal_cv,          1,      0.05,       0,      4);\nDistrib (de,           LogUniform,    0.000000001,      0.1);\n\n# Calcul des vraissemblances\nDistrib (Sigma_W, TruncNormal,  5, 1, 0.01, 100);'\n\ntext_likelihood <- 'Likelihood (Weight,   Normal, Prediction(Weight), Sigma_W);  \nLikelihood (Reproduction, Poisson, Prediction(Reproduction));'\n\nf_In_tot(path_H_FWKe, l_Experiments_fit, Adults_alone, \n         text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)\n```\n:::\n\n\n\n\n\n## Estimates results\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {#tbl-ResModels .cell tbl-cap='Estimation results from all models.'}\n\n```{.r .cell-code}\nlist_models <- c(\"A_FLYw\", \"B_FLYe\", \"C_CWYe\", \"D_CWKe\", \"E_CLYe\", \"F_CLKe\", \"G_FLKe\", \"H_FWKe\")\nlist_model_summary <- mget(paste0(\"Summary_res_\", list_models))\n\nparam_order <- c(\n  \"pAm\", \"r_pAm_pM\", \"Fm\", \"rOM_ClxHorse\", \"K\", \"v\", \"kap\", \"kapJ\", \"kapA\", \"tau\",\n  \"Ehp\", \"E_coc\", \"dv\", \"de\", \"wE\", \"Sigma_W\"\n)\n\nformat_summary <- function(df) {\n  df %>%\n    rename_with(~ str_remove(., \"\\\\.1\\\\.$\")) %>%\n    rownames_to_column(\"stat\") %>%\n    pivot_longer(\n      cols = -c(stat, Model),\n      names_to = \"param\",\n      values_to = \"value\"\n    ) %>%\n    pivot_wider(\n      names_from = stat,\n      values_from = value\n    ) %>%\n    mutate(\n      value = str_c(\n        round(Result_mode, 3),\n        \" [\", round(`2.5%`, 3),\n        \" ; \", round(`97.5%`, 3), \"]\"\n      )\n    ) %>%\n    dplyr::select(Model, param, value) %>%\n    pivot_wider(\n      names_from = param,\n      values_from = value\n    )\n}\n\ndf_result <- list_model_summary %>%\n  map(format_summary) %>%\n  bind_rows() %>%\n  dplyr::select(\n    Model,\n    any_of(param_order),\n    everything()\n  ) |> \n  left_join(df_LL_BIC)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nJoining with `by = join_by(Model)`\n```\n\n\n:::\n\n```{.r .cell-code}\ndf_result |> datatable(\n  options = list(\n    dom = 't',\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n      )\n    ),\n  class=\"hover\"\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-09714a492ee4bcb7aebf\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-09714a492ee4bcb7aebf\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\"],[\"A_FLYw\",\"B_FLYe\",\"C_CWYe\",\"D_CWKe\",\"E_CLYe\",\"F_CLKe\",\"G_FLKe\",\"H_FWKe\"],[\"269.454 [255.81 ; 290.922]\",\"134.034 [111.975 ; 167.618]\",\"285.406 [257.196 ; 322.668]\",\"259.953 [234.819 ; 285.688]\",\"381.112 [310.988 ; 394.341]\",\"248.606 [225.069 ; 272.375]\",\"304.838 [270.338 ; 327.819]\",\"287.333 [251.241 ; 319.901]\"],[\"1.094 [1.003 ; 1.132]\",\"0.662 [0.44 ; 0.719]\",\"0.1 [0.1 ; 0.126]\",\"0.701 [0.616 ; 0.743]\",\"0.1 [0.1 ; 0.119]\",\"0.629 [0.537 ; 0.692]\",\"0.887 [0.848 ; 0.927]\",\"0.915 [0.867 ; 0.948]\"],[\"5.199 [4.636 ; 6.623]\",\"7.504 [2.88 ; 9.012]\",\"9.592 [8.321 ; 9.986]\",\"3.876 [2.442 ; 8.775]\",\"9.951 [5.299 ; 9.894]\",\"5.645 [4.486 ; 6.351]\",\"7.183 [5.611 ; 8.551]\",\"7.6 [5.11 ; 9.943]\"],[\"0.139 [0.092 ; 0.169]\",\"0 [0 ; 0.081]\",\"0.181 [0.151 ; 0.242]\",\"0.029 [0.019 ; 0.045]\",\"0.064 [0.047 ; 0.167]\",\"0.057 [0.035 ; 0.101]\",\"0.061 [0.036 ; 0.12]\",\"0.027 [0.015 ; 0.05]\"],[null,null,null,\"0.055 [0.028 ; 0.173]\",null,\"0.418 [0.225 ; 0.772]\",\"0.352 [0.196 ; 0.808]\",\"0.069 [0.037 ; 0.159]\"],[\"0.199 [0.161 ; 0.23]\",\"0.184 [0.148 ; 0.221]\",\"0.203 [0.17 ; 0.236]\",\"0.231 [0.204 ; 0.263]\",\"0.219 [0.184 ; 0.251]\",\"0.221 [0.197 ; 0.257]\",\"0.237 [0.206 ; 0.264]\",\"0.232 [0.203 ; 0.265]\"],[\"0.643 [0.54 ; 0.724]\",\"0.665 [0.478 ; 0.807]\",null,null,null,null,\"0.978 [0.97 ; 0.986]\",\"0.977 [0.966 ; 0.988]\"],[null,null,\"0.968 [0.922 ; 0.975]\",\"0.983 [0.97 ; 0.988]\",\"0.964 [0.932 ; 0.982]\",\"0.976 [0.97 ; 0.99]\",null,null],[null,null,\"0.658 [0.584 ; 0.762]\",\"0.708 [0.627 ; 0.759]\",\"0.519 [0.472 ; 0.669]\",\"0.654 [0.561 ; 0.718]\",null,null],[null,null,\"9.085 [1.783 ; 14.621]\",\"11.953 [6.151 ; 20.39]\",\"9.175 [2.76 ; 17.381]\",\"16.768 [8.145 ; 22.801]\",null,null],[\"25.402 [22.192 ; 30.493]\",\"54.759 [38.542 ; 83.962]\",\"28.33 [21.593 ; 65.826]\",\"73.1 [55.907 ; 127.749]\",\"58.331 [25.268 ; 83.76]\",\"100.008 [42.173 ; 126.363]\",\"119.167 [81.084 ; 150.347]\",\"111.16 [62.413 ; 147.791]\"],[\"1 [1.001 ; 1.186]\",\"1.119 [1.009 ; 1.928]\",\"19.168 [11.665 ; 26.757]\",\"57.834 [51.235 ; 69.959]\",\"40.061 [21.764 ; 44.724]\",\"64.372 [55.934 ; 74.843]\",\"5.496 [3.503 ; 7.15]\",\"5.23 [2.808 ; 7.61]\"],[\"0.999 [0.902 ; 1.099]\",\"1.014 [0.9 ; 1.098]\",\"1.133 [1.037 ; 1.227]\",\"1.214 [1.094 ; 1.265]\",\"1.176 [1.045 ; 1.262]\",\"1.164 [1.07 ; 1.257]\",\"1.057 [0.962 ; 1.155]\",\"1.101 [0.991 ; 1.175]\"],[null,\"0 [0 ; 0]\",\"0 [0 ; 0]\",\"0 [0 ; 0]\",\"0 [0 ; 0]\",\"0 [0 ; 0]\",\"0 [0 ; 0]\",\"0 [0 ; 0]\"],[\"458.967 [293.703 ; 688.048]\",null,null,null,null,null,null,null],[\"0.141 [0.129 ; 0.167]\",\"0.598 [0.546 ; 0.687]\",\"0.312 [0.278 ; 0.369]\",\"0.118 [0.103 ; 0.138]\",\"0.215 [0.186 ; 0.303]\",\"0.102 [0.085 ; 0.112]\",\"0.14 [0.126 ; 0.171]\",\"0.169 [0.145 ; 0.202]\"],[-35.51,-247.61,-172.2,-9.550000000000001,-107.91,13.56,-18.83,-49.49],[127.26,551.47,411.89,92.20999999999999,283.3,45.98,99.53,160.84]],\"container\":\"<table class=\\\"hover\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Model<\\/th>\\n      <th>pAm<\\/th>\\n      <th>r_pAm_pM<\\/th>\\n      <th>Fm<\\/th>\\n      <th>rOM_ClxHorse<\\/th>\\n      <th>K<\\/th>\\n      <th>v<\\/th>\\n      <th>kap<\\/th>\\n      <th>kapJ<\\/th>\\n      <th>kapA<\\/th>\\n      <th>tau<\\/th>\\n      <th>Ehp<\\/th>\\n      <th>E_coc<\\/th>\\n      <th>dv<\\/th>\\n      <th>de<\\/th>\\n      <th>wE<\\/th>\\n      <th>Sigma_W<\\/th>\\n      <th>LL<\\/th>\\n      <th>BIC<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Model\",\"targets\":1},{\"name\":\"pAm\",\"targets\":2},{\"name\":\"r_pAm_pM\",\"targets\":3},{\"name\":\"Fm\",\"targets\":4},{\"name\":\"rOM_ClxHorse\",\"targets\":5},{\"name\":\"K\",\"targets\":6},{\"name\":\"v\",\"targets\":7},{\"name\":\"kap\",\"targets\":8},{\"name\":\"kapJ\",\"targets\":9},{\"name\":\"kapA\",\"targets\":10},{\"name\":\"tau\",\"targets\":11},{\"name\":\"Ehp\",\"targets\":12},{\"name\":\"E_coc\",\"targets\":13},{\"name\":\"dv\",\"targets\":14},{\"name\":\"de\",\"targets\":15},{\"name\":\"wE\",\"targets\":16},{\"name\":\"Sigma_W\",\"targets\":17},{\"name\":\"LL\",\"targets\":18},{\"name\":\"BIC\",\"targets\":19}],\"order\":[],\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n## Chains\n\n::: panel-tabset\n## A_FLYw\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Parameters chains. Only the last `r Nb_iter_kept` are represented.](E_Model_comparison_files/figure-html/fig-chains_A_FLYw-1.png){#fig-chains_A_FLYw width=768}\n:::\n:::\n\n\n\n\n\n\n\n## B_FLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Parameters chains. Only the last `r Nb_iter_kept` are represented.](E_Model_comparison_files/figure-html/fig-chains_B_FLYe-1.png){#fig-chains_B_FLYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## C_CWYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Parameters chains. Only the last `r Nb_iter_kept` are represented.](E_Model_comparison_files/figure-html/fig-chains_C_CWYe-1.png){#fig-chains_C_CWYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## D_CWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Parameters chains. Only the last `r Nb_iter_kept` are represented.](E_Model_comparison_files/figure-html/fig-chains_D_CWKe-1.png){#fig-chains_D_CWKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## E_CLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Parameters chains. Only the last `r Nb_iter_kept` are represented.](E_Model_comparison_files/figure-html/fig-chains_E_CLYe-1.png){#fig-chains_E_CLYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## F_CLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Parameters chains. Only the last `r Nb_iter_kept` are represented.](E_Model_comparison_files/figure-html/fig-chains_F_CLKe-1.png){#fig-chains_F_CLKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## G_FLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Parameters chains. Only the last `r Nb_iter_kept` are represented.](E_Model_comparison_files/figure-html/fig-chains_G_FLKe-1.png){#fig-chains_G_FLKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## H_FWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Parameters chains. Only the last `r Nb_iter_kept` are represented.](E_Model_comparison_files/figure-html/fig-chains_H_FWKe-1.png){#fig-chains_H_FWKe width=768}\n:::\n:::\n\n\n\n\n\n\n:::\n\n## Likelihoods\n\n::: panel-tabset\n## A_FLYw\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Evolution of likelihood and deviance ratio through the iterations.](E_Model_comparison_files/figure-html/fig-like_A_FLYw-1.png){#fig-like_A_FLYw width=768}\n:::\n:::\n\n\n\n\n\n\n\n## B_FLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Evolution of likelihood and deviance ratio through the iterations.](E_Model_comparison_files/figure-html/fig-like_B_FLYe-1.png){#fig-like_B_FLYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## C_CWYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Evolution of likelihood and deviance ratio through the iterations.](E_Model_comparison_files/figure-html/fig-like_C_CWYe-1.png){#fig-like_C_CWYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## D_CWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Evolution of likelihood and deviance ratio through the iterations.](E_Model_comparison_files/figure-html/fig-like_D_CWKe-1.png){#fig-like_D_CWKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## E_CLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Evolution of likelihood and deviance ratio through the iterations.](E_Model_comparison_files/figure-html/fig-like_E_CLYe-1.png){#fig-like_E_CLYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## F_CLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Evolution of likelihood and deviance ratio through the iterations.](E_Model_comparison_files/figure-html/fig-like_F_CLKe-1.png){#fig-like_F_CLKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## G_FLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Evolution of likelihood and deviance ratio through the iterations.](E_Model_comparison_files/figure-html/fig-like_G_FLKe-1.png){#fig-like_G_FLKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## H_FWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Evolution of likelihood and deviance ratio through the iterations.](E_Model_comparison_files/figure-html/fig-like_H_FWKe-1.png){#fig-like_H_FWKe width=768}\n:::\n:::\n\n\n\n\n\n\n:::\n\n## Chains convergence\n\n::: panel-tabset\n## A_FLYw\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPotential scale reduction factors:\n\n                Point est. Upper C.I.\ndv.1.                 1.00       1.00\nE_coc.1.              1.00       1.01\nEhp.1.                1.00       1.00\nFm.1.                 1.01       1.03\nkap.1.                1.04       1.11\npAm.1.                1.00       1.01\nr_pAm_pM.1.           1.01       1.03\nrOM_ClxHorse.1.       1.01       1.01\nSigma_W.1.            1.00       1.00\nv.1.                  1.00       1.01\nwE.1.                 1.04       1.12\n\nMultivariate psrf\n\n1.04\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_A_FLYw-1.png){#fig-chainsconvergence_A_FLYw-1 width=768}\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_A_FLYw-2.png){#fig-chainsconvergence_A_FLYw-2 width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_rds <- here::here(\"fig/DEBTKTD_Models/A_FLYw_ipairs_plot.png\")\nf_Plot_ipairs(MCMC_out_A_FLYw, file_rds)\n```\n\n::: {.cell-output-display}\n![Parameter correlations.](E_Model_comparison_files/figure-html/fig-corr_A_FLYw-1.png){#fig-corr_A_FLYw width=576}\n:::\n:::\n\n\n\n\n\n## B_FLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPotential scale reduction factors:\n\n                Point est. Upper C.I.\nde.1.                 1.12       1.32\ndv.1.                 1.01       1.02\nE_coc.1.              1.43       2.11\nEhp.1.                1.68       2.69\nFm.1.                 1.47       2.30\nkap.1.                1.94       3.33\npAm.1.                1.65       2.63\nr_pAm_pM.1.           1.03       1.08\nrOM_ClxHorse.1.       1.38       2.80\nSigma_W.1.            1.01       1.02\nv.1.                  1.00       1.00\n\nMultivariate psrf\n\n1.75\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_B_FLYe-1.png){#fig-chainsconvergence_B_FLYe-1 width=768}\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_B_FLYe-2.png){#fig-chainsconvergence_B_FLYe-2 width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_rds <- here::here(\"fig/DEBTKTD_Models/B_FLYe_ipairs_plot.png\")\nf_Plot_ipairs(MCMC_out_B_FLYe, file_rds)\n```\n\n::: {.cell-output-display}\n![Parameter correlations.](E_Model_comparison_files/figure-html/fig-corr_B_FLYe-1.png){#fig-corr_B_FLYe width=576}\n:::\n:::\n\n\n\n\n\n## C_CWYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPotential scale reduction factors:\n\n                Point est. Upper C.I.\nde.1.                 1.09       1.10\ndv.1.                 1.01       1.01\nE_coc.1.              1.10       1.30\nEhp.1.                1.04       1.10\nFm.1.                 1.01       1.04\nkapA.1.               1.07       1.22\nkapJ.1.               1.10       1.29\npAm.1.                1.06       1.19\nr_pAm_pM.1.           1.01       1.02\nrOM_ClxHorse.1.       1.03       1.11\nSigma_W.1.            1.03       1.11\ntau.1.                1.00       1.00\nv.1.                  1.00       1.02\n\nMultivariate psrf\n\n1.1\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_C_CWYe-1.png){#fig-chainsconvergence_C_CWYe-1 width=768}\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_C_CWYe-2.png){#fig-chainsconvergence_C_CWYe-2 width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_rds <- here::here(\"fig/DEBTKTD_Models/C_CWYe_ipairs_plot.png\")\nf_Plot_ipairs(MCMC_out_C_CWYe, file_rds)\n```\n\n::: {.cell-output-display}\n![Parameter correlations.](E_Model_comparison_files/figure-html/fig-corr_C_CWYe-1.png){#fig-corr_C_CWYe width=576}\n:::\n:::\n\n\n\n\n\n## D_CWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPotential scale reduction factors:\n\n                Point est. Upper C.I.\nde.1.                 1.05       1.09\ndv.1.                 1.01       1.04\nE_coc.1.              1.01       1.04\nEhp.1.                1.02       1.05\nFm.1.                 1.08       1.24\nK.1.                  1.08       1.24\nkapA.1.               1.01       1.02\nkapJ.1.               1.02       1.07\npAm.1.                1.01       1.03\nr_pAm_pM.1.           1.01       1.02\nrOM_ClxHorse.1.       1.04       1.14\nSigma_W.1.            1.00       1.01\ntau.1.                1.00       1.00\nv.1.                  1.00       1.01\n\nMultivariate psrf\n\n1.1\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_D_CWKe-1.png){#fig-chainsconvergence_D_CWKe-1 width=768}\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_D_CWKe-2.png){#fig-chainsconvergence_D_CWKe-2 width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_rds <- here::here(\"fig/DEBTKTD_Models/D_CWKe_ipairs_plot.png\")\nf_Plot_ipairs(MCMC_out_D_CWKe, file_rds)\n```\n\n::: {.cell-output-display}\n![Parameter correlations.](E_Model_comparison_files/figure-html/fig-corr_D_CWKe-1.png){#fig-corr_D_CWKe width=576}\n:::\n:::\n\n\n\n\n\n\n\n## E_CLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPotential scale reduction factors:\n\n                Point est. Upper C.I.\nde.1.                 1.02       1.03\ndv.1.                 1.02       1.06\nE_coc.1.              1.07       1.21\nEhp.1.                1.35       1.94\nFm.1.                 1.01       1.03\nkapA.1.               1.06       1.19\nkapJ.1.               1.37       1.97\npAm.1.                1.03       1.11\nr_pAm_pM.1.           1.01       1.01\nrOM_ClxHorse.1.       1.04       1.07\nSigma_W.1.            1.06       1.17\ntau.1.                1.01       1.03\nv.1.                  1.01       1.03\n\nMultivariate psrf\n\n1.26\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_E_CLYe-1.png){#fig-chainsconvergence_E_CLYe-1 width=768}\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_E_CLYe-2.png){#fig-chainsconvergence_E_CLYe-2 width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_rds <- here::here(\"fig/DEBTKTD_Models/E_CLYe_ipairs_plot.png\")\nf_Plot_ipairs(MCMC_out_E_CLYe, file_rds)\n```\n\n::: {.cell-output-display}\n![Parameter correlations.](E_Model_comparison_files/figure-html/fig-corr_E_CLYe-1.png){#fig-corr_E_CLYe width=576}\n:::\n:::\n\n\n\n\n\n## F_CLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPotential scale reduction factors:\n\n                Point est. Upper C.I.\nde.1.                 1.01       1.01\ndv.1.                 1.06       1.19\nE_coc.1.              1.03       1.10\nEhp.1.                1.06       1.17\nFm.1.                 1.03       1.08\nK.1.                  1.02       1.02\nkapA.1.               1.11       1.34\nkapJ.1.               1.04       1.07\npAm.1.                1.09       1.28\nr_pAm_pM.1.           1.08       1.25\nrOM_ClxHorse.1.       1.01       1.05\nSigma_W.1.            1.01       1.04\ntau.1.                1.00       1.00\nv.1.                  1.01       1.03\n\nMultivariate psrf\n\n1.13\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_F_CLKe-1.png){#fig-chainsconvergence_F_CLKe-1 width=768}\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_F_CLKe-2.png){#fig-chainsconvergence_F_CLKe-2 width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_rds <- here::here(\"fig/DEBTKTD_Models/F_CLKe_ipairs_plot.png\")\nf_Plot_ipairs(MCMC_out_F_CLKe, file_rds)\n```\n\n::: {.cell-output-display}\n![Parameter correlations.](E_Model_comparison_files/figure-html/fig-corr_F_CLKe-1.png){#fig-corr_F_CLKe width=576}\n:::\n:::\n\n\n\n\n\n## G_FLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPotential scale reduction factors:\n\n                Point est. Upper C.I.\nde.1.                 1.06       1.10\ndv.1.                 1.00       1.00\nE_coc.1.              1.02       1.05\nEhp.1.                1.03       1.08\nFm.1.                 1.01       1.02\nK.1.                  1.09       1.24\nkap.1.                1.02       1.04\npAm.1.                1.01       1.03\nr_pAm_pM.1.           1.00       1.01\nrOM_ClxHorse.1.       1.11       1.30\nSigma_W.1.            1.00       1.00\nv.1.                  1.00       1.00\n\nMultivariate psrf\n\n1.08\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_G_FLKe-1.png){#fig-chainsconvergence_G_FLKe-1 width=768}\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_G_FLKe-2.png){#fig-chainsconvergence_G_FLKe-2 width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_rds <- here::here(\"fig/DEBTKTD_Models/G_FLKe_ipairs_plot.png\")\nf_Plot_ipairs(MCMC_out_G_FLKe, file_rds)\n```\n\n::: {.cell-output-display}\n![Parameter correlations.](E_Model_comparison_files/figure-html/fig-corr_G_FLKe-1.png){#fig-corr_G_FLKe width=576}\n:::\n:::\n\n\n\n\n\n## H_FWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPotential scale reduction factors:\n\n                Point est. Upper C.I.\nde.1.                 1.17       1.43\ndv.1.                 1.01       1.02\nE_coc.1.              1.06       1.18\nEhp.1.                1.04       1.13\nFm.1.                 1.00       1.00\nK.1.                  1.01       1.03\nkap.1.                1.05       1.15\npAm.1.                1.02       1.06\nr_pAm_pM.1.           1.01       1.02\nrOM_ClxHorse.1.       1.01       1.02\nSigma_W.1.            1.02       1.05\nv.1.                  1.00       1.01\n\nMultivariate psrf\n\n1.07\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_H_FWKe-1.png){#fig-chainsconvergence_H_FWKe-1 width=768}\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](E_Model_comparison_files/figure-html/fig-chainsconvergence_H_FWKe-2.png){#fig-chainsconvergence_H_FWKe-2 width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_rds <- here::here(\"fig/DEBTKTD_Models/H_FWKe_ipairs_plot.png\")\nf_Plot_ipairs(MCMC_out_H_FWKe, file_rds)\n```\n\n::: {.cell-output-display}\n![Parameter correlations.](E_Model_comparison_files/figure-html/fig-corr_H_FWKe-1.png){#fig-corr_H_FWKe width=576}\n:::\n:::\n\n\n\n\n:::\n\n## Posterior distributions\n\n::: panel-tabset\n## A_FLYw\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distributions of the priors and the posteriors.](E_Model_comparison_files/figure-html/fig-post_A_FLYw-1.png){#fig-post_A_FLYw width=768}\n:::\n:::\n\n\n\n\n\n\n\n## B_FLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distributions of the priors and the posteriors.](E_Model_comparison_files/figure-html/fig-post_B_FLYe-1.png){#fig-post_B_FLYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## C_CWYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distributions of the priors and the posteriors.](E_Model_comparison_files/figure-html/fig-post_C_CWYe-1.png){#fig-post_C_CWYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## D_CWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distributions of the priors and the posteriors.](E_Model_comparison_files/figure-html/fig-post_D_CWKe-1.png){#fig-post_D_CWKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## E_CLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distributions of the priors and the posteriors.](E_Model_comparison_files/figure-html/fig-post_E_CLYe-1.png){#fig-post_E_CLYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## F_CLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distributions of the priors and the posteriors.](E_Model_comparison_files/figure-html/fig-post_F_CLKe-1.png){#fig-post_F_CLKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## G_FLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distributions of the priors and the posteriors.](E_Model_comparison_files/figure-html/fig-post_G_FLKe-1.png){#fig-post_G_FLKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## H_FWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distributions of the priors and the posteriors.](E_Model_comparison_files/figure-html/fig-post_H_FWKe-1.png){#fig-post_H_FWKe width=768}\n:::\n:::\n\n\n\n\n\n\n:::\n\n## Predicted vs. Observed\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nl_param_name_A_FLYw <- names(Summary_res_A_FLYw) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\") \n\nf_In_predobs(path_A_FLYw, l_Experiments_fit, Adults_alone, OM_diff, l_param_name_A_FLYw)\n\nl_param_name_B_FLYe <- names(Summary_res_B_FLYe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_predobs(path_B_FLYe, l_Experiments_fit, Adults_alone, OM_diff, l_param_name_B_FLYe)\n\nl_param_name_C_CWYe <- names(Summary_res_C_CWYe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_predobs(path_C_CWYe, l_Experiments_fit, Adults_alone, OM_diff, l_param_name_C_CWYe)\n\nl_param_name_D_CWKe <- names(Summary_res_D_CWKe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_predobs(path_D_CWKe, l_Experiments_fit, Adults_alone, OM_diff, l_param_name_D_CWKe)\n\nl_param_name_E_CLYe <- names(Summary_res_E_CLYe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_predobs(path_E_CLYe, l_Experiments_fit, Adults_alone, OM_diff, l_param_name_E_CLYe)\n\nl_param_name_F_CLKe <- names(Summary_res_F_CLKe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_predobs(path_F_CLKe, l_Experiments_fit, Adults_alone, OM_diff, l_param_name_F_CLKe)\n\nl_param_name_G_FLKe <- names(Summary_res_G_FLKe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_predobs(path_G_FLKe, l_Experiments_fit, Adults_alone, OM_diff, l_param_name_G_FLKe)\n\nl_param_name_H_FWKe <- names(Summary_res_H_FWKe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_predobs(path_H_FWKe, l_Experiments_fit, Adults_alone, OM_diff, l_param_name_H_FWKe)\n```\n:::\n\n::: {.cell execute='false'}\n\n```{.bash .cell-code}\nfor j in $(seq 1 12); do\n./mcsim.DEBcali DEB_setpoint_predobs_${j}.in\ndone\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nNb_experiment <- 12\n\ndf_data_obs <- df_data_fit |> \n  mutate(\n    Weight_obs = Weight,\n    Reproduction_obs = Reproduction\n    ) |> \n  dplyr::select(-c(Weight, Reproduction))\n\n######## A_FLYw ###############################################################\n\ndf_pred_A_FLYw <- f_read_predobs(path_A_FLYw, Nb_experiment, df_data_obs)\n\ndf_pred_Weight_A_FLYw <- subset(df_pred_A_FLYw, Endpt == \"Weight\" & Time !=0)\ndf_pred_Reproduction_A_FLYw <- subset(df_pred_A_FLYw, Endpt == \"Reproduction\" & Time !=0)\n\ndf_predobs_Reproduction_A_FLYw <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Reproduction_A_FLYw, suffix = c(\"_obs\", \"_pred\")) |> \n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\ndf_predobs_Weight_A_FLYw <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Weight_A_FLYw, suffix = c(\"_obs\", \"_pred\"))|>\n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\n######## B_FLYe ###############################################################\n\ndf_pred_B_FLYe <- f_read_predobs(path_B_FLYe, Nb_experiment, df_data_obs)\n\ndf_pred_Weight_B_FLYe <- subset(df_pred_B_FLYe, Endpt == \"Weight\" & Time !=0)\ndf_pred_Reproduction_B_FLYe <- subset(df_pred_B_FLYe, Endpt == \"Reproduction\" & Time !=0)\n\ndf_predobs_Reproduction_B_FLYe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Reproduction_B_FLYe, suffix = c(\"_obs\", \"_pred\")) |> \n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\ndf_predobs_Weight_B_FLYe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Weight_B_FLYe, suffix = c(\"_obs\", \"_pred\"))|>\n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\n######## C_CWYe ###############################################################\n\ndf_pred_C_CWYe <- f_read_predobs(path_C_CWYe, Nb_experiment, df_data_obs)\n\ndf_pred_Weight_C_CWYe <- subset(df_pred_C_CWYe, Endpt == \"Weight\" & Time !=0)\ndf_pred_Reproduction_C_CWYe <- subset(df_pred_C_CWYe, Endpt == \"Reproduction\" & Time !=0)\n\ndf_predobs_Reproduction_C_CWYe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Reproduction_C_CWYe, suffix = c(\"_obs\", \"_pred\")) |> \n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\ndf_predobs_Weight_C_CWYe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Weight_C_CWYe, suffix = c(\"_obs\", \"_pred\"))|>\n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\n######## D_CWKe ###############################################################\n\ndf_pred_D_CWKe <- f_read_predobs(path_D_CWKe, Nb_experiment, df_data_obs)\n\ndf_pred_Weight_D_CWKe <- subset(df_pred_D_CWKe, Endpt == \"Weight\" & Time !=0)\ndf_pred_Reproduction_D_CWKe <- subset(df_pred_D_CWKe, Endpt == \"Reproduction\" & Time !=0)\n\ndf_predobs_Reproduction_D_CWKe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Reproduction_D_CWKe, suffix = c(\"_obs\", \"_pred\")) |> \n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\ndf_predobs_Weight_D_CWKe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Weight_D_CWKe, suffix = c(\"_obs\", \"_pred\"))|>\n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\n######## E_CLYe ###############################################################\n\ndf_pred_E_CLYe <- f_read_predobs(path_E_CLYe, Nb_experiment, df_data_obs)\n\ndf_pred_Weight_E_CLYe <- subset(df_pred_E_CLYe, Endpt == \"Weight\" & Time !=0)\ndf_pred_Reproduction_E_CLYe <- subset(df_pred_E_CLYe, Endpt == \"Reproduction\" & Time !=0)\n\ndf_predobs_Reproduction_E_CLYe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Reproduction_E_CLYe, suffix = c(\"_obs\", \"_pred\")) |> \n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\ndf_predobs_Weight_E_CLYe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Weight_E_CLYe, suffix = c(\"_obs\", \"_pred\"))|>\n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\n######## F_CLKe ###############################################################\n\ndf_pred_F_CLKe <- f_read_predobs(path_F_CLKe, Nb_experiment, df_data_obs)\n\ndf_pred_Weight_F_CLKe <- subset(df_pred_F_CLKe, Endpt == \"Weight\" & Time !=0)\ndf_pred_Reproduction_F_CLKe <- subset(df_pred_F_CLKe, Endpt == \"Reproduction\" & Time !=0)\n\ndf_predobs_Reproduction_F_CLKe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Reproduction_F_CLKe, suffix = c(\"_obs\", \"_pred\")) |> \n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\ndf_predobs_Weight_F_CLKe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Weight_F_CLKe, suffix = c(\"_obs\", \"_pred\"))|>\n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\n######## G_FLKe ###############################################################\n\ndf_pred_G_FLKe <- f_read_predobs(path_G_FLKe, Nb_experiment, df_data_obs)\n\ndf_pred_Weight_G_FLKe <- subset(df_pred_G_FLKe, Endpt == \"Weight\" & Time !=0)\ndf_pred_Reproduction_G_FLKe <- subset(df_pred_G_FLKe, Endpt == \"Reproduction\" & Time !=0)\n\ndf_predobs_Reproduction_G_FLKe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Reproduction_G_FLKe, suffix = c(\"_obs\", \"_pred\")) |> \n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\ndf_predobs_Weight_G_FLKe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Weight_G_FLKe, suffix = c(\"_obs\", \"_pred\"))|>\n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\n######## H_FWKe ###############################################################\n\ndf_pred_H_FWKe <- f_read_predobs(path_H_FWKe, Nb_experiment, df_data_obs)\n\ndf_pred_Weight_H_FWKe <- subset(df_pred_H_FWKe, Endpt == \"Weight\" & Time !=0)\ndf_pred_Reproduction_H_FWKe <- subset(df_pred_H_FWKe, Endpt == \"Reproduction\" & Time !=0)\n\ndf_predobs_Reproduction_H_FWKe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Reproduction_H_FWKe, suffix = c(\"_obs\", \"_pred\")) |> \n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n\ndf_predobs_Weight_H_FWKe <- df_data_obs |> \n  filter(Time !=0) |>\n  left_join(df_pred_Weight_H_FWKe, suffix = c(\"_obs\", \"_pred\"))|>\n  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> \n  drop_na()\n```\n:::\n\n\n\n\n\n::: panel-tabset\n## A_FLYw\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W <- ggplot(\n  data = df_predobs_Weight_A_FLYw,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R <- ggplot(\n  data = df_predobs_Reproduction_A_FLYw,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs <- p_W + p_R +plot_layout(guides=\"collect\") +\n  plot_annotation(tag_levels = \"A\")\n\np_predobs\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_A_FLYw-1.png){#fig-predobs_A_FLYw width=768}\n:::\n:::\n\n\n\n\n\n\n\n## B_FLYe\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W <- ggplot(\n  data = df_predobs_Weight_B_FLYe,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R <- ggplot(\n  data = df_predobs_Reproduction_B_FLYe,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs <- p_W + p_R +plot_layout(guides=\"collect\") +\n  plot_annotation(tag_levels = \"A\")\n\np_predobs\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_B_FLYe-1.png){#fig-predobs_B_FLYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## C_CWYe\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W <- ggplot(\n  data = df_predobs_Weight_C_CWYe,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R <- ggplot(\n  data = df_predobs_Reproduction_C_CWYe,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs <- p_W + p_R +plot_layout(guides=\"collect\")\n\np_predobs\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_C_CWYe-1.png){#fig-predobs_C_CWYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## D_CWKe\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W <- ggplot(\n  data = df_predobs_Weight_D_CWKe,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R <- ggplot(\n  data = df_predobs_Reproduction_D_CWKe,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs <- p_W + p_R +plot_layout(guides=\"collect\") +\n  plot_annotation(tag_levels = \"A\")\n\np_predobs\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_D_CWKe-1.png){#fig-predobs_D_CWKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## E_CLYe\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W <- ggplot(\n  data = df_predobs_Weight_E_CLYe,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R <- ggplot(\n  data = df_predobs_Reproduction_E_CLYe,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs <- p_W + p_R +plot_layout(guides=\"collect\") +\n  plot_annotation(tag_levels = \"A\")\n\np_predobs\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_E_CLYe-1.png){#fig-predobs_E_CLYe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## F_CLKe\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W <- ggplot(\n  data = df_predobs_Weight_F_CLKe,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R <- ggplot(\n  data = df_predobs_Reproduction_F_CLKe,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs <- p_W + p_R +plot_layout(guides=\"collect\") +\n  plot_annotation(tag_levels = \"A\")\n\np_predobs\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_F_CLKe-1.png){#fig-predobs_F_CLKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## G_FLKe\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W <- ggplot(\n  data = df_predobs_Weight_G_FLKe,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R <- ggplot(\n  data = df_predobs_Reproduction_G_FLKe,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs <- p_W + p_R +plot_layout(guides=\"collect\") +\n  plot_annotation(tag_levels = \"A\")\n\np_predobs\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_G_FLKe-1.png){#fig-predobs_G_FLKe width=768}\n:::\n:::\n\n\n\n\n\n\n\n## H_FWKe\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W <- ggplot(\n  data = df_predobs_Weight_H_FWKe,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R <- ggplot(\n  data = df_predobs_Reproduction_H_FWKe,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = ID_experiment\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"Experiments\",\n    values = col_experiment\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs <- p_W + p_R +plot_layout(guides=\"collect\") +\n  plot_annotation(tag_levels = \"A\")\n\np_predobs\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_H_FWKe-1.png){#fig-predobs_H_FWKe width=768}\n:::\n:::\n\n\n\n\n\n\n:::\n\n### Folds\n\n\n\n\n\n::: {.cell tbl-cap='Folds for Weight and Reproduction for each model.'}\n\n```{.r .cell-code}\nNo_round <- 1\n\nf_count_fold <- function(df_predobs_Weight, df_predobs_Reproduction, No_round) {\n  \n  df_predobs_Weight <- df_predobs_Weight  |>\n  mutate(\n    Ratio_predobs = predict.endpoint / Weight_obs,\n    Residuals = predict.endpoint - Weight_obs\n  )\n  df_predobs_Reproduction <- df_predobs_Reproduction  |>\n  mutate(\n    Ratio_predobs = predict.endpoint / Reproduction_obs,\n    Residuals = predict.endpoint - Reproduction_obs\n  )\n  \n  Weight_count_fold2 <- round(length(subset(df_predobs_Weight, Ratio_predobs >= 0.5 & Ratio_predobs <= 2)$Weight_obs) / length(df_predobs_Weight$Weight_obs) * 100, No_round)\n\n  Weight_count_fold5 <- round(length(subset(df_predobs_Weight, Ratio_predobs >= 0.2 & Ratio_predobs <= 5)$Weight_obs) / length(df_predobs_Weight$Weight_obs) * 100, No_round)\n  \n  Repro_count_fold2 <- round(length(subset(df_predobs_Reproduction, Ratio_predobs >= 0.5 & Ratio_predobs <= 2)$Reproduction_obs) / length(df_predobs_Reproduction$Reproduction_obs) * 100, No_round)\n  \n  Repro_count_fold5 <- round(length(subset(df_predobs_Reproduction, Ratio_predobs >= 0.2 & Ratio_predobs <= 5)$Reproduction_obs) / length(df_predobs_Reproduction$Reproduction_obs) * 100, No_round)\n  \n  df_predobs_Reproduction_0 <- df_predobs_Reproduction |>\n    filter(Reproduction_obs > 0) \n  \n  Repro0_count_fold2 <- round(length(subset(df_predobs_Reproduction_0, Ratio_predobs >= 0.5 & Ratio_predobs <= 2)$Reproduction_obs) / length(df_predobs_Reproduction_0$Reproduction_obs) * 100, No_round)\n  \n  Repro0_count_fold5 <- round(length(subset(df_predobs_Reproduction_0, Ratio_predobs >= 0.2 & Ratio_predobs <= 5)$Reproduction_obs) / length(df_predobs_Reproduction_0$Reproduction_obs) * 100, No_round)\n  \n  df_fold <- data.frame(\n    Endpoint = c(\"Weight\", \"Reproduction\", \"Observed reproduction above 0\"),\n    '% of predictions in fold 2' = c(Weight_count_fold2, Repro_count_fold2, Repro0_count_fold2),\n    '% of predictions in fold 5' = c(Weight_count_fold5, Repro_count_fold5, Repro0_count_fold5),\n  check.names = FALSE\n  )\n  \n  return(df_fold)\n\n}\n\nlist_weight <- mget(paste0(\"df_predobs_Weight_\", list_models))\nlist_repro  <- mget(paste0(\"df_predobs_Reproduction_\", list_models))\n\ndf_fold <- purrr::map2_dfr(\n  list_weight,\n  list_repro,\n  f_count_fold,\n  .id = \"Model\"\n)\n\ndf_fold <- df_fold %>%\n  dplyr::mutate(Model = str_remove(Model, \"df_predobs_(Weight|Reproduction)_\"))\n\ndf_fold |> datatable(\n  options = list(\n    dom = 't',\n    pageLength = nrow(df_fold),\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n    )\n  ),\n  class = \"hover\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-02e7a35b545168189964\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-02e7a35b545168189964\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\"],[\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\"],[\"Weight\",\"Reproduction\",\"Observed reproduction above 0\",\"Weight\",\"Reproduction\",\"Observed reproduction above 0\",\"Weight\",\"Reproduction\",\"Observed reproduction above 0\",\"Weight\",\"Reproduction\",\"Observed reproduction above 0\",\"Weight\",\"Reproduction\",\"Observed reproduction above 0\",\"Weight\",\"Reproduction\",\"Observed reproduction above 0\",\"Weight\",\"Reproduction\",\"Observed reproduction above 0\",\"Weight\",\"Reproduction\",\"Observed reproduction above 0\"],[95,23,79,4,24,82,49,24,82,100,23,79,88,24,82,96,25,85,95,23,79,99,25,85],[100,26,88,18,28,94,100,29,97,100,26,88,100,29,97,100,28,94,100,26,88,100,28,94]],\"container\":\"<table class=\\\"hover\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Model<\\/th>\\n      <th>Endpoint<\\/th>\\n      <th>% of predictions in fold 2<\\/th>\\n      <th>% of predictions in fold 5<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":24,\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Model\",\"targets\":1},{\"name\":\"Endpoint\",\"targets\":2},{\"name\":\"% of predictions in fold 2\",\"targets\":3},{\"name\":\"% of predictions in fold 5\",\"targets\":4}],\"order\":[],\"orderClasses\":false,\"lengthMenu\":[10,24,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\n### RMSE per experiment\n\n\n\n\n\n::: {.cell tbl-cap='RMSE for Weight and Reproduction per experiment for each model.'}\n\n```{.r .cell-code}\nf_RMSE_experiment <- function(df_predobs_Weight, df_predobs_Reproduction){\n  \n  df_rmse_W <- df_predobs_Weight %>%\n    group_by(ID_experiment) %>%\n    summarise(\n      RMSE_Weight = sqrt(mean((predict.endpoint - Weight_obs)^2, na.rm = TRUE))\n    )\n  \n  df_rmse_R <- df_predobs_Reproduction %>%\n    group_by(ID_experiment) %>%\n    summarise(\n      RMSE_Reproduction = sqrt(mean((predict.endpoint - Reproduction_obs)^2, na.rm = TRUE))\n    )\n  \n  df_rmse <- left_join(df_rmse_W, df_rmse_R)\n  \n  return(df_rmse)\n}\n\n\ndf_rmse <- purrr::map2_dfr(\n  list_weight,\n  list_repro,\n  f_RMSE_experiment,\n  .id = \"Model\"\n)\n\ndf_rmse <- df_rmse %>%\n  dplyr::mutate(Model = str_remove(Model, \"df_predobs_(Weight|Reproduction)_\")) %>%\n  pivot_longer(\n    cols = starts_with(\"RMSE\"),\n    names_to = \"Metric\",\n    values_to = \"RMSE\"\n  )\n\ndf_rmse |>\n  pivot_wider(\n    names_from = Metric,\n    values_from = RMSE\n  ) |> \n  datatable(\n  options = list(\n    dom = 't',\n    pageLength = nrow(df_rmse),\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n    )\n  ),\n  class = \"hover\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-a7c31faf572db57a45fc\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-a7c31faf572db57a45fc\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\"],[\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"A_FLYw\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"B_FLYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"C_CWYe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"D_CWKe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"E_CLYe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"F_CLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"G_FLKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\",\"H_FWKe\"],[\"Bart2019_XP1_1\",\"Bart2019_XP1_2\",\"Bart2019_XP3\",\"Bart2019_XP4_1\",\"Bart2019_XP4_2\",\"Bart2019_XP5\",\"Bart2020\",\"Gollot2026_dens_D1\",\"Gollot2026_dens_D2\",\"Gollot2026_dens_D2b\",\"Gollot2026_dens_D5\",\"Gollot2026_dens_D7\",\"Bart2019_XP1_1\",\"Bart2019_XP1_2\",\"Bart2019_XP3\",\"Bart2019_XP4_1\",\"Bart2019_XP4_2\",\"Bart2019_XP5\",\"Bart2020\",\"Gollot2026_dens_D1\",\"Gollot2026_dens_D2\",\"Gollot2026_dens_D2b\",\"Gollot2026_dens_D5\",\"Gollot2026_dens_D7\",\"Bart2019_XP1_1\",\"Bart2019_XP1_2\",\"Bart2019_XP3\",\"Bart2019_XP4_1\",\"Bart2019_XP4_2\",\"Bart2019_XP5\",\"Bart2020\",\"Gollot2026_dens_D1\",\"Gollot2026_dens_D2\",\"Gollot2026_dens_D2b\",\"Gollot2026_dens_D5\",\"Gollot2026_dens_D7\",\"Bart2019_XP1_1\",\"Bart2019_XP1_2\",\"Bart2019_XP3\",\"Bart2019_XP4_1\",\"Bart2019_XP4_2\",\"Bart2019_XP5\",\"Bart2020\",\"Gollot2026_dens_D1\",\"Gollot2026_dens_D2\",\"Gollot2026_dens_D2b\",\"Gollot2026_dens_D5\",\"Gollot2026_dens_D7\",\"Bart2019_XP1_1\",\"Bart2019_XP1_2\",\"Bart2019_XP3\",\"Bart2019_XP4_1\",\"Bart2019_XP4_2\",\"Bart2019_XP5\",\"Bart2020\",\"Gollot2026_dens_D1\",\"Gollot2026_dens_D2\",\"Gollot2026_dens_D2b\",\"Gollot2026_dens_D5\",\"Gollot2026_dens_D7\",\"Bart2019_XP1_1\",\"Bart2019_XP1_2\",\"Bart2019_XP3\",\"Bart2019_XP4_1\",\"Bart2019_XP4_2\",\"Bart2019_XP5\",\"Bart2020\",\"Gollot2026_dens_D1\",\"Gollot2026_dens_D2\",\"Gollot2026_dens_D2b\",\"Gollot2026_dens_D5\",\"Gollot2026_dens_D7\",\"Bart2019_XP1_1\",\"Bart2019_XP1_2\",\"Bart2019_XP3\",\"Bart2019_XP4_1\",\"Bart2019_XP4_2\",\"Bart2019_XP5\",\"Bart2020\",\"Gollot2026_dens_D1\",\"Gollot2026_dens_D2\",\"Gollot2026_dens_D2b\",\"Gollot2026_dens_D5\",\"Gollot2026_dens_D7\",\"Bart2019_XP1_1\",\"Bart2019_XP1_2\",\"Bart2019_XP3\",\"Bart2019_XP4_1\",\"Bart2019_XP4_2\",\"Bart2019_XP5\",\"Bart2020\",\"Gollot2026_dens_D1\",\"Gollot2026_dens_D2\",\"Gollot2026_dens_D2b\",\"Gollot2026_dens_D5\",\"Gollot2026_dens_D7\"],[0.06450312460942989,0.1824740711315384,0.1341096382346796,0.08099296472800895,0.1967910147416431,0.07614273064701768,0.08404166278618636,0.1317461976609143,0.1672164434008908,0.09783347390416021,0.05900065395479389,0.08891999792861052,0.3185160668106758,0.9984501233598974,0.2274772932445012,0.2695480613751006,0.5747189905017797,0.3028986967907611,0.3544982138618834,0.4265077826794232,0.7433191967204876,0.6828652733144269,0.5684088563597041,0.215457552380074,0.2363795398548619,0.441511394868729,0.02483244657912306,0.2041397206789048,0.2862801207752681,0.2312794156059814,0.2712768428254831,0.3287795444146225,0.4730686004318953,0.3977403778602645,0.3031434019413218,0.1233695049399818,0.06649899415261581,0.1739872604408522,0.03552751820000765,0.04459812332851015,0.1395829316893542,0.06829730650106194,0.101791463500585,0.1195888867718403,0.1661588490031251,0.08405343326241944,0.03392986346026494,0.08265638580660609,0.1595593502004179,0.274577418967297,0.04801670282979664,0.1308474848301736,0.217857101447957,0.1517672451126678,0.1969342464277397,0.2477371557360732,0.3175148723785514,0.2452452392315353,0.1971166867950075,0.04904926455390789,0.04726411536798853,0.1231279723118434,0.07278659925324081,0.05570279433731311,0.1221464562710093,0.04212346988044278,0.06679329690058242,0.0991427095890499,0.1442458289331638,0.07394203260528477,0.06330611245184431,0.09529884239943753,0.08022727741844603,0.1631336061061861,0.1049448636874055,0.08444584751413921,0.1918945493424238,0.0763809715301714,0.1068961137040823,0.1564150012779573,0.1734638948519867,0.1071808111582292,0.1161348769325085,0.04648591609550852,0.1089660199872402,0.2132220010623036,0.09151740245350198,0.08083839075372079,0.2202311657593475,0.1044514871674884,0.1434042432308587,0.1842020011397036,0.211104288431937,0.1329471071645261,0.07734079620674546,0.02907358399324226],[1e-06,9.723617188865854,0.3130400000014974,1e-06,4.238970952094443,1e-06,1e-06,1e-06,2.287196181035879,6.564444128823141,3.998592379088005,1e-06,1e-06,7.304078887903289,1e-06,1e-06,3.478962789490343,1e-06,1e-06,1e-06,1.757330522329726,6.087982732476448,4.930259529909883,1e-06,1e-06,8.826220389250381,0.361616597237409,1e-06,8.166209015830864,1e-06,1e-06,1e-06,3.431271157338713,5.609164702424104,2.791404924657714,1e-06,1e-06,6.644092511365241,0.009186350051026793,1e-06,5.265512998617607,1e-06,1e-06,1e-06,5.86851491362457,8.078638074899544,4.779985390873235,1e-06,1e-06,5.184029083200081,0.007315475064076496,1e-06,5.55219305212648,1e-06,1e-06,1e-06,1.691652945174367,7.002576444535318,1.342269177589205,1e-06,1e-06,3.295074111896692,0.003053500153512359,1e-06,4.340310906028021,1e-06,1e-06,1e-06,0.7741120702747116,9.008718896115369,3.686060666493431,1e-06,1e-06,7.291984499184728,1e-06,1e-06,4.116159938087478,1e-06,1e-06,1e-06,2.316565715366559,7.783196172412108,1.027053252871534,1e-06,1e-06,9.358252829679666,1e-06,1e-06,5.016592581508677,1e-06,1e-06,1e-06,2.066450334419576,7.039975877972914,3.383093637126708,1e-06]],\"container\":\"<table class=\\\"hover\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Model<\\/th>\\n      <th>ID_experiment<\\/th>\\n      <th>RMSE_Weight<\\/th>\\n      <th>RMSE_Reproduction<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":192,\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Model\",\"targets\":1},{\"name\":\"ID_experiment\",\"targets\":2},{\"name\":\"RMSE_Weight\",\"targets\":3},{\"name\":\"RMSE_Reproduction\",\"targets\":4}],\"order\":[],\"orderClasses\":false,\"lengthMenu\":[10,25,50,100,192]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nID_exp_plot_1 <- unique(df_rmse$ID_experiment)[1:6]\nID_exp_plot_2 <- unique(df_rmse$ID_experiment)[7:12]\n\nylim_metric <- df_rmse |>\n  group_by(Metric) |>\n  summarise(\n    ymin = min(RMSE, na.rm = TRUE),\n    ymax = max(RMSE, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nmake_plot <- function(data, ids, metric_name) {\n  \n  lims <- ylim_metric |>\n    filter(Metric == metric_name)\n  \n  ggplot(\n    subset(data, ID_experiment %in% ids & Metric == metric_name),\n    aes(\n      x = Model,\n      y = RMSE,\n      color = Model\n    )\n  ) +\n    geom_point(size = 2) +\n    facet_grid(\n      . ~ ID_experiment\n    ) +\n    coord_cartesian(\n      ylim = c(lims$ymin, lims$ymax)\n    ) +\n    scale_color_manual(\n      name = \"Models\",\n      values = c(Nord_aurora, Nord_frost)\n    ) +\n    theme_bw() +\n    theme(\n      axis.text.x = element_text(angle = 45, hjust = 1, size = 8),\n      strip.text = element_text(size = 8)\n    ) +\n    labs(\n      x = \"Model\",\n      y = \"RMSE\"\n    )\n}\n\np1_metric1 <- make_plot(df_rmse, ID_exp_plot_1, unique(df_rmse$Metric)[1]) +\n  labs(title = \"RMSE Weight\") +\n  theme(\n    axis.title.x = element_blank()\n  )\np2_metric1 <- make_plot(df_rmse, ID_exp_plot_2, unique(df_rmse$Metric)[1])\n\np1_metric2 <- make_plot(df_rmse, ID_exp_plot_1, unique(df_rmse$Metric)[2]) +\n  labs(title = \"RMSE Reproduction\") +\n  theme(\n    axis.title.x = element_blank()\n  )\np2_metric2 <- make_plot(df_rmse, ID_exp_plot_2, unique(df_rmse$Metric)[2])\n\np <- (\n  p1_metric1 / p2_metric1 /\n  p1_metric2 / p2_metric2\n) +\n  plot_layout(guides = \"collect\")\n\np\n```\n\n::: {.cell-output-display}\n![RMSE per experiment.](E_Model_comparison_files/figure-html/fig-rmse-1.png){#fig-rmse width=1152}\n:::\n:::\n\n\n\n\n\n\n\n## Predicted trajectories for Weight and Reproduction\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNb_experiment <- 12\nlim_yrepro <- 100\nstep_sim <- 0.05\nselect_times <- seq(0,400, 0.1)\n\nEndpoints_print <- \"Weight,\n    Reproduction\"\n\n\nl_param_name_A_FLYw <- names(Summary_res_A_FLYw) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_Setpoint_full(\n  path_A_FLYw, l_Experiments_fit, \n  Adults_alone, OM_diff, \n  l_param_name_A_FLYw, step_sim, Endpoints_print\n  )\n\nl_param_name_B_FLYe <- names(Summary_res_B_FLYe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_Setpoint_full(\n  path_B_FLYe, l_Experiments_fit, \n  Adults_alone, OM_diff, \n  l_param_name_B_FLYe, step_sim, Endpoints_print\n  )\n\nl_param_name_C_CWYe <- names(Summary_res_C_CWYe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_Setpoint_full(\n  path_C_CWYe, l_Experiments_fit, \n  Adults_alone, OM_diff, \n  l_param_name_C_CWYe, step_sim, Endpoints_print\n  )\n\nl_param_name_D_CWKe <- names(Summary_res_D_CWKe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_Setpoint_full(\n  path_D_CWKe, l_Experiments_fit, \n  Adults_alone, OM_diff, \n  l_param_name_D_CWKe, step_sim, Endpoints_print\n  )\n\nl_param_name_E_CLYe <- names(Summary_res_E_CLYe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_Setpoint_full(\n  path_E_CLYe, l_Experiments_fit, \n  Adults_alone, OM_diff, \n  l_param_name_E_CLYe, step_sim, Endpoints_print\n  )\n\nl_param_name_F_CLKe <- names(Summary_res_F_CLKe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_Setpoint_full(\n  path_F_CLKe, l_Experiments_fit, \n  Adults_alone, OM_diff, \n  l_param_name_F_CLKe, step_sim, Endpoints_print\n  )\n\nl_param_name_G_FLKe <- names(Summary_res_G_FLKe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_Setpoint_full(\n  path_G_FLKe, l_Experiments_fit, \n  Adults_alone, OM_diff, \n  l_param_name_G_FLKe, step_sim, Endpoints_print\n  )\n\nl_param_name_H_FWKe <- names(Summary_res_H_FWKe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_Setpoint_full(\n  path_H_FWKe, l_Experiments_fit, \n  Adults_alone, OM_diff, \n  l_param_name_H_FWKe, step_sim, Endpoints_print\n  )\n```\n:::\n\n::: {.cell execute='false'}\n\n```{.bash .cell-code}\nfor j in $(seq 1 12); do\n./mcsim.DEBcali DEB_setpoint_full_${j}.in\ndone\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwidth_plot <- 12\nheight_plot <- 12\n\nfile_rds_A_FLYw <- file.path(path_A_FLYw, paste0(\"Sim.Res.Exp.full.rds\"))\n\nif (file.exists(file_rds_A_FLYw)) {\n  df_pred_full_A_FLYw <- readRDS(file_rds_A_FLYw)\n} else {\n  df_pred_full_A_FLYw <- f_read_Setpoint_full(path_A_FLYw, l_Experiments_fit, Adults_alone = FALSE, Nb_experiment, select_times, step_sim)\n}\n\nfile_rds_B_FLYe <- file.path(path_B_FLYe, paste0(\"Sim.Res.Exp.full.rds\"))\n\nif (file.exists(file_rds_B_FLYe)) {\n  df_pred_full_B_FLYe <- readRDS(file_rds_B_FLYe)\n} else {\n  df_pred_full_B_FLYe <- f_read_Setpoint_full(path_B_FLYe, l_Experiments_fit, Adults_alone = FALSE, Nb_experiment, select_times, step_sim)\n}\n\nfile_rds_C_CWYe <- file.path(path_C_CWYe, paste0(\"Sim.Res.Exp.full.rds\"))\n\nif (file.exists(file_rds_C_CWYe)) {\n  df_pred_full_C_CWYe <- readRDS(file_rds_C_CWYe)\n} else {\n  df_pred_full_C_CWYe <- f_read_Setpoint_full(path_C_CWYe, l_Experiments_fit, Adults_alone = FALSE, Nb_experiment, select_times, step_sim)\n}\n\nfile_rds_D_CWKe <- file.path(path_D_CWKe, paste0(\"Sim.Res.Exp.full.rds\"))\n\nif (file.exists(file_rds_D_CWKe)) {\n  df_pred_full_D_CWKe <- readRDS(file_rds_D_CWKe)\n} else {\n  df_pred_full_D_CWKe <- f_read_Setpoint_full(path_D_CWKe, l_Experiments_fit, Adults_alone = FALSE, Nb_experiment, select_times, step_sim)\n}\n\nfile_rds_E_CLYe <- file.path(path_E_CLYe, paste0(\"Sim.Res.Exp.full.rds\"))\n\nif (file.exists(file_rds_E_CLYe)) {\n  df_pred_full_E_CLYe <- readRDS(file_rds_E_CLYe)\n} else {\n  df_pred_full_E_CLYe <- f_read_Setpoint_full(path_E_CLYe, l_Experiments_fit, Adults_alone = FALSE, Nb_experiment, select_times, step_sim)\n}\n\nfile_rds_F_CLKe <- file.path(path_F_CLKe, paste0(\"Sim.Res.Exp.full.rds\"))\n\nif (file.exists(file_rds_F_CLKe)) {\n  df_pred_full_F_CLKe <- readRDS(file_rds_F_CLKe)\n} else {\n  df_pred_full_F_CLKe <- f_read_Setpoint_full(path_F_CLKe, l_Experiments_fit, Adults_alone = FALSE, Nb_experiment, select_times, step_sim)\n}\n\nfile_rds_G_FLKe <- file.path(path_G_FLKe, paste0(\"Sim.Res.Exp.full.rds\"))\n\nif (file.exists(file_rds_G_FLKe)) {\n  df_pred_full_G_FLKe <- readRDS(file_rds_G_FLKe)\n} else {\n  df_pred_full_G_FLKe <- f_read_Setpoint_full(path_G_FLKe, l_Experiments_fit, Adults_alone = FALSE, Nb_experiment, select_times, step_sim)\n}\n\nfile_rds_H_FWKe <- file.path(path_H_FWKe, paste0(\"Sim.Res.Exp.full.rds\"))\n\nif (file.exists(file_rds_H_FWKe)) {\n  df_pred_full_H_FWKe <- readRDS(file_rds_H_FWKe)\n} else {\n  df_pred_full_H_FWKe <- f_read_Setpoint_full(path_H_FWKe, l_Experiments_fit, Adults_alone = FALSE, Nb_experiment, select_times, step_sim)\n}\n\nmax_up <- 1.5\n```\n:::\n\n\n\n\n\n::: panel-tabset\n## A_FLYw\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_A_FLYw-1.png){#fig-pred_A_FLYw width=1152}\n:::\n:::\n\n\n\n\n\n\n\n## B_FLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_B_FLYe-1.png){#fig-pred_B_FLYe width=1152}\n:::\n:::\n\n\n\n\n\n\n\n## C_CWYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_C_CWYe-1.png){#fig-pred_C_CWYe width=1152}\n:::\n:::\n\n\n\n\n\n\n\n## D_CWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_D_CWKe-1.png){#fig-pred_D_CWKe width=1152}\n:::\n:::\n\n\n\n\n\n\n\n## E_CLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_E_CLYe-1.png){#fig-pred_E_CLYe width=1152}\n:::\n:::\n\n\n\n\n\n\n\n## F_CLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_F_CLKe-1.png){#fig-pred_F_CLKe width=1152}\n:::\n:::\n\n\n\n\n\n\n\n## G_FLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_G_FLKe-1.png){#fig-pred_G_FLKe width=1152}\n:::\n:::\n\n\n\n\n\n\n\n## H_FWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_H_FWKe-1.png){#fig-pred_H_FWKe width=1152}\n:::\n:::\n\n\n\n\n\n\n:::\n\n::: panel-tabset\n## A_FLYw\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_A_FLYwr-1.png){#fig-pred_A_FLYwr width=1152}\n:::\n:::\n\n\n\n\n\n## B_FLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_B_FLYer-1.png){#fig-pred_B_FLYer width=1152}\n:::\n:::\n\n\n\n\n\n## C_CWYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_C_CWYer-1.png){#fig-pred_C_CWYer width=1152}\n:::\n:::\n\n\n\n\n\n## D_CWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_D_CWKer-1.png){#fig-pred_D_CWKer width=1152}\n:::\n:::\n\n\n\n\n\n## E_CLYe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_E_CLYer-1.png){#fig-pred_E_CLYer width=1152}\n:::\n:::\n\n\n\n\n\n## F_CLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_F_CLKer-1.png){#fig-pred_F_CLKer width=1152}\n:::\n:::\n\n\n\n\n\n## G_FLKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_G_FLKer-1.png){#fig-pred_G_FLKer width=1152}\n:::\n:::\n\n\n\n\n\n## H_FWKe\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted Weight and Reproduction for each experiment.](E_Model_comparison_files/figure-html/fig-pred_H_FWKer-1.png){#fig-pred_H_FWKer width=1152}\n:::\n:::\n\n\n\n\n:::\n\nCalibration of all tested model formulations was achieved using three MCMC chains. Convergence diagnostics indicated satisfactory mixing and convergence overall, with chains converging toward similar posterior distributions and Gelman–Rubin statistics close to 1 ($\\hat{R}$). However, for some model formulations, posterior estimates of specific parameters approached the upper or lower bounds of their biologically constrained priors, suggesting limited parameter identifiability or weak support for these formulations. Model comparison based on BIC revealed substantial differences among formulations (@tbl-ResModels).\n\nThe two best-supported models shared three common characteristics: (i) a progressive change in energy allocation after maturation (C), (ii) a normalized hyperbolic functional response (K), and (iii) a formulation in which reserve contribution to fresh body mass was independent of structural size (e). The only difference between these two formulations concerned the scaling of the maximum searching rate, which was either structural-mass-specific (W) or surface-area-specific (L) : model W.K.C.e (BIC = 25.5) and model L.K.C.e (BIC = -31.3). whereas all other formulations had considerably higher BIC values (103-597).\n\nModels assuming a fixed allocation rule throughout the life cycle (F) systematically resulted in poorer fits. Similarly, models using the classical hyperbolic formulation for the functional response (Y) showed much higher BIC values than those using the normalized formulation (K). In practice, these formulations systematically failed to reproduce observed growth trajectories, with predicted assimilation remaining insufficient to sustain realistic growth across experiments. Models assuming reserve contribution proportional to structure (w) also performed less well than formulations assuming reserve independence (e) (see Supplementary information Section S2).\n\nAlthough the two best models had substantially different BIC values ($\\Delta$BIC = 56.8), both provided qualitatively similar predictions for most datasets. However, they greatly differed for the key experiment Bart2019_XP3, where earthworms were alternately fed with soil only and soil supplemented with horse dung. The model with a structural-mass-specific maximum searching rate (W.K.C.e) reproduced the observed growth trajectory more accurately during the final phase of the experiment. This difference was reflected by a lower weight RMSE for the W.K.C.e compared with L.K.C.e (0.039 vs. 0.067, respectively). Consequently, despite a higher overall BIC, only W.K.C.e was retained for subsequent analyses because it provided a substantially better fit for Bart2019_XP3 while producing similar fits for the other experiments (@fig-pred_D_CWKe & fig-pred_F_CLKe).\n\nParameter estimates for the retained model are presented in @tbl-ResModels. Parameter values were generally consistent between W.K.C.e and L.K.C.e, with as expected, the main differences concerning the ingestion-related parameters $[\\dot{F}_m]$, $\\{\\dot{F}_m\\}$ and $K$. For both formulations, posterior estimates of the maximum searching rate approached the upper bound of the prior distribution.\n\nAlthough the retained model adequately reproduced the main growth and reproduction trajectories across experiments (W.K.C.e), some condition-specific deviations remained. For body mass, grouped individuals under low-food conditions (Bart2019_XP4_2) showed an overestimation of the adult plateau, whereas the adult plateau was well estimated for grouped individuals under high-food conditions (Bart2019_XP1_2). In the density experiments at densities 2 and 5 (Gollot2026_D2 and Gollot2026_D5), the transition between juvenile growth and the adult plateau remained more abrupt in simulations than in observations, despite the introduction of a progressive allocation transition over the timescale parameter ($\\tau$). In contrast, this transition was more accurately reproduced for individuals at density 2 with increased food supply (Gollot2026_D2b). Finally, the timing of maturation was overestimated in the density 5 condition (Gollot2026_D5).\n\nFor reproduction, the main deviations also corresponded to specific experimental conditions rather than to a general model bias. For grouped individuals under low-food conditions (Bart2019_XP4_2), observed reproduction decreased when density increased from three to six individuals per cosm, whereas the model predicted similar reproductive outputs between the two conditions. For individuals at density 2 with increased food supply (Gollot2026_D2b), reproductive output was overestimated, with observed reproduction remaining substantially lower than predicted by the model.\n\n## Organic matter dynamic and functional response\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath_D_OM <- here::here(\"mod/D_DEB_CWKe/OM_study\")\n\nMCMC_out_D_OM <- f_MCSim(path_D_OM)\nL_parameters_D_OM <- unique(MCMC_out_D_OM$Priors$Nom)\n\nSummary_res_D_OM <- \n  as.data.frame(MCMC_out_D_OM$Summary_res)[1:length(L_parameters_D_OM)] |> \n  mutate(Model = \"D_OM\") \n\nNb_experiment <- 12\nstep_sim <- 0.05\nselect_times <- seq(0,400, 0.1)\n\nEndpoints_print <- \"freal,\n    OMsoil,\n    OMhorse,\n    OM_soil_out,\n    OM_horse_out,\n    Q_soil,\n    Q_horse,\n    Qf_soil,\n    Qf_horse,\n    Q_matter,\n    Q_mattermax,\n    Weight\"\n\n\nl_param_name_D_OM <- names(Summary_res_D_OM) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_Setpoint_full(\n  path_D_OM, l_Experiments_fit, \n  Adults_alone = FALSE, OM_diff = TRUE, \n  l_param_name_D_OM, step_sim, Endpoints_print\n  )\n\n# for j in $(seq 1 12); do\n# ./mcsim.DEBcali DEB_setpoint_full_${j}.in\n# done\n\nfile_rds_D_OM <- file.path(path_D_OM, paste0(\"Sim.Res.Exp.full.rds\"))\n\nif (file.exists(file_rds_D_OM)) {\n  df_pred_full_D_OM <- readRDS(file_rds_D_OM)\n} else {\n  df_pred_full_D_OM <- f_read_Setpoint_full(path_D_OM, Adults_alone = FALSE, l_Experiments_fit, Nb_experiment, select_times, step_sim, bol_OM = TRUE)\n}\n\ndf_pred_full_D_OM_wide <- df_pred_full_D_OM |> \n  pivot_wider(\n    id_cols = c(Time, ID_experiment),\n    names_from = Endpt, \n    values_from = predict.endpoint\n    ) |>\n  mutate(\n    OMtot = OMhorse + OMsoil\n    )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncol_D2 <- Nord_polar[1]\ncol_D2b <- Nord_polar[4]\ntype_D2b <- \"solid\"\ntype_D2 <- \"dotted\"\n\nline_width <- 0.6\nfont_size <- 10\nt_max <- 155\n\n\ndf_pred_full_D_OM_wide_D22b <- df_pred_full_D_OM_wide |> filter(ID_experiment %in% c(\"Gollot2026_dens_D2\", \"Gollot2026_dens_D2b\"))\n\np_freal_food <- ggplot(\n    data = df_pred_full_D_OM_wide_D22b,\n    aes(\n      x = Time,\n      y = freal,\n      color = ID_experiment,\n      linetype = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = c(\"1.5 g/ind/14d (D2)\", \"3 g/ind/14d (D2b)\"),\n    values = c(col_D2, col_D2b)\n    )+\n  scale_linetype_manual(\n    name = \"Condition\",\n    label = c(\"1.5 g/ind/14d (D2)\", \"3 g/ind/14d (D2b)\"),\n    values = c(type_D2, type_D2b)\n  )+\n  labs(\n    x = \"Time (days)\",\n    y = \"Functional response, f (-)\"\n  )+\n  lims(y = c(0,1))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_OM_food <- ggplot(\n    data = df_pred_full_D_OM_wide_D22b,\n    aes(\n      x = Time,\n      y = OMtot,\n      color = ID_experiment,\n      linetype = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = c(\"1.5 g/ind/14d (D2)\", \"3 g/ind/14d (D2b)\"),\n    values = c(col_D2, col_D2b)\n    )+\n  scale_linetype_manual(\n    name = \"Condition\",\n    label = c(\"1.5 g/ind/14d (D2)\", \"3 g/ind/14d (D2b)\"),\n    values = c(type_D2, type_D2b)\n  )+\n  labs(\n    x = \"Time (days)\",\n    y = \"OM in the cosm (g)\"\n  )+\n  lims(y = c(0,18))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_OMhorse_food <- ggplot(\n    data = df_pred_full_D_OM_wide_D22b,\n    aes(\n      x = Time,\n      y = OMhorse,\n      color = ID_experiment,\n      linetype = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = c(\"1.5 g/ind/14d (D2)\", \"3 g/ind/14d (D2b)\"),\n    values = c(col_D2, col_D2b)\n    )+\n  scale_linetype_manual(\n    name = \"Condition\",\n    label = c(\"1.5 g/ind/14d (D2)\", \"3 g/ind/14d (D2b)\"),\n    values = c(type_D2, type_D2b)\n  )+\n  labs(\n    x = \"Time (days)\",\n    y = \"OM horse in the cosm (g)\"\n  )+\n # lims(y = c(0,18))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_OMsoil_food <- ggplot(\n    data = df_pred_full_D_OM_wide_D22b,\n    aes(\n      x = Time,\n      y = OMsoil,\n      color = ID_experiment,\n      linetype = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = c(\"1.5 g/ind/14d (D2)\", \"3 g/ind/14d (D2b)\"),\n    values = c(col_D2, col_D2b)\n    )+\n  scale_linetype_manual(\n    name = \"Condition\",\n    label = c(\"1.5 g/ind/14d (D2)\", \"3 g/ind/14d (D2b)\"),\n    values = c(type_D2, type_D2b)\n  )+\n  #lims(y = c(0,18))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  labs(\n    x = \"Time (days)\",\n    y = \"OM soil in the cosm (g)\"\n  )+\n  theme_minimal(font_size)\n\np_food <- p_freal_food + p_OM_food + p_OMhorse_food + p_OMsoil_food + plot_layout(ncol=1, guides = \"collect\") &\n  theme(legend.position = \"bottom\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npal_dens_dens <- c(\"#B48EAD\", \"#5E81AC\", \"#88C0D0\", \"#8FBCBB\")\ntype_D2b <- \"solid\"\ntype_D2 <- \"dotted\"\nline_width <- 0.6\nfont_size <- 10\nt_max <- 155\n\nlim_y_OM <- 15\n\ndf_pred_full_D_OM_wide_D <- df_pred_full_D_OM_wide |> filter(ID_experiment %in% c(\"Gollot2026_dens_D1\", \"Gollot2026_dens_D2\", \"Gollot2026_dens_D5\", \"Gollot2026_dens_D7\"))\n\nl_labels <- c(\"1 ind.\", \"2 ind.\", \"5 ind.\", \"7 ind.\")\n\np_W <- ggplot(\n    data = df_pred_full_D_OM_wide_D,\n    aes(\n      x = Time,\n      y = Weight,\n      color = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = l_labels,\n    values = pal_dens_dens\n    )+\n  labs(\n    x = \"Time (days)\",\n    y = \"Weight (g)\"\n  )+\n  lims(y = c(0,1))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_Qmatter <- ggplot(\n    data = df_pred_full_D_OM_wide_D,\n    aes(\n      x = Time,\n      color = ID_experiment\n    )\n  )+\n  geom_line(\n    aes(\n      y = Q_matter_max\n    ),\n    linewidth = line_width,\n    linetype = 2\n    )+\n  geom_line(\n    aes(\n      y = Q_matter_Fm\n    ),\n    linewidth = line_width,\n    linetype = 1\n    )+\n  scale_color_manual(\n    name = \"Condition\",\n    label = l_labels,\n    values = pal_dens_dens\n    )+\n  labs(\n    x = \"Time (days)\",\n    y = \"Q_matter (g)\"\n  )+\n  #lims(y = c(0,1))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_freal_dens <- ggplot(\n    data = df_pred_full_D_OM_wide_D,\n    aes(\n      x = Time,\n      y = freal,\n      color = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = l_labels,\n    values = pal_dens_dens\n    )+\n  labs(\n    x = \"Time (days)\",\n    y = \"Functional response, f (-)\"\n  )+\n  lims(y = c(0,1))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_OM_dens <- ggplot(\n    data = df_pred_full_D_OM_wide_D,\n    aes(\n      x = Time,\n      y = OMtot,\n      color = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = l_labels,\n    values = pal_dens_dens\n    )+\n  labs(\n    x = \"Time (days)\",\n    y = \"OM in the cosm (g)\"\n  )+\n  lims(y = c(0,lim_y_OM))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_OMhorse_dens <- ggplot(\n    data = df_pred_full_D_OM_wide_D,\n    aes(\n      x = Time,\n      y = OMhorse,\n      color = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = l_labels,\n    values = pal_dens_dens\n    )+\n  labs(\n    x = \"Time (days)\",\n    y = \"OM horse in the cosm (g)\"\n  )+\n  lims(y = c(0,lim_y_OM))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_OMsoil_dens <- ggplot(\n    data = df_pred_full_D_OM_wide_D,\n    aes(\n      x = Time,\n      y = OMsoil,\n      color = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = l_labels,\n    values = pal_dens_dens\n    )+\n  lims(y = c(0,lim_y_OM))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  labs(\n    x = \"Time (days)\",\n    y = \"OM soil in the cosm (g)\"\n  )+\n  theme_minimal(font_size)\n\np_OM_horse_out <- ggplot(\n    data = df_pred_full_D_OM_wide_D,\n    aes(\n      x = Time,\n      y = OM_horse_out,\n      color = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = l_labels,\n    values = pal_dens_dens\n    )+\n  labs(\n    x = \"Time (days)\",\n    y = \"OM horse consummed (g/ind.)\"\n  )+\n  lims(y = c(0,NA))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_OM_soil_out <- ggplot(\n    data = df_pred_full_D_OM_wide_D,\n    aes(\n      x = Time,\n      y = OM_soil_out,\n      color = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = l_labels,\n    values = pal_dens_dens\n    )+\n  labs(\n    x = \"Time (days)\",\n    y = \"OM soil consummed (g/ind.)\"\n  )+\n  lims(y = c(0,NA))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_OM_horse_out_g <- ggplot(\n    data = df_pred_full_D_OM_wide_D,\n    aes(\n      x = Time,\n      y = OM_horse_out_g,\n      color = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = l_labels,\n    values = pal_dens_dens\n    )+\n  labs(\n    x = \"Time (days)\",\n    y = \"OM horse consummed (g/g ind.)\"\n  )+\n  lims(y = c(0,NA))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_OM_soil_out_g <- ggplot(\n    data = df_pred_full_D_OM_wide_D,\n    aes(\n      x = Time,\n      y = OM_soil_out_g,\n      color = ID_experiment\n    )\n  )+\n  geom_line(linewidth = line_width)+\n  scale_color_manual(\n    name = \"Condition\",\n    label = l_labels,\n    values = pal_dens_dens\n    )+\n  labs(\n    x = \"Time (days)\",\n    y = \"OM soil consummed (g/g ind.)\"\n  )+\n  lims(y = c(0,NA))+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  theme_minimal(font_size)\n\np_dens <- p_freal_dens + p_OM_dens + p_OMhorse_dens + p_OMsoil_dens + p_OM_horse_out + p_OM_soil_out  + plot_layout(ncol=2, guides = \"collect\") &\n  theme(legend.position = \"bottom\")\np <- p_freal_dens + p_freal_food + p_OM_dens + p_OM_food + plot_layout(ncol=2, guides = \"collect\") + \n  plot_annotation(tag_levels = \"A\") &\n  theme(legend.position = \"bottom\")\np\n```\n\n::: {.cell-output-display}\n![Predicted function response and organic matter dynamic.](E_Model_comparison_files/figure-html/fig-OMdynDens-1.png){#fig-OMdynDens width=768}\n:::\n:::\n\n\n\n\n\n\n\n## Environmental conditions and model performance\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels_Density_env <- c(\"1\", \"2\", \"5\", \"7\", \"Grouped\\nafter puberty\")\ncol_Density_env <- c(rev(Nord_aurora[1:4]), Nord_aurora[5])\n\nlevels_Food_env <- c(\"0.19 %\", \"0.22 %\", \"0.27 %\", \"0.34 %\", \"0.67 %\", \"1.3 %\", \"0 or 0.67 %\")\ncol_Food_env <- c(Nord_frost[2], rev(Nord_aurora[1:4]), Nord_aurora[5], Nord_polar[4])\n\nlevels_T_env <- c(\"15°C\", \"18°C\")\ncol_T_env <- c(Nord_frost[3], Nord_aurora[1])\n\ndf_Env_XP <- data.frame(\n  ID_experiment = l_Experiments_fit,\n  Density_env = c(\"1\", \"Grouped\\nafter puberty\", \"1\", \"1\", \"Grouped\\nafter puberty\", \n                  \"1\", \"1\", \"1\", \"2\", \"2\", \"5\", \"7\"),\n  Food_env = c(\"0.67 %\", \"0.67 %\", \"0 or 0.67 %\",  \"0.22 %\", \"0.22 %\", \"0.34 %\", \"0.67 %\", \"1.3 %\", \"0.67 %\", \"1.3 %\", \"0.27 %\", \"0.19 %\"),\n  T_env = c(\"15°C\", \"15°C\", \"15°C\", \"15°C\", \"15°C\", \"15°C\", \"15°C\", \"18°C\", \"18°C\", \"18°C\", \"18°C\", \"18°C\")\n) |> \n  mutate(\n    Density_env = factor(Density_env, levels = levels_Density_env),\n    Food_env = factor(Food_env, levels = levels_Food_env),\n    T_env = factor(T_env, levels = levels_T_env)\n  )\n\ndf_predobs_Reproduction_D_CWKe_plot <- df_predobs_Reproduction_D_CWKe |> \n  left_join(df_Env_XP) |> \n  mutate(\n    Density_env = case_when(\n      (ID_experiment == \"Bart2019_XP1_2\" & Time <= 84) ~ \"1\",\n      (ID_experiment == \"Bart2019_XP4_2\" & Time <= 112) ~ \"1\",\n      .default = Density_env\n    )\n  )\n\ndf_predobs_Weight_D_CWKe_plot <- df_predobs_Weight_D_CWKe |> \n  left_join(df_Env_XP) |> \n  mutate(\n    Density_env = case_when(\n      (ID_experiment == \"Bart2019_XP1_2\" & Time <= 84) ~ \"1\",\n      (ID_experiment == \"Bart2019_XP4_2\" & Time <= 112) ~ \"1\",\n      .default = Density_env\n    )\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W_Dens <- ggplot(\n  data = df_predobs_Weight_D_CWKe_plot,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  # geom_line(\n  #   data=df_line,\n  #   mapping=aes(x=x2, y=y2),\n  #   color = col_line2\n  #   )+\n  # geom_line(\n  #   data=df_line,\n  #   mapping=aes(x=x_2, y=y_2),\n  #   color = col_line2\n  #   )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = Density_env\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"Density (#)\",\n    values = col_Density_env\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R_Dens <- ggplot(\n  data = df_predobs_Reproduction_D_CWKe_plot,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = Density_env\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"Density (#)\",\n    values = col_Density_env\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs_Density <- p_W_Dens + p_R_Dens +plot_layout(guides=\"collect\") +\n  plot_annotation(tag_levels = \"A\")\n\np_predobs_Density\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_D_Dens-1.png){#fig-predobs_D_Dens width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W_Food <- ggplot(\n  data = df_predobs_Weight_D_CWKe_plot,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  # geom_line(\n  #   data=df_line,\n  #   mapping=aes(x=x2, y=y2),\n  #   color = col_line2\n  #   )+\n  # geom_line(\n  #   data=df_line,\n  #   mapping=aes(x=x_2, y=y_2),\n  #   color = col_line2\n  #   )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = Food_env\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"OM from horse\\ndung (%/ind/14d)\",\n    values = col_Food_env\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R_Food <- ggplot(\n  data = df_predobs_Reproduction_D_CWKe_plot,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = Food_env\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"OM from horse\\ndung (%/ind/14d)\",\n    values = col_Food_env\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs_Food <- p_W_Food + p_R_Food +plot_layout(guides=\"collect\") +\n  plot_annotation(tag_levels = \"A\")\n\np_predobs_Food\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_D_Food-1.png){#fig-predobs_D_Food width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfact_1 <- 2\nfact_2 <- 5\n\ncol_line0 <- Nord_polar[1]\ncol_line1 <- Nord_polar[4]\ncol_line2 <- Nord_snow[1]\n\ncol_experiment <- c(\n  Nord_aurora[1], Nord_aurora[1], Nord_polar[1],\n  Nord_aurora[2],\n  Nord_aurora[2], Nord_aurora[3],\n  Nord_aurora[4], \n  Nord_aurora[5], rev(Nord_frost)\n  )\n\nseq_line <- seq(0.01, 1.5, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_W_Temp <- ggplot(\n  data = df_predobs_Weight_D_CWKe_plot,\n  mapping = aes(\n      x = Weight_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  # geom_line(\n  #   data=df_line,\n  #   mapping=aes(x=x2, y=y2),\n  #   color = col_line2\n  #   )+\n  # geom_line(\n  #   data=df_line,\n  #   mapping=aes(x=x_2, y=y_2),\n  #   color = col_line2\n  #   )+\n  \n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n    color = T_env\n    ),\n    alpha = 0.5\n  )+\n  scale_x_log10(\n    labels = scales::label_number()\n    )+\n  scale_y_log10(\n    labels = scales::label_number()\n    )+\n  scale_color_manual(\n    name = \"Temperature (°C)\",\n    values = col_T_env\n    )+\n  labs(\n    x = \"Observed weight of earthworms (g)\",\n    y = \"Predicted weight of earthworms (g)\"\n  )+\n  theme_minimal()\n\nfact_1 <- 2\nfact_2 <- 5\n\nseq_line <- seq(0.01, 100, 0.01)\n\ndf_line <- data.frame(\n  x1  = seq_line,\n  y1  = seq_line*fact_1,\n  x_1 = seq_line,\n  y_1 = seq_line/fact_1,\n  x2  = seq_line,\n  y2  = seq_line*fact_2,\n  x_2 = seq_line,\n  y_2 = seq_line/fact_2\n  )\n\np_R_Temp <- ggplot(\n  data = df_predobs_Reproduction_D_CWKe_plot,\n  mapping = aes(\n      x = Reproduction_obs,\n      y = predict.endpoint\n    )\n  )+\n  geom_path(\n    data=df_line,\n    mapping=aes(x=x1, y=y1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_1, y=y_1),\n    color = col_line1\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x2, y=y2),\n    color = col_line2\n    )+\n  geom_line(\n    data=df_line,\n    mapping=aes(x=x_2, y=y_2),\n    color = col_line2\n    )+\n  geom_abline(\n    slope=1, \n    intercept = 0, \n    color = col_line0,\n    linewidth = 1\n    )+\n  geom_pointrange(\n    mapping = aes(\n      ymin = low,\n      ymax = up,\n      color = T_env\n    ),\n    alpha = 0.5\n  )+\n  labs(\n    x = \"Observed reproduction (#)\",\n    y = \"Predicted reproduction (#)\"\n  )+\n  scale_color_manual(\n    name = \"Temperature (°C)\",\n    values = col_T_env\n    )+\n  scale_x_log10(\n   labels = scales::label_number()\n    )+\n  scale_y_log10(\n   labels = scales::label_number()\n    )+\n  theme_minimal()\n\np_predobs_Temp <- p_W_Temp + p_R_Temp +plot_layout(guides=\"collect\") +\n  plot_annotation(tag_levels = \"A\")\n\np_predobs_Temp\n```\n\n::: {.cell-output-display}\n![Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line.](E_Model_comparison_files/figure-html/fig-predobs_D_Temp-1.png){#fig-predobs_D_Temp width=768}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf_Quality_fit <- function(df, group){\n  df_res <- df |> \n    group_by(across(all_of(group))) |> \n    summarise(\n        Fold_mean = mean(Fold, na.rm = TRUE),\n        Bias = mean(Residuals, na.rm = TRUE),\n        Mean_relative_error = mean(Relative_error, na.rm = TRUE),\n        Mean_LogPredObs = mean(LogPredObs, na.rm = TRUE),\n        .groups = \"drop\"\n      ) |> \n    ungroup() |> \n    mutate(Mean_PredObs = exp(Mean_LogPredObs))\n}\n\nf_Experiment_Conditions <- function(df){\n  df_res <- df |> \n  mutate(\n    Status = case_when(\n      ID_experiment == \"Bart2019_XP1_1\" ~ \"J\",\n      ID_experiment == \"Bart2019_XP1_2\" & Time <= 84 ~ \"J\",\n      ID_experiment == \"Bart2019_XP1_2\" & Time > 84 ~ \"A\",\n      ID_experiment == \"Bart2019_XP3\" ~ \"J\",\n      ID_experiment == \"Bart2019_XP4_1\" ~ \"J\",\n      ID_experiment == \"Bart2019_XP4_2\" & Time <= 112 ~ \"J\",\n      ID_experiment == \"Bart2019_XP4_2\" & Time > 112 ~ \"A\",\n      ID_experiment == \"Bart2019_XP5\" ~ \"J\",\n      ID_experiment == \"Bart2020\" ~ \"J\",\n      ID_experiment == \"Gollot2026_dens_D1\" ~ \"J\",\n      ID_experiment == \"Gollot2026_dens_D2\" & Time <= 70 ~ \"J\",\n      ID_experiment == \"Gollot2026_dens_D2\" & Time > 70 ~ \"A\",\n      ID_experiment == \"Gollot2026_dens_D2b\" & Time <= 70 ~ \"J\",\n      ID_experiment == \"Gollot2026_dens_D2b\" & Time > 70 ~ \"A\",\n      ID_experiment == \"Gollot2026_dens_D5\" & Time <= 70 ~ \"J\",\n      ID_experiment == \"Gollot2026_dens_D5\" & Time > 70 ~ \"A\",\n      ID_experiment == \"Gollot2026_dens_D7\" ~ \"J\"\n    )\n  ) |> \n  mutate(Status = factor(Status, levels = c(\"J\", \"A\")))\n  \n  return(df_res)\n}\n\ndf_predobs_Weight_D_CWKe_Fit <- f_Experiment_Conditions(df_predobs_Weight_D_CWKe_plot)\n\ndf_predobs_Weight_D_CWKe_Fit <- df_predobs_Weight_D_CWKe_Fit |> \n  mutate(\n    Fold = ifelse(predict.endpoint > Weight_obs, predict.endpoint/Weight_obs, Weight_obs/predict.endpoint),\n    Residuals = predict.endpoint-Weight_obs,\n    Relative_error = (predict.endpoint-Weight_obs)/Weight_obs,\n    LogPredObs = log(predict.endpoint/Weight_obs)\n    )\n\ndf_fold_D_Weight_Dens <- f_Quality_fit(df_predobs_Weight_D_CWKe_Fit, \"Density_env\")\ndf_fold_D_Weight_Food <- f_Quality_fit(df_predobs_Weight_D_CWKe_Fit, \"Food_env\")\ndf_fold_D_Weight_Temp <- f_Quality_fit(df_predobs_Weight_D_CWKe_Fit, \"T_env\")\n\ndf_fold_D_Weight_Dens_Status <- f_Quality_fit(df_predobs_Weight_D_CWKe_Fit, c(\"Density_env\", \"Status\"))\ndf_fold_D_Weight_Food_Status <- f_Quality_fit(df_predobs_Weight_D_CWKe_Fit, c(\"Food_env\", \"Status\"))\ndf_fold_D_Weight_Temp_Status <- f_Quality_fit(df_predobs_Weight_D_CWKe_Fit, c(\"T_env\", \"Status\"))\n\n\ndf_predobs_Reproduction_D_CWKe_Fit <- f_Experiment_Conditions(df_predobs_Reproduction_D_CWKe_plot)\n\ndf_predobs_Reproduction_D_CWKe_Fit <- df_predobs_Reproduction_D_CWKe_Fit |> \n  mutate(\n    Fold = ifelse(predict.endpoint > Reproduction_obs, predict.endpoint/Reproduction_obs, Reproduction_obs/predict.endpoint),\n    Residuals = predict.endpoint-Reproduction_obs,\n    Relative_error = (predict.endpoint-Reproduction_obs)/Reproduction_obs,\n    LogPredObs = log(predict.endpoint/Reproduction_obs)\n    )\n\ndf_fold_D_Reproduction_Dens <- f_Quality_fit(df_predobs_Reproduction_D_CWKe_Fit, \"Density_env\")\ndf_fold_D_Reproduction_Food <- f_Quality_fit(df_predobs_Reproduction_D_CWKe_Fit, \"Food_env\")\ndf_fold_D_Reproduction_Temp <- f_Quality_fit(df_predobs_Reproduction_D_CWKe_Fit, \"T_env\")\n\ndf_fold_D_Reproduction_Dens_Status <- f_Quality_fit(df_predobs_Reproduction_D_CWKe_Fit, c(\"Density_env\", \"Status\"))\ndf_fold_D_Reproduction_Food_Status <- f_Quality_fit(df_predobs_Reproduction_D_CWKe_Fit, c(\"Food_env\", \"Status\"))\ndf_fold_D_Reproduction_Temp_Status <- f_Quality_fit(df_predobs_Reproduction_D_CWKe_Fit, c(\"T_env\", \"Status\"))\n```\n:::\n\n::: {.cell tbl-cap='Quality of fit for weight and its bias according to experimental temperature.'}\n\n```{.r .cell-code}\ndf_fold_D_Weight_Temp |> datatable(\n  options = list(\n    dom = 't',\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n      )\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-1b8f36ddff70699a5c2d\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1b8f36ddff70699a5c2d\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\"],[\"15°C\",\"18°C\"],[1.254500881399286,1.227441701579369],[-0.02336825072199352,-0.01930105],[0.07256375027807258,0.1080983143452151],[0.0370596384644849,0.07832660195878001],[1.037754909101969,1.081475813115414]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>T_env<\\/th>\\n      <th>Fold_mean<\\/th>\\n      <th>Bias<\\/th>\\n      <th>Mean_relative_error<\\/th>\\n      <th>Mean_LogPredObs<\\/th>\\n      <th>Mean_PredObs<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"T_env\",\"targets\":1},{\"name\":\"Fold_mean\",\"targets\":2},{\"name\":\"Bias\",\"targets\":3},{\"name\":\"Mean_relative_error\",\"targets\":4},{\"name\":\"Mean_LogPredObs\",\"targets\":5},{\"name\":\"Mean_PredObs\",\"targets\":6}],\"order\":[],\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell tbl-cap='Quality of fit for weight and its bias according to the number of individuals in the cosm and their observed developmental status.'}\n\n```{.r .cell-code}\ndf_fold_D_Weight_Dens_Status |> datatable(\n  options = list(\n    dom = 't',\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n      )\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-c9c30d45e0aa675613c7\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c9c30d45e0aa675613c7\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],[\"1\",\"2\",\"2\",\"5\",\"5\",\"7\",\"Grouped\\nafter puberty\"],[\"J\",\"J\",\"A\",\"J\",\"A\",\"J\",\"A\"],[1.270361223144324,1.304793570472867,1.164122993686313,1.181991716144163,1.048308273347274,1.389441852006791,1.204082571922154],[-0.02575984947533669,0.03172437,-0.1311238888888889,0.02602446000000002,0.0108355,0.07029899333333334,-0.02983940909090897],[0.08506776772500037,0.2840593541872418,-0.1187654662316939,0.1819917161441632,0.01672760663644276,0.3894418520067914,-0.003054177623508869],[0.04525045531769904,0.236090914904112,-0.1336478704112523,0.1633400586196958,0.01547552538079106,0.3277526018287038,-0.02435888870037886],[1.046289875958979,1.266289429515831,0.8748980878719763,1.177437019224391,1.015595891431421,1.387845579355398,0.9759353947141514]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Density_env<\\/th>\\n      <th>Status<\\/th>\\n      <th>Fold_mean<\\/th>\\n      <th>Bias<\\/th>\\n      <th>Mean_relative_error<\\/th>\\n      <th>Mean_LogPredObs<\\/th>\\n      <th>Mean_PredObs<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Density_env\",\"targets\":1},{\"name\":\"Status\",\"targets\":2},{\"name\":\"Fold_mean\",\"targets\":3},{\"name\":\"Bias\",\"targets\":4},{\"name\":\"Mean_relative_error\",\"targets\":5},{\"name\":\"Mean_LogPredObs\",\"targets\":6},{\"name\":\"Mean_PredObs\",\"targets\":7}],\"order\":[],\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell tbl-cap='Quality of fit for weight and its bias according to percentage of organic matter (OM) from horse dung given every 14 days per individual and the observed developmental status of earthworms.'}\n\n```{.r .cell-code}\ndf_fold_D_Weight_Food_Status |> datatable(\n  options = list(\n    dom = 't',\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n      )\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-bcaa8a34126b6a4038ec\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-bcaa8a34126b6a4038ec\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\"],[\"0.19 %\",\"0.22 %\",\"0.22 %\",\"0.27 %\",\"0.27 %\",\"0.34 %\",\"0.67 %\",\"0.67 %\",\"1.3 %\",\"1.3 %\",\"0 or 0.67 %\"],[\"J\",\"J\",\"A\",\"J\",\"A\",\"J\",\"J\",\"A\",\"J\",\"A\",\"J\"],[1.389441852006791,1.310665424550249,1.194711886942285,1.181991716144163,1.048308273347274,1.21527950438613,1.264530388972888,1.223075990051956,1.289943746192942,1.095790583663948,1.269996102312926],[0.07029899333333334,-0.01157851041666665,0.1249158181818182,0.02602446000000002,0.0108355,-0.05241639999999999,-0.03068264370893655,-0.1930597333333331,-0.01407258666666672,-0.06295199999999998,0.005882293749999996],[0.3894418520067914,0.1939490706087349,0.1636153028953339,0.1819917161441632,0.01672760663644276,-0.1465775699017776,0.04962323928761941,-0.1755046685460379,0.1244049715993205,-0.06065588149210887,0.2171903836624856],[0.3277526018287038,0.1412133817122603,0.1409397711856289,0.1633400586196958,0.01547552538079106,-0.1681020858941902,0.0139988006424019,-0.1971134522132678,0.08136039865531747,-0.06647241699050137,0.1744939498685452],[1.387845579355398,1.151670367162727,1.151355301131719,1.177437019224391,1.015595891431421,0.8452675403873281,1.01409724267253,0.8210974727025324,1.084761772811154,0.9356887246113663,1.190643538813298]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Food_env<\\/th>\\n      <th>Status<\\/th>\\n      <th>Fold_mean<\\/th>\\n      <th>Bias<\\/th>\\n      <th>Mean_relative_error<\\/th>\\n      <th>Mean_LogPredObs<\\/th>\\n      <th>Mean_PredObs<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Food_env\",\"targets\":1},{\"name\":\"Status\",\"targets\":2},{\"name\":\"Fold_mean\",\"targets\":3},{\"name\":\"Bias\",\"targets\":4},{\"name\":\"Mean_relative_error\",\"targets\":5},{\"name\":\"Mean_LogPredObs\",\"targets\":6},{\"name\":\"Mean_PredObs\",\"targets\":7}],\"order\":[],\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell tbl-cap='Quality of fit for reproduction and its bias according to experimental temperature.'}\n\n```{.r .cell-code}\ndf_fold_D_Reproduction_Temp |> datatable(\n  options = list(\n    dom = 't',\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n      )\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-16b9b5fdd255d53defcc\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-16b9b5fdd255d53defcc\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\"],[\"15°C\",\"18°C\"],[null,null],[-0.4729676351351347,0.9849823684210525],[null,null],[null,null],[null,null]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>T_env<\\/th>\\n      <th>Fold_mean<\\/th>\\n      <th>Bias<\\/th>\\n      <th>Mean_relative_error<\\/th>\\n      <th>Mean_LogPredObs<\\/th>\\n      <th>Mean_PredObs<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"T_env\",\"targets\":1},{\"name\":\"Fold_mean\",\"targets\":2},{\"name\":\"Bias\",\"targets\":3},{\"name\":\"Mean_relative_error\",\"targets\":4},{\"name\":\"Mean_LogPredObs\",\"targets\":5},{\"name\":\"Mean_PredObs\",\"targets\":6}],\"order\":[],\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell tbl-cap='Quality of fit for reproduction and its bias according to the number of individuals in the cosm and their observed developmental status.'}\n\n```{.r .cell-code}\ndf_fold_D_Reproduction_Dens_Status |> datatable(\n  options = list(\n    dom = 't',\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n      )\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-41bebee9b57ffd7fb40c\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-41bebee9b57ffd7fb40c\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],[\"1\",\"2\",\"2\",\"5\",\"5\",\"7\",\"Grouped\\nafter puberty\"],[\"J\",\"J\",\"A\",\"J\",\"A\",\"J\",\"A\"],[null,null,111114.3873337959,null,1.55331643471978,null,null],[0.0006456385964912281,1e-06,1.566868000000001,1e-06,5.831873250000001,1e-06,-1.5925637],[null,null,0.4008329157712527,null,0.4728143740277874,null,null],[null,null,-1.661665318412239,null,0.3488531658481037,null,null],[null,null,0.1898226016656077,null,1.417441046307136,null,null]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Density_env<\\/th>\\n      <th>Status<\\/th>\\n      <th>Fold_mean<\\/th>\\n      <th>Bias<\\/th>\\n      <th>Mean_relative_error<\\/th>\\n      <th>Mean_LogPredObs<\\/th>\\n      <th>Mean_PredObs<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Density_env\",\"targets\":1},{\"name\":\"Status\",\"targets\":2},{\"name\":\"Fold_mean\",\"targets\":3},{\"name\":\"Bias\",\"targets\":4},{\"name\":\"Mean_relative_error\",\"targets\":5},{\"name\":\"Mean_LogPredObs\",\"targets\":6},{\"name\":\"Mean_PredObs\",\"targets\":7}],\"order\":[],\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n::: {.cell tbl-cap='Quality of fit for reproduction and its bias according to percentage of organic matter (OM) from horse dung given every 14 days per individual and the observed developmental status of earthworms.'}\n\n```{.r .cell-code}\ndf_fold_D_Reproduction_Food_Status |> datatable(\n  options = list(\n    dom = 't',\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n      )\n    )\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-5009d8ca80db8e0432dc\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5009d8ca80db8e0432dc\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\"],[\"0.19 %\",\"0.22 %\",\"0.22 %\",\"0.27 %\",\"0.27 %\",\"0.34 %\",\"0.67 %\",\"0.67 %\",\"1.3 %\",\"1.3 %\",\"0 or 0.67 %\"],[\"J\",\"J\",\"A\",\"J\",\"A\",\"J\",\"J\",\"A\",\"J\",\"A\",\"J\"],[null,null,null,null,1.55331643471978,null,null,null,null,4.118269241245638,null],[1e-06,1e-06,3.553131,1e-06,5.831873250000001,1e-06,1e-06,-7.012207426666667,1e-06,9.032816200000001,0.002297524999999999],[null,null,null,null,0.4728143740277874,null,null,null,null,1.251247736396936,null],[null,null,null,null,0.3488531658481037,null,null,null,null,0.3276673660673371,null],[null,null,null,null,1.417441046307136,null,null,null,null,1.387727290322082,null]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Food_env<\\/th>\\n      <th>Status<\\/th>\\n      <th>Fold_mean<\\/th>\\n      <th>Bias<\\/th>\\n      <th>Mean_relative_error<\\/th>\\n      <th>Mean_LogPredObs<\\/th>\\n      <th>Mean_PredObs<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Food_env\",\"targets\":1},{\"name\":\"Status\",\"targets\":2},{\"name\":\"Fold_mean\",\"targets\":3},{\"name\":\"Bias\",\"targets\":4},{\"name\":\"Mean_relative_error\",\"targets\":5},{\"name\":\"Mean_LogPredObs\",\"targets\":6},{\"name\":\"Mean_PredObs\",\"targets\":7}],\"order\":[],\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n\nThe predicted-observed analysis highlighted condition-specific patterns in model fit and prediction bias. These comparisons remain descriptive because the experimental factors were not orthogonal, particularly density and per-capita food availability.\n\nFor body mass, fit quality was similar between temperatures, with mean fold values of 1.21 at 15 °C and 1.28 at 18 °C. The exponentiated mean log predicted-to-observed ratios were also close to 1 at both temperatures (1.11 and 0.92, respectively), providing no clear evidence of a marked temperature-specific bias. The higher reproduction residual observed at 18 °C was mainly driven by individuals at density 2 with increased food supply (Gollot2026_D2b) and therefore reflected a condition-specific overestimation rather than a general temperature effect.\n\nFor juveniles, fit quality decreased as density increased and per-capita food availability declined, with mean fold values ranging from 1.24 at density 1 to 1.55 at density 7. Negative mean log predicted-to-observed ratios at densities 5 and 7, and under the lowest food input, indicated a tendency to underestimate juvenile body mass under the most limiting conditions. Adult body mass was also underestimated at densities 2 and 5, whereas individuals grouped after puberty were accurately reproduced, with a mean fold of 1.12 and a mean log predicted-to-observed ratio close to zero.\n\nReproduction showed greater condition-specific variation than body mass, with both over- and underestimation across adult density and feeding treatments. The strongest overestimation occurred for individuals at density 2 with increased food supply (Gollot2026_D2b), which also corresponded to the highest per-capita food input. Overall, model deviations were associated with combinations of density, food availability, developmental stage, and experiment-specific conditions rather than with a single environmental factor.\n\n## Sensitivity analysis - CWKe\n\n### With temperature parameters\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath_fig <- here::here(\"fig/AS\")\npath_AS <- here::here(\"mod/X_AS\")\n\nseed       <- 361224\nSobol_type <- \"Jansen\"\nNb_sim     <- 30000 # (p + 2) * Nb_sim simulations 30000\nCV         <- 0.1 # 1000\nprocessors <- 2\nNboot      <- 1000  # nb replicat\n\nl_params_median <- c(\n  # Environment\n  muOM = 13000, rOM_ClxHorse = 0.0294325,\n  # Energy assimilation\n  Fm = 3.87576, kapX = 0.258, K = 0.0546564, pAm = 259.953, v = 0.230918,\n  kapJ  = 0.983041, kapA = 0.707631, \n  tau = 11.9528,\n  # Maintenance and growth\n  r_pAm_pM = 0.70081, Eg = 4183, dv = 1.2135, de = 1.130890e-09,\n  # Maturity\n  kJ = 0.002793, Ehb = 0.5, Ehp = 73.1002,\n  # Reproduction\n  E_coc = 57.8342, kapR = 0.475,\n  # Metabolic response to T\n  TAH = 28750, TH = 293.2, TA = 7976, Tref = 293.15\n)\n\n# With temperature parameters\n\nSobol_design_T <- f_AS_Sobol_design(Sobol_type = Sobol_type, seed = seed, Nb_sim = Nb_sim, CV = CV, Processors = Processors, Nboot = Nboot, l_params_median = l_params_median, Temperature_bol = TRUE)\nl_Sobol_param_T <- Sobol_design_T$Sobol_param\nSobol_info_T <- Sobol_design_T$Sobol\n\nfile_rds_AS_T <- file.path(path_AS, paste0(\"df_Sobol_param_T.rds\"))\nfile_txt_AS_T <- here::here(paste0(\"mod/X_AS/Param_sobol_\", Sobol_type, \"_T.txt\"))\n\nif (file.exists(file_rds_AS_T)) {\n  df_Sobol_param_T <- readRDS(file_rds_AS_T)\n} else {\n  \n  library(data.table)\n\n  df_Sobol_param_T <- rbindlist(\n    l_Sobol_param_T,\n    use.names = TRUE,\n    fill = FALSE\n  )\n  \n  df_Sobol_param_T <- cbind(id = seq_len(nrow(df_Sobol_param_T)), df_Sobol_param_T)\n  \n  saveRDS(df_Sobol_param_T, file_rds_AS_T)\n  \n  fwrite(\n    df_Sobol_param_T,\n    file = file_txt_AS_T,\n    sep = \"\\t\",\n    quote = FALSE\n  )\n\n}\n\n# In the AS folder in the terminal :\n# makemcsim DEBcali.model\n# ./mcsim.DEBcali DEB_AS_T.in\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nl_sim_fail_T <- c()\n\nNames_AS_outputs <- c(\"Weight_Juv\", \"Weight_Adult\", \"Energy_Juv\", \"Energy_Adult\", \"Maturity_Juv\", \"Maturity_Adult\", \"Reproduction\", \"Organic_matter\")\n\npath_AS <- here::here(\"mod/X_AS\")\nfile_rds_AS_res_T <- file.path(path_AS, paste0(\"df_Sobol_results_T.rds\"))\n\nif (file.exists(file_rds_AS_res_T)) {\n  df_Sobol_results_T <- readRDS(file_rds_AS_res_T)\n} else {\n  # Long to generate\n  df_AS_sim_T <- read_tsv(file.path(path_AS, paste0(\"Sobol_\", Sobol_type,\"_T.out\"))) |>\n  dplyr::select(-(1:(length(l_params_median)+1))) |>\n  setNames(Names_AS_outputs)\n  df_Sobol_results_T <- f_AS_Sobol_index(df_AS_sim_T, Sobol_info_T, l_sim_fail_T)\n  saveRDS(df_Sobol_results_T, file_rds_AS_res_T)\n}\n\n\ndf_Sobol_results_T <- df_Sobol_results_T |> \n  mutate(\n    Variable = factor(Variable, Names_AS_outputs),\n    Variable_title = case_when(\n      Variable == \"Energy_Adult\" ~ \"Energy - Adult stage\",\n      Variable == \"Energy_Juv\" ~ \"Energy - Juvenile stage\",\n      Variable == \"Weight_Adult\" ~ \"Weight - Adult stage\",\n      Variable == \"Weight_Juv\" ~ \"Weight - Juvenile stage\",\n      Variable == \"Maturity_Adult\" ~ \"Maturity - Adult stage\",\n      Variable == \"Maturity_Juv\" ~ \"Maturity - Juvenile stage\",\n      Variable == \"Reproduction\" ~ \"Reproduction\",\n      Variable == \"Organic_matter\" ~ \"Total organic matter in the cosm\"\n    )\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np_TI_tot <- ggplot(\n  df_Sobol_results_T,\n  aes(\n    x = reorder(Parameter, TI),\n    y = TI\n  )\n) +\n  geom_col(\n    aes(\n      fill = Variable_title\n    ),\n    alpha = 0.7\n  ) +\n  coord_flip() +\n  scale_fill_manual(\n    values = rev(c(Nord_aurora, rev(Nord_frost))),\n    name = \"Endpoints\"\n  )+\n  labs(\n    title = \"Sobol Sensitivity Analysis - Total Index\",\n    x = \"Parameter\",\n    y = \"Total Index\",\n    caption = paste0(\"Nsim = \", Nb_sim, \" | Nboot = \", Nboot)\n  ) +\n  #scale_y_log10()+\n  theme_minimal() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(face = \"bold\"),\n    legend.title = element_text(face = \"bold\")\n  )\n\np_TI_tot\n```\n\n::: {.cell-output-display}\n![Sobol Sensitivity Analysis - Total Index.](E_Model_comparison_files/figure-html/fig-TItotT-1.png){#fig-TItotT width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n{\n  Color_AS <- rev(c(Nord_aurora, rev(Nord_frost)))\n  size_title_facet <- 10\n  size_axis_text_y <- 7\n  for (i in 1:length(unique(df_Sobol_results_T$Variable))){\n\n    Variable_i <- Names_AS_outputs[i]\n    Variable_title_i <- (subset(df_Sobol_results_T, Variable == Variable_i))$Variable_title[1]\n\n    if (i == 1){\n      p1 <- ggplot(\n        subset(df_Sobol_results_T, Variable == Variable_i),\n        aes(\n          x = reorder(Parameter, TI),\n          y = TI\n        )\n      ) +\n        geom_col(\n          fill = Color_AS[i],\n          alpha = 0.7\n        ) +\n        coord_flip() +\n        labs(\n          title = as.character(Variable_title_i),\n          x = \"Parameter\",\n          y = \"Total Index\"#,\n          #caption = \"Error bars = CI 95% | n = 1000\"\n        ) +\n        theme_minimal() +\n        theme(\n          legend.position = \"right\",\n          axis.text.y = element_text(size = size_axis_text_y),\n          plot.title = element_text(face = \"bold\", size = size_title_facet),\n          legend.title = element_text(face = \"bold\")\n        )\n    } else {\n      p <- ggplot(\n        subset(df_Sobol_results_T, Variable == Variable_i),\n        aes(\n          x = reorder(Parameter, TI),\n          y = TI\n        )\n      ) +\n        geom_col(\n          fill = Color_AS[i],\n          alpha = 0.7\n        ) +\n        coord_flip() +\n        labs(\n          title = as.character(Variable_title_i),\n          x = \"Parameter\",\n          y = \"Total Index\"#,\n          #caption = \"Error bars = CI 95% | n = 1000\"\n        ) +\n        theme_minimal() +\n        theme(\n          legend.position = \"right\",\n          axis.text.y = element_text(size = size_axis_text_y),\n          plot.title = element_text(face = \"bold\", size = size_title_facet),\n          legend.title = element_text(face = \"bold\")\n        )\n      p1 <- p1 + p\n    }\n  }\n\n  p_TI_pervar <- p1 + plot_layout(ncol = 3) +\n    plot_annotation(\n      title = \"Sobol Sensitivity Analysis - Total Index\",\n      caption = paste0(\"Nsim = \", Nb_sim, \" | Nboot = \", Nboot),\n      theme = theme(\n        plot.title = element_text(size = 16, face = \"bold\"),\n      )\n    )\n  p_TI_pervar\n}\n```\n\n::: {.cell-output-display}\n![Sobol Sensitivity Analysis - Total Index per variable.](E_Model_comparison_files/figure-html/fig-TItotpervarT-1.png){#fig-TItotpervarT width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_Sobol_results_long_T <- df_Sobol_results_T %>%\n  pivot_longer(\n    cols = c(FOI, TI),\n    names_to = \"Index_Type\",\n    values_to = \"Index_Value\"\n  ) %>%\n  mutate(\n    # Ajouter les IC correspondants\n    IC_inf = ifelse(Index_Type == \"FOI\", FOI.borninf, TI.borninf),\n    IC_sup = ifelse(Index_Type == \"FOI\", FOI.bornsup, TI.bornsup)\n  )\n\n\n# Graphique comparatif\np2 <- ggplot(\n  df_Sobol_results_long_T, \n  aes(\n    x = reorder(Parameter, Index_Value), \n    y = Index_Value, \n    fill = Index_Type)\n) +\n  geom_col(\n    position = \"dodge\", \n    alpha = 0.8\n  ) +\n  geom_errorbar(\n    aes(\n      ymin = IC_inf, \n      ymax = IC_sup\n    ),\n    position = position_dodge(width = 0.8),\n    width = 0.25,\n    linewidth = 0.4,\n    color = Nord_polar[4]\n  ) +\n  coord_flip() +\n  facet_wrap(\n    ~Variable_title, \n    ncol = 4,\n    scales = \"free\"\n  ) +\n  scale_fill_manual(\n    name = \"Index type\",\n    values = c(\"FOI\" = \"#5E81AC\", \"TI\" = \"#BF616A\"),\n    labels = c(\"FOI\" = \"First order\", \"TI\" = \"Total\")\n  ) +\n  labs(\n    title = \"Comparison of sensitivity indexes\",\n    x = \"Parameter\",\n    y = \"Index value\",\n    caption = paste0(\"Error bars = CI 95% | Nsim = \", Nb_sim, \" | Nboot = \", Nboot)\n  ) +\n  theme_minimal()\n\np2\n```\n\n::: {.cell-output-display}\n![Sobol Sensitivity Analysis - Comparison TI & FOI.](E_Model_comparison_files/figure-html/fig-TIFOIT-1.png){#fig-TIFOIT width=1344}\n:::\n:::\n\n\n\n\n\n\n\n### Without temperature parameters\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath_fig <- here::here(\"fig/AS\")\npath_AS <- here::here(\"mod/X_AS\")\n\nseed       <- 361224\nSobol_type <- \"Jansen\"\nNb_sim     <- 30000 # (p + 2) * Nb_sim simulations 30000\nCV         <- 0.1 # 1000\nprocessors <- 2\nNboot      <- 1000  # nb replicat\n\nl_params_median <- c(\n  # Environment\n  muOM = 13000, rOM_ClxHorse = 0.0294325,\n  # Energy assimilation\n  Fm = 3.87576, kapX = 0.258, K = 0.0546564, pAm = 259.953, v = 0.230918,\n  kapJ  = 0.983041, kapA = 0.707631, \n  tau = 11.9528,\n  # Maintenance and growth\n  r_pAm_pM = 0.70081, Eg = 4183, dv = 1.2135, de = 1.130890e-09,\n  # Maturity\n  kJ = 0.002793, Ehb = 0.5, Ehp = 73.1002,\n  # Reproduction\n  E_coc = 57.8342, kapR = 0.475,\n  # Metabolic response to T\n  TAH = 28750, TH = 293.2, TA = 7976, Tref = 293.15\n)\n\n# Withou temperature parameters\n\nSobol_design_noT <- f_AS_Sobol_design(Sobol_type, seed, Nb_sim, CV, Processors, Nboot, l_params_median, Temperature_bol = FALSE)\nl_Sobol_param_noT <- Sobol_design_noT$Sobol_param\nSobol_info_noT <- Sobol_design_noT$Sobol\n\nfile_rds_AS_noT <- file.path(path_AS, paste0(\"df_Sobol_param_noT.rds\"))\nfile_txt_AS_noT <- here::here(paste0(\"mod/X_AS/Param_sobol_\", Sobol_type, \"_noT.txt\"))\n\nif (file.exists(file_rds_AS_noT)) {\n  df_Sobol_param_noT <- readRDS(file_rds_AS_noT)\n} else {\n  \n  library(data.table)\n\n  df_Sobol_param_noT <- rbindlist(\n    l_Sobol_param_noT,\n    use.names = TRUE,\n    fill = FALSE\n  )\n  \n  df_Sobol_param_noT <- cbind(id = seq_len(nrow(df_Sobol_param_noT)), df_Sobol_param_noT)\n  \n  saveRDS(df_Sobol_param_noT, file_rds_AS_noT)\n  \n  fwrite(\n    df_Sobol_param_noT,\n    file = file_txt_AS_noT,\n    sep = \"\\t\",\n    quote = FALSE\n  )\n\n}\n\n# In the AS folder in the terminal :\n# makemcsim DEBcali.model\n# ./mcsim.DEBcali DEB_AS.in\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nl_sim_fail_noT <- c()\n\nNames_AS_outputs <- c(\"Weight_Juv\", \"Weight_Adult\", \"Energy_Juv\", \"Energy_Adult\", \"Maturity_Juv\", \"Maturity_Adult\", \"Reproduction\", \"Organic_matter\")\n\npath_AS <- here::here(\"mod/X_AS\")\nfile_rds_AS_res_noT <- file.path(path_AS, paste0(\"df_Sobol_results_noT.rds\"))\n\nif (file.exists(file_rds_AS_res_noT)) {\n  df_Sobol_results_noT <- readRDS(file_rds_AS_res_noT)\n} else {\n  # Long to generate\n  df_AS_sim_noT <- read_tsv(file.path(path_AS, paste0(\"Sobol_\", Sobol_type,\"_noT.out\"))) |>\n  dplyr::select(-(1:(length(l_params_median)+1-4))) |>\n  setNames(Names_AS_outputs)\n  df_Sobol_results_noT <- f_AS_Sobol_index(df_AS_sim_noT, Sobol_info_noT, l_sim_fail_noT)\n  saveRDS(df_Sobol_results_noT, file_rds_AS_res_noT)\n}\n\n\ndf_Sobol_results_noT <- df_Sobol_results_noT |> \n  mutate(\n    Variable = factor(Variable, Names_AS_outputs),\n    Variable_title = case_when(\n      Variable == \"Energy_Adult\" ~ \"Energy - Adult stage\",\n      Variable == \"Energy_Juv\" ~ \"Energy - Juvenile stage\",\n      Variable == \"Weight_Adult\" ~ \"Weight - Adult stage\",\n      Variable == \"Weight_Juv\" ~ \"Weight - Juvenile stage\",\n      Variable == \"Maturity_Adult\" ~ \"Maturity - Adult stage\",\n      Variable == \"Maturity_Juv\" ~ \"Maturity - Juvenile stage\",\n      Variable == \"Reproduction\" ~ \"Reproduction\",\n      Variable == \"Organic_matter\" ~ \"Total organic matter in the cosm\"\n    )\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np_TI_tot <- ggplot(\n  df_Sobol_results_noT,\n  aes(\n    x = reorder(Parameter, TI),\n    y = TI\n  )\n) +\n  geom_col(\n    aes(\n      fill = Variable_title\n    ),\n    alpha = 0.7\n  ) +\n  coord_flip() +\n  scale_fill_manual(\n    values = rev(c(Nord_aurora, rev(Nord_frost))),\n    name = \"Endpoints\"\n  )+\n  labs(\n    title = \"Sobol Sensitivity Analysis - Total Index\",\n    x = \"Parameter\",\n    y = \"Total Index\",\n    caption = paste0(\"Nsim = \", Nb_sim, \" | Nboot = \", 1000)\n  ) +\n  #scale_y_log10()+\n  theme_minimal() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(face = \"bold\"),\n    legend.title = element_text(face = \"bold\")\n  )\n\np_TI_tot\n```\n\n::: {.cell-output-display}\n![Sobol Sensitivity Analysis - Total Index.](E_Model_comparison_files/figure-html/fig-TItotnoT-1.png){#fig-TItotnoT width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n{\n  Color_AS <- rev(c(Nord_aurora, rev(Nord_frost)))\n  size_title_facet <- 10\n  size_axis_text_y <- 7\n  for (i in 1:length(unique(df_Sobol_results_noT$Variable))){\n\n    Variable_i <- Names_AS_outputs[i]\n    Variable_title_i <- (subset(df_Sobol_results_noT, Variable == Variable_i))$Variable_title[1]\n\n    if (i == 1){\n      p1 <- ggplot(\n        subset(df_Sobol_results_noT, Variable == Variable_i),\n        aes(\n          x = reorder(Parameter, TI),\n          y = TI\n        )\n      ) +\n        geom_col(\n          fill = Color_AS[i],\n          alpha = 0.7\n        ) +\n        coord_flip() +\n        labs(\n          title = as.character(Variable_title_i),\n          x = \"Parameter\",\n          y = \"Total Index\"#,\n          #caption = \"Error bars = CI 95% | n = 1000\"\n        ) +\n        theme_minimal() +\n        theme(\n          legend.position = \"right\",\n          axis.text.y = element_text(size = size_axis_text_y),\n          plot.title = element_text(face = \"bold\", size = size_title_facet),\n          legend.title = element_text(face = \"bold\")\n        )\n    } else {\n      p <- ggplot(\n        subset(df_Sobol_results_noT, Variable == Variable_i),\n        aes(\n          x = reorder(Parameter, TI),\n          y = TI\n        )\n      ) +\n        geom_col(\n          fill = Color_AS[i],\n          alpha = 0.7\n        ) +\n        coord_flip() +\n        labs(\n          title = as.character(Variable_title_i),\n          x = \"Parameter\",\n          y = \"Total Index\"#,\n          #caption = \"Error bars = CI 95% | n = 1000\"\n        ) +\n        theme_minimal() +\n        theme(\n          legend.position = \"right\",\n          axis.text.y = element_text(size = size_axis_text_y),\n          plot.title = element_text(face = \"bold\", size = size_title_facet),\n          legend.title = element_text(face = \"bold\")\n        )\n      p1 <- p1 + p\n    }\n  }\n\n  p_TI_pervar <- p1 + plot_layout(ncol = 3) +\n    plot_annotation(\n      title = \"Sobol Sensitivity Analysis - Total Index\",\n      caption = paste0(\"Nsim = \", Nb_sim, \" | Nboot = \", Nboot),\n      theme = theme(\n        plot.title = element_text(size = 16, face = \"bold\"),\n      )\n    )\n  p_TI_pervar\n}\n```\n\n::: {.cell-output-display}\n![Sobol Sensitivity Analysis - Total Index per variable.](E_Model_comparison_files/figure-html/fig-TItotpervarnoT-1.png){#fig-TItotpervarnoT width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_Sobol_results_long <- df_Sobol_results_noT %>%\n  pivot_longer(\n    cols = c(FOI, TI),\n    names_to = \"Index_Type\",\n    values_to = \"Index_Value\"\n  ) %>%\n  mutate(\n    # Ajouter les IC correspondants\n    IC_inf = ifelse(Index_Type == \"FOI\", FOI.borninf, TI.borninf),\n    IC_sup = ifelse(Index_Type == \"FOI\", FOI.bornsup, TI.bornsup)\n  )\n\n\n# Graphique comparatif\np2 <- ggplot(\n  df_Sobol_results_long, \n  aes(\n    x = reorder(Parameter, Index_Value), \n    y = Index_Value, \n    fill = Index_Type)\n) +\n  geom_col(\n    position = \"dodge\", \n    alpha = 0.8\n  ) +\n  geom_errorbar(\n    aes(\n      ymin = IC_inf, \n      ymax = IC_sup\n    ),\n    position = position_dodge(width = 0.8),\n    width = 0.25,\n    linewidth = 0.4,\n    color = Nord_polar[4]\n  ) +\n  coord_flip() +\n  facet_wrap(\n    ~Variable_title, \n    ncol = 4,\n    scales = \"free\"\n  ) +\n  scale_fill_manual(\n    name = \"Index type\",\n    values = c(\"FOI\" = \"#5E81AC\", \"TI\" = \"#BF616A\"),\n    labels = c(\"FOI\" = \"First order\", \"TI\" = \"Total\")\n  ) +\n  labs(\n    title = \"Comparison of sensitivity indexes\",\n    x = \"Parameter\",\n    y = \"Index value\",\n    caption = paste0(\"Error bars = CI 95% | Nsim = \", Nb_sim, \" | Nboot = \", Nboot)\n  ) +\n  theme_minimal()\n\np2\n```\n\n::: {.cell-output-display}\n![Sobol Sensitivity Analysis - Comparison TI & FOI.](E_Model_comparison_files/figure-html/fig-TIFOI-1.png){#fig-TIFOI width=1344}\n:::\n:::\n\n\n\n\n\n\n\nThe global sensitivity analysis revealed that model outputs were strongly influenced by the parameters governing temperature correction when these were included in the analysis. The reference temperature ($T_{\\mathrm{ref}}$) was the main driver of body mass, reserve energy, reproduction, and organic matter dynamics, while ($T_H$) also contributed substantially. Maturity-related endpoints were primarily controlled by the juvenile allocation fraction ($\\kappa_J$). Differences between first-order and total-order indices indicated substantial interactions between temperature correction, energy allocation, and other physiological processes.\n\nWhen temperature-related parameters were excluded, the sensitivity patterns became more process-specific. Body mass, maturity, and reproduction were mainly governed by ($\\kappa_J$), whereas reserve energy was primarily influenced by the energy conductance ($\\nu$) and the maximum assimilation rate ($\\{\\dot{p}_{Am}\\}$). Organic matter remaining in the cosm was influenced by several ingestion- and assimilation-related parameters, particularly ($[\\dot{F}_m]$), ($\\kappa_X$), ($\\mu_{OM}$), and ($d_V$). These results highlight the central role of temperature correction and energy allocation in model predictions, while also showing that environmental resource dynamics depend on a broader set of interacting processes.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}