{
  "hash": "d88298c9c6a815130d0e9bb84004dc09",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n\n\n# DENS experiment - Impact of density and food quantity\n\n## Protocol\n\n### Earthworms and soil\n\nEarthworms used in the original experiment of this study originated from a laboratory culture established from individuals collected between late 2023 and early 2024 in a permanent grassland located in Versailles (48°48′ N, 2°5′ E). The site has been free of pesticide applications for over three decades. Specimens were identified under a binocular microscope following standard taxonomic keys. The culture was maintained at 18 °C in 1 L vessels, with groups of five individuals per vessel. The rearing substrate consisted of loamy soil sampled from the same meadow and identical to that used in @bart_2019 and @bart_2020, according to the texture classification of the Food and Agriculture Organization (FAO), to reproduce conditions close to those of the native habitat. The soil contained 3.26% organic matter (dry weight basis; see Supplementary Information Table S1.1 for soil characteristics). Soil was collected from the 0-20 cm layer, air-dried, and sieved to \\< 2 mm. Moisture was maintained at 60-70% of the soil’s water-holding capacity (WHC). Earthworms were fed monthly with approximately 6 g (dry weight) of horse dung per group of five individuals, adjusted to 60–80% WHC. The dung was collected long after any veterinary deworming treatment, frozen and thawed twice, and then ground to \\< 1 mm following the procedure of @lowe_2005. As recommended by @bart_2018, ten field-collected individuals were barcoded to verify lineage composition; results indicated two genetic lineages within *A. caliginosa*. To limit potential age-related variation in reproductive performance @hartenstein_1979, individuals used in each reproduction test were less than two months apart in age.\n\nTo obtain age-synchronized cohorts, cocoons were retrieved from the breeding containers and then incubated at 18 °C in Petri dishes lined with moistened filter paper. Newly hatched juveniles were collected daily and transferred to soil stored at 4 °C to slow down their development until the start of the experiment. This procedure ensured that all hatchlings were at a comparable developmental stage at the experiment’s onset and allowed for random assignment of individuals to experimental groups.\n\n### Population density experiment\n\nTo assess the effect of density on earthworm growth and reproduction from the newly hatched juvenile stage to the adult stage, four cosm densities were tested: 1, 2, 5, and 7 individuals per cosm, each in four replicates (hereafter D1, D2, D5, and D7). An additional treatment (D2b) was included to evaluate the effect of food availability independently of density. For each replicate, the corresponding number of earthworms was placed in a cosm consisting of a plastic vessel (11 × 7.7 × 4.5 cm) containing the equivalent of 200 g dry soil humidified at WHC 70%. All cosms were maintained at 18 °C. Each cosm received the equivalent of 3 g of dry horse dung humidified at WHC 70% as food every 14 days, which corresponds to *ad libitum* conditions for a single earthworm (D1). In the D2b condition, this amount was doubled (6 g every 14 days). Soil was renewed every 28 days. Earthworms were weighed every 14 days, and soil moisture was checked and adjusted weekly. Once earthworms reached adulthood, cocoons were collected every 28 days during soil renewal by wet-sieving the soil through a 1-mm mesh, following @bart_2018a.\n\nStatistical analyses were performed to evaluate the effect of population density on juvenile growth and reproductive output. Initial body mass was first compared among density treatments to verify the homogeneity of individuals at the beginning of the experiment. Individual juvenile growth rates were then estimated. Individual juvenile growth rates were then estimated using a linear regression on the weight ($W$) through an allometric relationship with a 1/3 power scaling [@gollot_2025]. For each individual, a linear regression of structural length against time was then fitted, and the slope of this regression was used as an individual estimate of juvenile growth rate. The effect of population density on juvenile growth rate was tested using a one-way analysis of variance (ANOVA), with density treatment as a fixed factor. When a significant density effect was detected, pairwise comparisons between density treatments were performed using Tukey post hoc test. Reproductive output was analysed at the replicate level and compared among density treatments using the same statistical framework. Pairwise comparisons between the remaining density treatments were performed using Tukey post hoc tests.\n\n## Results\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dens_growth_full <- read_excel(here::here(\"data/Data_expe_raw/Data_DENS.xlsx\"), sheet=1)%>%\n  mutate(\n    ID = paste0(Lot, Condition, Nb_rep),\n    Weight = as.numeric(w),\n    L = Weight^(1/3), \n    Lot = as.factor(Lot),\n    Nb_rep = paste0(Lot, Nb_rep)\n    ) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNew names:\n• `` -> `...15`\n```\n\n\n:::\n\n```{.r .cell-code}\ndf_dens_growth <- df_dens_growth_full |> \n  filter(Keep == \"Yes\") |> \n  filter(!(Nb_rep %in% c(\"B1\", \"B2\")))\n\n# Mean at the replicate level\ndf_dens_growth_mean_rep <- df_dens_growth %>%\n  aggregate(Weight~Condition+Nb_rep+Lot+t, FUN=mean)\n\n# Mean at the condition level\ndf_dens_growth_mean_cond <- df_dens_growth %>%\n  aggregate(Weight~Condition+t, FUN=mean)\n\ndf_dens_repro <- read_excel(here::here(\"data/Data_expe_raw/Data_DENS.xlsx\"), sheet=2)%>%\n  mutate(\n    ID = paste0(Lot, Condition, Nb_rep),\n    Lot = as.factor(Lot),\n    Nb_rep = paste0(Lot, Nb_rep)\n    ) |> \n  filter(Keep == \"Yes\") |> \n  filter(!(Nb_rep %in% c(\"B1\", \"B2\")))\n\ndf_dens_repro_mean_cond <- df_dens_repro %>%\n  aggregate(Reproduction~Condition+t, FUN=mean)\n```\n:::\n\n\n\n\n### Initial conditions\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dens_t0 <- subset(df_dens_growth, t==0)\n\np <- ggplot(\n  data = df_dens_t0,\n  aes(\n    x = \"\",\n    y = Weight\n  )\n)+\n  geom_boxplot(\n    alpha=0,\n    color=Nord_polar[4]\n  )+\n  geom_dotplot(\n    aes(\n    color = Lot,\n    fill = Lot\n    ),\n    binaxis='y',\n    stackdir='center',\n    alpha=0.5\n  )+\n  labs(\n    x=\"Conditions\",\n    y = \"Weight (mg)\"\n  )+\n  scale_color_manual(\n    values = c(Nord_frost[4], Nord_polar[4])\n  )+\n  scale_fill_manual(\n    values = c(Nord_frost[4], Nord_polar[4])\n  )+\n  facet_wrap(\n    ~Condition,\n    ncol=5\n    )+\n  theme_minimal()\np\n```\n\n::: {.cell-output-display}\n![Initial weight of earthworms.](B_DENS_experiment_files/figure-html/fig-densinit-1.png){#fig-densinit width=576}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Summary of initial weights : \\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSummary of initial weights : \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(df_dens_t0$Weight)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  4.300   8.725  10.450  10.197  11.675  15.000 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dens_t0 <- df_dens_t0 |> \n  mutate(Condition_f = as.factor(Condition))\n\n# ANOVA\nmod_aov <- aov(Weight ~ Condition_f, data = df_dens_t0)\nsummary(mod_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value Pr(>F)\nCondition_f  4   18.4   4.600   0.905  0.467\nResiduals   65  330.6   5.086               \n```\n\n\n:::\n\n```{.r .cell-code}\nshapiro.test(residuals(mod_aov))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(mod_aov)\nW = 0.97983, p-value = 0.3189\n```\n\n\n:::\n\n```{.r .cell-code}\nleveneTest(Weight ~ Condition_f, data = df_dens_t0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  4  1.0154  0.406\n      65               \n```\n\n\n:::\n\n```{.r .cell-code}\ndunnett_test <- glht(mod_aov, linfct = mcp(Condition_f = \"Dunnett\"))\nsummary(dunnett_test)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Simultaneous Tests for General Linear Hypotheses\n\nMultiple Comparisons of Means: Dunnett Contrasts\n\n\nFit: aov(formula = Weight ~ Condition_f, data = df_dens_t0)\n\nLinear Hypotheses:\n              Estimate Std. Error t value Pr(>|t|)\nD2 - D1 == 0    -0.575      1.381  -0.416    0.955\nD2b - D1 == 0   -1.820      1.334  -1.364    0.359\nD5 - D1 == 0    -0.380      1.235  -0.308    0.984\nD7 - D1 == 0    -1.046      1.205  -0.868    0.684\n(Adjusted p values reported -- single-step method)\n```\n\n\n:::\n:::\n\n\n\n\n### Growth trajectories\n\n@fig-densgrowthtraj shows all data points collected during the experiment.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxmax <- 170\nymax <- 2500\n\np <- ggplot()+\n  geom_point(\n    data = df_dens_growth_full,\n    aes(\n      x=t,\n      y=Weight,\n      color=as.factor(Condition),\n      group=as.factor(ID)\n    ),\n    alpha=0.5,\n    size=1\n  )+\n  geom_point(\n    data = df_dens_growth_mean_rep,\n    aes(\n      x=t,\n      y=Weight,\n      color=as.factor(Condition)\n    ),\n    size=1.2\n  )+\n  geom_line(\n    data = df_dens_growth_mean_rep,\n    aes(\n      x=t,\n      y=Weight,\n      color=as.factor(Condition)\n    )\n  )+\n  scale_color_manual(\n    name=\"Conditions\",\n    values=pal_dens\n    )+\n  facet_grid(cols=vars(Condition), rows=vars(Nb_rep))+\n  scale_x_continuous(\n    limits = c(0, xmax),       \n    breaks = seq(0, xmax, by = 28),\n    minor_breaks = seq(0, xmax, by = 14) \n  ) +\n  ylim(0, ymax)+\n  labs(\n    x=\"Time (days)\",\n    y = \"Weight (mg)\"\n  )+\n  theme_minimal()\np\n```\n\n::: {.cell-output-display}\n![Growth trajectories of earthworms per conditions.](B_DENS_experiment_files/figure-html/fig-densgrowthtraj-1.png){#fig-densgrowthtraj width=768}\n:::\n:::\n\n\n\n\n\n\n## Effect of density\n\n### Juvenile growth rate\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf_GrowthRate <- function(data){\n \n  df_GrowthRate <- data.frame() \n \n  for (i in unique(data$ID_cosm)){\n\n    data_i <- subset(data, ID_cosm == i) \n    Nb_vdt_i <- unique(subset(data_i, t==0)$Nb_vdt)\n    Food_i <- unique(subset(data_i, t==0)$Food)\n    Nb_rep_i <- unique(subset(data_i, t==0)$Nb_rep)\n    Lot_i <- unique(subset(data_i, t==0)$Lot)\n    Condition_i <- unique(subset(data_i, t==0)$Condition)\n   \n    if (length(na.omit(data_i$L))<2) {\n      a.Est <- NA\n      \n    }else if(length(na.omit(data_i$L))==2){ \n     \n      a.Est <- (subset(data_i, !t==0)$L - subset(data_i, t==0)$L)/subset(data_i, !t==0)$t # (L(t=t)-L(t=0))/t\n     \n    }else{\n      lm_i <- lm(L~t, data=data_i)\n      a.Est <- lm_i$coefficients[2]\n    }\n   \n    df_GrowthRate_i <- data.frame(\n      ID_cosm = i,\n      Nb_vdt = Nb_vdt_i,\n      Food = Food_i,\n      Nb_rep = Nb_rep_i,\n      Lot = Lot_i,\n      Condition = Condition_i,\n      Growth_rate = a.Est\n    )\n    \n    df_GrowthRate <- rbind(df_GrowthRate, df_GrowthRate_i)\n  }\n \n  return(df_GrowthRate) \n}\n\ndf_dens_juv_mean <- df_dens_growth |> \n  filter(Status == \"J\") |> \n  aggregate(Weight~Condition+Nb_rep+Nb_vdt+Food+Lot+t, FUN=mean) |> \n  mutate(\n    ID_cosm = paste0(Condition, Nb_rep),\n    L = Weight^(1/3),\n    Nb_vdt_f = as.factor(Nb_vdt)\n  )\n\ndf_GrowthRate <- f_GrowthRate(df_dens_juv_mean) |> \n  mutate(\n    Nb_vdt_f = as.factor(Nb_vdt),\n    Food_f = as.factor(Food)\n  )\n\ndf_GrowthRate_mean <- df_GrowthRate |> \n  aggregate(Growth_rate~Condition, FUN=mean)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot(\n  data = df_GrowthRate,\n  aes(\n    x = Condition,\n    y = Growth_rate\n  )\n)+\n  geom_boxplot(\n    alpha=0,\n    color=Nord_polar[4],\n    fill=Nord_frost[4]\n  )+\n  geom_dotplot(\n    binaxis='y',\n    stackdir='center',\n    alpha=0.5,\n    color=Nord_frost[4],\n    fill=Nord_frost[4]\n  )+\n  labs(\n    x = \"Density (# earthworm / cosm)\",\n    y = expression(paste(\"Growth rate (\",mg^{1/3},\"/day)\"))\n  )+\n  theme_minimal()\np\n```\n\n::: {.cell-output-display}\n![Growth rates of earthworms per condition](B_DENS_experiment_files/figure-html/fig-densgrowthratedens-1.png){#fig-densgrowthratedens width=768}\n:::\n:::\n\n::: {.cell tbl-cap='Growth rate per condition'}\n\n```{.r .cell-code}\ndf_GrowthRate_mean <- df_GrowthRate |> \n  aggregate(Growth_rate~Condition, FUN=mean)\ndf_GrowthRate_mean |> datatable(\n  options = list(\n    dom = 't',\n    pageLength = nrow(df_GrowthRate_mean),\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n    )\n  ),\n  class = \"hover\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-09714a492ee4bcb7aebf\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-09714a492ee4bcb7aebf\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\"],[\"D1\",\"D2\",\"D2b\",\"D5\",\"D7\"],[0.09679109393879269,0.08224772172472006,0.07583703713760577,0.08368750278000171,0.06150103044655759]],\"container\":\"<table class=\\\"hover\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Condition<\\/th>\\n      <th>Growth_rate<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":5,\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Condition\",\"targets\":1},{\"name\":\"Growth_rate\",\"targets\":2}],\"order\":[],\"orderClasses\":false,\"lengthMenu\":[5,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\nIs there an effect of density on juvenile growth rate ?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_model <- aov(Growth_rate ~ Condition, data = subset(df_GrowthRate, Condition != \"D2b\"))\nsummary(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df   Sum Sq   Mean Sq F value Pr(>F)  \nCondition    3 0.002145 0.0007151   5.269  0.017 *\nResiduals   11 0.001493 0.0001357                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n1 observation deleted due to missingness\n```\n\n\n:::\n\n```{.r .cell-code}\n# Normalité des résidus\nshapiro.test(residuals(anova_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(anova_model)\nW = 0.92793, p-value = 0.254\n```\n\n\n:::\n\n```{.r .cell-code}\n# Homogénéité des variances\nbartlett.test(Growth_rate ~ Condition, data = df_GrowthRate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBartlett test of homogeneity of variances\n\ndata:  Growth_rate by Condition\nBartlett's K-squared = 2.2825, df = 4, p-value = 0.684\n```\n\n\n:::\n\n```{.r .cell-code}\nTukeyHSD(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = Growth_rate ~ Condition, data = subset(df_GrowthRate, Condition != \"D2b\"))\n\n$Condition\n              diff         lwr          upr     p adj\nD2-D1 -0.014543372 -0.03933491  0.010248163 0.3386941\nD5-D1 -0.013103591 -0.03789513  0.011687944 0.4221341\nD7-D1 -0.035290063 -0.06206798 -0.008512145 0.0101374\nD5-D2  0.001439781 -0.02335175  0.026231316 0.9979844\nD7-D2 -0.020746691 -0.04752461  0.006031227 0.1496376\nD7-D5 -0.022186472 -0.04896439  0.004591446 0.1160833\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dens_growth_dens <- df_dens_growth |> \n  filter(!(Condition %in% c(\"D2b\")))\ndf_dens_growth_dens_mean_rep <- df_dens_growth_mean_rep |> \n  filter(!(Condition %in% c(\"D2b\")))\n\npal_dens_dens <- c(\"#B48EAD\", \"#5E81AC\", \"#88C0D0\", \"#8FBCBB\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nxmax <- 170\nymax <- 2000\n\np <- ggplot()+\n  geom_point(\n    data = df_dens_growth_dens,\n    aes(\n      x=t,\n      y=Weight,\n      color=as.factor(Condition),\n      group=as.factor(ID)\n    ),\n    alpha=0.5,\n    size=2\n  )+\n  geom_point(\n    data = df_dens_growth_dens_mean_rep,\n    aes(\n      x=t,\n      y=Weight,\n      color=as.factor(Condition)\n    ),\n    size=2\n  )+\n  geom_line(\n    data = df_dens_growth_dens_mean_rep,\n    aes(\n      x=t,\n      y=Weight,\n      color=as.factor(Condition)\n    )\n  )+\n  scale_color_manual(\n    name=\"Replicate\\nnumber\",\n    values=pal_dens_dens\n    )+\n  facet_grid(cols=vars(Condition), rows=vars(Nb_rep))+\n  scale_x_continuous(\n    limits = c(0, xmax),       \n    breaks = seq(0, xmax, by = 28),\n    minor_breaks = seq(0, xmax, by = 14) \n  ) +\n  ylim(0, ymax)+\n  labs(\n    x=\"Time (days)\",\n    y = \"Weight (mg)\"\n  )+\n  theme_minimal()\np\n```\n\n::: {.cell-output-display}\n![Growth trajectories of earthworms per conditions.](B_DENS_experiment_files/figure-html/fig-densgrowthtraj21-1.png){#fig-densgrowthtraj21 width=768}\n:::\n:::\n\n\n\n\n### Cocoon production\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxmax <- 170\nymax <- 25\n\np <- ggplot()+\n  geom_point(\n    data = subset(df_dens_repro, Condition != \"D2b\"),\n    aes(\n      x=t,\n      y=Reproduction,\n      color=as.factor(Condition)\n    ),\n    size=2\n  )+\n  geom_line(\n    data = subset(df_dens_repro, Condition != \"D2b\"),\n    aes(\n      x=t,\n      y=Reproduction,\n      color=as.factor(Condition)\n    )\n  )+\n  scale_color_manual(\n    name=\"Replicate\\nnumber\",\n    values=pal_dens\n    )+\n  facet_grid(cols=vars(Condition), rows=vars(Nb_rep))+\n  scale_x_continuous(\n    limits = c(0, xmax),       \n    breaks = seq(0, xmax, by = 28),\n    minor_breaks = seq(0, xmax, by = 14) \n  ) +\n  ylim(0, ymax)+\n  labs(\n    x=\"Time (days)\",\n    y = \"Cumulated reproduction (#/ind)\"\n  )+\n  theme_minimal()\np\n```\n\n::: {.cell-output-display}\n![Reproduction of earthworms per conditions.](B_DENS_experiment_files/figure-html/fig-densegg-1.png){#fig-densegg width=768}\n:::\n:::\n\n::: {.cell tbl-cap='Reproduction rate per condition'}\n\n```{.r .cell-code}\ndf_dens_repro_clean <- df_dens_repro |>\n  filter(!(Condition %in% c(\"D1\"))) |>\n  arrange(ID, t) |>\n  group_by(ID) |>\n  mutate(\n    start_repro = min(t[Nb_cocoons > 0], na.rm = TRUE)\n  ) |>\n  ungroup() |>\n  filter(is.finite(start_repro)) |>\n  arrange(ID, t) |>\n  group_by(ID) |>\n  mutate(\n    dt = t - lag(t)\n  ) |>\n  ungroup()  |>\n  mutate(\n    Repro_rate = Nb_cocoons / (Nb_vdt * dt)\n  ) |> \n  filter(Repro_rate!=0) |> \n  group_by(ID) |> \n  slice(-1) |> # Remove first repro rate bc reproduction started some unknow time during the previous 28 days.\n  summarise(\n    Repro_rate = mean(Repro_rate, na.rm = TRUE),\n    Condition = first(Condition),\n    Food = first(Food),\n    Nb_vdt = first(Nb_vdt),\n    .groups = \"drop\"\n  ) |> \n  ungroup()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: There were 7 warnings in `mutate()`.\nThe first warning was:\nℹ In argument: `start_repro = min(t[Nb_cocoons > 0], na.rm = TRUE)`.\nℹ In group 5: `ID = \"AD2b1\"`.\nCaused by warning in `min()`:\n! no non-missing arguments to min; returning Inf\nℹ Run `dplyr::last_dplyr_warnings()` to see the 6 remaining warnings.\n```\n\n\n:::\n\n```{.r .cell-code}\ndf_dens_reprorate_mean <- df_dens_repro_clean %>%\n  aggregate(Repro_rate~Condition, FUN=mean)\n\ndf_dens_reprorate_mean  |> \n  mutate(Repro_rate = round(Repro_rate, 2)) |> \n  datatable(\n  options = list(\n    dom = 't',\n    pageLength = nrow(df_dens_reprorate_mean),\n    autoWidth = TRUE,\n    columnDefs = list(\n      list(className = 'dt-left', targets = \"_all\")\n    )\n  ),\n  class = \"hover\"\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-09714a492ee4bcb7aebf\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-09714a492ee4bcb7aebf\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\"],[\"D2\",\"D2b\",\"D5\"],[0.41,0.37,0.23]],\"container\":\"<table class=\\\"hover\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Condition<\\/th>\\n      <th>Repro_rate<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"dom\":\"t\",\"pageLength\":3,\"autoWidth\":true,\"columnDefs\":[{\"className\":\"dt-left\",\"targets\":\"_all\"},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Condition\",\"targets\":1},{\"name\":\"Repro_rate\",\"targets\":2}],\"order\":[],\"orderClasses\":false,\"lengthMenu\":[3,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\nIs there an effect of density on earthworm reproduction ?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- glm(\n  Repro_rate ~ Condition,\n  family = Gamma(link = \"log\"),\n  data = df_dens_repro_clean |> filter(!(Condition == \"D2b\") & !is.na(Repro_rate))\n)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Repro_rate ~ Condition, family = Gamma(link = \"log\"), \n    data = filter(df_dens_repro_clean, !(Condition == \"D2b\") & \n        !is.na(Repro_rate)))\n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)   \n(Intercept)  -0.8826     0.1679  -5.258   0.0019 **\nConditionD5  -0.5778     0.2374  -2.434   0.0509 . \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Gamma family taken to be 0.1127052)\n\n    Null deviance: 1.5827  on 7  degrees of freedom\nResidual deviance: 0.9242  on 6  degrees of freedom\nAIC: -8.0776\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nemmeans(model, pairwise ~ Condition, adjust = \"tukey\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n Condition emmean    SE df lower.CL upper.CL\n D2        -0.883 0.168  6    -1.29   -0.472\n D5        -1.460 0.168  6    -1.87   -1.050\n\nResults are given on the log (not the response) scale. \nConfidence level used: 0.95 \n\n$contrasts\n contrast estimate    SE df t.ratio p.value\n D2 - D5     0.578 0.237  6   2.434  0.0509\n\nResults are given on the log (not the response) scale. \n```\n\n\n:::\n:::\n\n\n\n\n## Effect of food\n\n### Juvenile growth rate\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_GrowthRate_food <- subset(df_GrowthRate, Nb_vdt == 2)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot(\n  data = df_GrowthRate_food,\n  aes(\n    x = Food_f,\n    y = Growth_rate\n  )\n)+\n  geom_boxplot(\n    alpha=0,\n    color=Nord_polar[4],\n    fill=Nord_frost[4]\n  )+\n  geom_dotplot(\n    binaxis='y',\n    stackdir='center',\n    alpha=0.5,\n    color=Nord_frost[4],\n    fill=Nord_frost[4]\n  )+\n  labs(\n    x = \"Horse dung quantity given per earthworm every 14 days\",\n    y = expression(paste(\"Growth rate (\",mg^{1/3},\"/day)\"))\n  )+\n  theme_minimal()\np\n```\n\n::: {.cell-output-display}\n![Growth rates of earthworms per food condition (density = 2).](B_DENS_experiment_files/figure-html/fig-densgrowthratefood-1.png){#fig-densgrowthratefood width=576}\n:::\n:::\n\n\n\n\nIs there an effect of food on growth rate ?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(df_GrowthRate_food$Growth_rate) # Si pas signif alors donnee pas inconsistentes avec une loi normale\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  df_GrowthRate_food$Growth_rate\nW = 0.91938, p-value = 0.4646\n```\n\n\n:::\n\n```{.r .cell-code}\nvar.test(df_GrowthRate_food$Growth_rate~df_GrowthRate_food$Food) # Si pas signif alors variance égale\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  df_GrowthRate_food$Growth_rate by df_GrowthRate_food$Food\nF = 0.56821, num df = 3, denom df = 2, p-value = 0.6243\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.01450797 9.11645074\nsample estimates:\nratio of variances \n         0.5682118 \n```\n\n\n:::\n\n```{.r .cell-code}\nt.test(df_GrowthRate_food$Growth_rate~df_GrowthRate_food$Food, alternative = \"two.sided\", var.equal=T) # si signif différence signif entre les deux groupes\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  df_GrowthRate_food$Growth_rate by df_GrowthRate_food$Food\nt = 0.64579, df = 5, p-value = 0.5469\nalternative hypothesis: true difference in means between group 1.5 and group 3 is not equal to 0\n95 percent confidence interval:\n -0.01910705  0.03192842\nsample estimates:\nmean in group 1.5   mean in group 3 \n       0.08224772        0.07583704 \n```\n\n\n:::\n:::\n\n\n\n\n### Cocoon production\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_dens_repro_clean_food <- subset(df_dens_repro_clean, Nb_vdt == 2) |> \n  mutate(Food_f = as.factor(Food))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot(\n  data = df_dens_repro_clean_food,\n  aes(\n    x = Food_f,\n    y = Repro_rate\n  )\n)+\n  geom_boxplot(\n    alpha=0,\n    color=Nord_polar[4],\n    fill=Nord_frost[4]\n  )+\n  geom_dotplot(\n    binaxis='y',\n    stackdir='center',\n    alpha=0.5,\n    color=Nord_frost[4],\n    fill=Nord_frost[4]\n  )+\n  labs(\n    x = \"Horse dung quantity given per earthworm every 14 days\",\n    y = expression(paste(\"Reproduction rate (#/ind/day)\"))\n  )+\n  theme_minimal()\np\n```\n\n::: {.cell-output-display}\n![Reproduction rates of earthworms per food condition (density = 2).](B_DENS_experiment_files/figure-html/fig-densreproratefood-1.png){#fig-densreproratefood width=576}\n:::\n:::\n\n\n\n\n## Summary\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_max <- max((df_dens_growth_mean_rep |> filter(!(Condition == \"D2b\")))$t)\n\np_G <- ggplot()+\n  geom_point(\n    data = df_dens_growth_mean_rep |> filter(!(Condition == \"D2b\")),\n    aes(\n      x = t,\n      y = Weight,\n      color = Condition\n    ),\n    alpha = 0.5,\n    size = 1.4\n  )+\n  geom_line(\n    data = df_dens_growth_mean_cond |> filter(!(Condition == \"D2b\")),\n    aes(\n      x = t,\n      y = Weight,\n      color = Condition\n    )\n  )+\n  geom_point(\n    data = df_dens_growth_mean_cond |> filter(!(Condition == \"D2b\")),\n    aes(\n      x = t,\n      y = Weight,\n      color = Condition\n    ),\n    size = 2,\n    shape = shape_EPX\n  )+\n  facet_wrap(\n    ~ Condition, ncol=4\n  )+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  labs(x = \"Time (days)\", y = \"Weight (mg)\")+\n  scale_color_manual(values = pal_dens[-3])+\n  theme_minimal()+\n  theme(legend.position = \"none\")\n\np_R <- ggplot()+\n  geom_point(\n    data = df_dens_repro |> filter(!(Condition == \"D2b\")),\n    aes(\n      x = t,\n      y = Reproduction,\n      color = Condition\n    ),\n    alpha = 0.5,\n    size = 1.4\n  )+\n  geom_line(\n    data = df_dens_repro_mean_cond |> filter(!(Condition == \"D2b\")),\n    aes(\n      x = t,\n      y = Reproduction,\n      color = Condition\n    )\n  )+\n  geom_point(\n    data = df_dens_repro_mean_cond |> filter(!(Condition == \"D2b\")),\n    aes(\n      x = t,\n      y = Reproduction,\n      color = Condition\n    ),\n    size = 2,\n    shape = shape_EPX\n  )+\n  facet_wrap(\n    ~ Condition, ncol=4\n  )+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  labs(x = \"Time (days)\", y = \"Cumulated reproduction (#)\")+\n  scale_color_manual(values = pal_dens[-3])+\n  theme_minimal()+\n  theme(\n    legend.position = \"none\",\n    strip.text = element_blank()\n    )\n\np <- p_G / p_R\np\n```\n\n::: {.cell-output-display}\n![Growth curves and cumulative reproduction of earthworms across density treatments (cosm densities of 1, 2, 5, and 7 individuals). Small points correspond to the mean weight of earthworm at the replicate level, bigger plain squares correspond to the mean weight at the condition level.](B_DENS_experiment_files/figure-html/fig-summarydens-1.png){#fig-summarydens width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_max <- max((df_dens_growth_mean_rep |> filter((Condition %in% c(\"D2\",\"D2b\"))))$t)\nt_D2b <- 112\n\np_G <- ggplot()+\n  geom_point(\n    data = df_dens_growth_mean_rep |> filter((Condition %in% c(\"D2\",\"D2b\"))),\n    aes(\n      x = t,\n      y = Weight,\n      color = Condition\n    ),\n    alpha = 0.6,\n    size = 1.4\n  )+\n  geom_line(\n    data = df_dens_growth_mean_cond |> filter((Condition %in% c(\"D2\",\"D2b\"))&(!(Condition == \"D2b\" & t > t_D2b))),\n    aes(\n      x = t,\n      y = Weight,\n      color = Condition\n    )\n  )+\n  geom_point(\n    data = df_dens_growth_mean_cond |> filter((Condition %in% c(\"D2\",\"D2b\"))&(!(Condition == \"D2b\" & t > t_D2b))),\n    aes(\n      x = t,\n      y = Weight,\n      color = Condition\n    ),\n    size = 2,\n    shape = shape_EPX\n  )+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  labs(x = \"Time (days)\", y = \"Weight (mg)\")+\n  scale_color_manual(values = c(Nord_snow[1], pal_dens[3]))+\n  theme_minimal()+\n  theme(legend.position = \"none\")\n\np_R <- ggplot()+\n  geom_point(\n    data = df_dens_repro |> filter((Condition %in% c(\"D2\",\"D2b\"))),\n    aes(\n      x = t,\n      y = Reproduction,\n      color = Condition\n    ),\n    alpha = 0.6,\n    size = 1.4\n  )+\n  geom_line(\n    data = df_dens_repro_mean_cond |> filter((Condition %in% c(\"D2\",\"D2b\"))&(!(Condition == \"D2b\" & t > t_D2b))),\n    aes(\n      x = t,\n      y = Reproduction,\n      color = Condition\n    )\n  )+\n  geom_point(\n    data = df_dens_repro_mean_cond |> filter((Condition %in% c(\"D2\",\"D2b\"))&(!(Condition == \"D2b\" & t > t_D2b))),\n    aes(\n      x = t,\n      y = Reproduction,\n      color = Condition\n    ),\n    size = 2,\n    shape = shape_EPX\n  )+\n  scale_x_continuous(     \n    breaks = seq(0, t_max, by = 28),        \n    minor_breaks = seq(0, t_max, by = 14)\n  ) +\n  labs(x = \"Time (days)\", y = \"Cumulated reproduction (#)\")+\n  scale_color_manual(values = c(Nord_snow[1], pal_dens[3]))+\n  theme_minimal()+\n  theme(legend.position = \"none\")\n\np <- p_G + p_R\np\n```\n\n::: {.cell-output-display}\n![Comparison of growth curves and cumulative reproduction of earthworms under standard (D2, grey) and increased food supply (D2b, blue) at constant density. Small points correspond to the mean weight of earthworm at the replicate level, bigger plain squares correspond to the mean weight at the condition level.](B_DENS_experiment_files/figure-html/fig-summaryfood-1.png){#fig-summaryfood width=576}\n:::\n:::\n\n\n\n\n\n\nA total of 516 body-mass measurements and 64 reproduction measurements were collected over the 154-day monitoring period. Initial body mass was homogeneous across treatments (median = 10.4 mg, Q1 = 8.7 mg, Q3 = 11.7 mg). Growth rates of each individual were estimated using a linear regression on the structural length of the earthworm ($L=W^{1/3}$) which is related to the weight ($W$) through an allometric relationship with a 1/3 power scaling [@gollot_2025]. A significant effect of density on juvenile growth rate was detected (ANOVA, $p$ = 0.02). However, post hoc comparisons (Tukey test) revealed that only the contrast between the two extremes of population densities was statistically significant (densities of 1 vs. 7 individuals per cosm, $p$ = 0.016). No individual reached maturity at the highest population density and we were not able to keep population density constant due to mortality. As a result we excluded this treatment from the statistical analysis of reproduction data. A possible decrease in reproduction with population density was detected (-43% between density 2 and density 5) with high inter-replicate variability (Tukey test : $p$ = 0.051, Figure 1).\n\nAt the highest density (D7), one individual died in each replicate at different times (days 14, 28, 56, 70, and 84 depending on the replicate). The remaining individuals ($n$ = 6 per replicate) survived until the end of the experiment (154 days). These replicates were excluded from the main analysis due to uncertainty regarding the exact timing of mortality.\n\nOnly two replicates yielded reproduction data in the D2b condition (density 2 with increased food supply), and these displayed contrasting dynamics. One replicate was monitored until day 154, whereas the second stopped at day 84, resulting in a visible discontinuity in cumulative reproduction after this time point. Prior to day 84, increasing food availability at constant density (D2b) resulted in only limited decreases in growth and similar reproduction compared with D2.\n\nOverall, both growth and reproduction tends to decrease with increasing density.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}