```{r lib, include = F}
library(here)
source(file = here::here("functions/fun.R"))
source(file = here::here("functions/fun_MCSim.R"))
f_load_libraries_colors()
col_Molecule <- rev(col_Molecule)
pal_chains <- c(Nord_aurora, Nord_frost, Nord_polar)
lab_chains <- c("1", "2", "3", "4", "5", "6", "7", "8")
```

# Case of isolated adults

## Load data

```{r}
path_fig <- here::here("fig/DEB_Models")
path_files <- here::here("mod/Y_DEB_IsolatedAdultes")

col_experiment <- c(
  Nord_aurora[1], 
  Nord_aurora[2], 
  Nord_aurora[5]
  )

l_Experiments_IsolatedAdults <- c(
  "Bart2019_XP1_1",    
  "Bart2019_XP4_1",
  "Gollot2026_dens_D1"
  )

Adults_alone <- TRUE
OM_diff <- TRUE

df_data_obs <- f_import_data_DEB(l_Experiments_IsolatedAdults, Adults_alone)
```

## Simulations

```{r setpointfullin}

Nb_experiment <- length(l_Experiments_IsolatedAdults)
step_sim <- 0.05
select_times <- seq(0,400, 0.1)

Endpoints_print <- "Weight,
    Reproduction"


l_param_name <- c("Fm", "pAm", "r_pAm_pM", "v", "kapJ", "kapA", "Ehp", "E_coc", "rOM_ClxHorse", "K", "dv", "de", "tau", "Sigma_W")

f_In_Setpoint_full(
  file.path(path_files, "kapJ"), l_Experiments_IsolatedAdults, 
  Adults_alone, OM_diff, 
  l_param_name, step_sim, Endpoints_print
  )

f_In_Setpoint_full(
  file.path(path_files, "kapA"), l_Experiments_IsolatedAdults, 
  Adults_alone, OM_diff, 
  l_param_name, step_sim, Endpoints_print
  )

```

```{bash, eval=F, execute=F}

# Put the tab_setpoint.out from the best model in each folder

for j in $(seq 1 3); do
./mcsim.DEBcali_A DEB_setpoint_full_${j}.in
done

for j in $(seq 1 3); do
./mcsim.DEBcali_J DEB_setpoint_full_${j}.in
done
```

```{r, message=F, warning=F}

file_rds_kapA <- file.path(file.path(path_files, "kapA"), paste0("Sim.Res.Exp.full.rds"))

if (file.exists(file_rds_kapA)) {
  df_pred_full_kapA <- readRDS(file_rds_kapA)
} else {
  df_pred_full_kapA <- f_read_Setpoint_full(file.path(path_files, "kapA"), l_Experiments_IsolatedAdults, Adults_alone = TRUE, Nb_experiment, select_times, step_sim)
}

file_rds_kapJ <- file.path(file.path(path_files, "kapJ"), paste0("Sim.Res.Exp.full.rds"))

if (file.exists(file_rds_kapJ)) {
  df_pred_full_kapJ <- readRDS(file_rds_kapJ)
} else {
  df_pred_full_kapJ <- f_read_Setpoint_full(file.path(path_files, "kapJ"), l_Experiments_IsolatedAdults, Adults_alone = TRUE, Nb_experiment, select_times, step_sim)
}

# Times where earthworm are first observed as adults
df_time_adult <- data.frame(
  ID_experiment = unique(df_data_obs$ID_experiment),
  Time_adult = c(98, 126, 84)
)

df_data_obs <- df_data_obs |> 
  left_join(df_time_adult) |> 
  mutate(
    Adult = case_when(
      Time >= Time_adult ~ "Yes",
      .default = "No"
    )
  )

df_pred_full_kapJ$kappa <- "J"
df_pred_full_kapA$kappa <- "A"

df_pred_full <- bind_rows(df_pred_full_kapJ, df_pred_full_kapA) |> 
  mutate(kappa = fct_relevel(kappa, c("J", "A")))

df_data_obs_kapJ <- df_data_obs |> mutate(kappa = "J")
df_data_obs_kapA <- df_data_obs |> mutate(kappa = "A")

df_data_obs_full <- bind_rows(df_data_obs_kapJ, df_data_obs_kapA) |> 
  mutate(kappa = fct_relevel(kappa, c("J", "A")))
```

```{r}
#| fig-cap: Predicted Weight for each experiment.
#| label: fig-predkapW
#| fig-height: 4
#| fig-width: 8

alpha_ribbon <- 0.15
line_width <- 1.1
point_stroke <- 0.9
alpha_line <- 0.7
wrap_nb_col <- 2

col_kappa <- c(Nord_frost[2], Nord_frost[4], Nord_frost[4])
col_data <- Nord_polar[4]

ID_exp_plot <- "Bart2019_XP1_1"

p_XP11 <- ggplot()+
  
  geom_ribbon(
    data = subset(df_pred_full, Endpt == "Weight" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      ymax = up,
      ymin = low,
      fill = kappa
    ),
    alpha = alpha_ribbon
  )+
  
  geom_line(
    data = subset(df_pred_full, Endpt == "Weight" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      y = predict.endpoint,
      color = kappa
    ),
    linewidth = line_width,
    alpha = alpha_line
  )+
  
  geom_point(
    data = df_data_obs_full |> filter(ID_experiment == ID_exp_plot),    
    aes(  
      x = Time, 
      y = Weight, 
      alpha = Adult
    ),
    color = col_data,
    stroke = point_stroke
  )+
  
  scale_color_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_fill_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_alpha_manual(
    name = "Status",
    values = c(0.2, 0.7),
    labels = c("Juvenile", "Adult")
  )+
  labs(
    x = "Time (days)", 
    y = "Weight (g)",
    title = ID_exp_plot
  )+
  
  theme_minimal()+
  theme(
    plot.title = element_text(face="bold", size = 10),
    legend.text = element_text(size = 11)
  )


ID_exp_plot <- "Bart2019_XP4_1"

p_XP41 <- ggplot()+
  
  geom_ribbon(
    data = subset(df_pred_full, Endpt == "Weight" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      ymax = up,
      ymin = low,
      fill = kappa
    ),
    alpha = alpha_ribbon
  )+
  
  geom_line(
    data = subset(df_pred_full, Endpt == "Weight" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      y = predict.endpoint,
      color = kappa
    ),
    linewidth = line_width,
    alpha = alpha_line
  )+
  
  geom_point(
    data = df_data_obs_full |> filter(ID_experiment == ID_exp_plot),    
    aes(  
      x = Time, 
      y = Weight, 
      alpha = Adult
    ),
    color = col_data,
    stroke = point_stroke
  )+
  
  scale_color_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_fill_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_alpha_manual(
    name = "Status",
    values = c(0.2, 0.7),
    labels = c("Juvenile", "Adult")
  )+
  labs(
    x = "Time (days)", 
    y = "Weight (g)",
    title = ID_exp_plot
  )+
  
  theme_minimal()+
  theme(
    plot.title = element_text(face="bold", size = 10),
    legend.text = element_text(size = 11)
  )

ID_exp_plot <- "Gollot2026_dens_D1"

p_D1 <- ggplot()+
  
  geom_ribbon(
    data = subset(df_pred_full, Endpt == "Weight" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      ymax = up,
      ymin = low,
      fill = kappa
    ),
    alpha = alpha_ribbon
  )+
  
  geom_line(
    data = subset(df_pred_full, Endpt == "Weight" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      y = predict.endpoint,
      color = kappa
    ),
    linewidth = line_width,
    alpha = alpha_line
  )+
  
  geom_point(
    data = df_data_obs_full |> filter(ID_experiment == ID_exp_plot),    
    aes(  
      x = Time, 
      y = Weight, 
      alpha = Adult
    ),
    color = col_data,
    stroke = point_stroke
  )+
  
  scale_color_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_fill_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_alpha_manual(
    name = "Status",
    values = c(0.2, 0.7),
    labels = c("Juvenile", "Adult")
  )+
  labs(
    x = "Time (days)", 
    y = "Weight (g)",
    title = ID_exp_plot
  )+
  
  theme_minimal()+
  theme(
    plot.title = element_text(face="bold", size = 10),
    legend.text = element_text(size = 11)
  )

pW <- p_XP11 + p_XP41 + p_D1 + 
  plot_layout(ncol=3, guides = "collect") # +
  # plot_annotation(tag_levels = "A")
pW
```

```{r savetrajW, include = F}
ggsave(
  filename="Y_IsolatedAdults_trajW.png", 
  plot=pW, 
  width=8, height = 4, 
  path=path_fig
  )
```

```{r}
#| fig-cap: Predicted Reproduction for each experiment.
#| label: fig-predkapR
#| fig-height: 4
#| fig-width: 8

alpha_ribbon <- 0.15
line_width <- 1.1
point_stroke <- 0.9
alpha_line <- 0.7
wrap_nb_col <- 2

col_kappa <- c(Nord_frost[2], Nord_frost[4])
col_data <- Nord_polar[4]

ID_exp_plot <- "Bart2019_XP1_1"

p_XP11 <- ggplot()+
  
  geom_ribbon(
    data = subset(df_pred_full, Endpt == "Reproduction" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      ymax = up,
      ymin = low,
      fill = kappa
    ),
    alpha = alpha_ribbon
  )+
  
  geom_line(
    data = subset(df_pred_full, Endpt == "Reproduction" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      y = predict.endpoint,
      color = kappa
    ),
    linewidth = line_width,
    alpha = alpha_line
  )+
  
  geom_point(
    data = df_data_obs_full |> filter(ID_experiment == ID_exp_plot),    
    aes(  
      x = Time, 
      y = Reproduction, 
      alpha = Adult
    ),
    color = col_data,
    stroke = point_stroke
  )+
  
  scale_color_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_fill_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_alpha_manual(
    name = "Status",
    values = c(0.2, 0.7),
    labels = c("Juvenile", "Adult")
  )+
  labs(
    x = "Time (days)", 
    y = "Reproduction (#)",
    title = ID_exp_plot
  )+
  
  theme_minimal()+
  theme(
    plot.title = element_text(face="bold", size = 10),
    legend.text = element_text(size = 11)
  )


ID_exp_plot <- "Bart2019_XP4_1"

p_XP41 <- ggplot()+
  
  geom_ribbon(
    data = subset(df_pred_full, Endpt == "Reproduction" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      ymax = up,
      ymin = low,
      fill = kappa
    ),
    alpha = alpha_ribbon
  )+
  
  geom_line(
    data = subset(df_pred_full, Endpt == "Reproduction" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      y = predict.endpoint,
      color = kappa
    ),
    linewidth = line_width,
    alpha = alpha_line
  )+
  
  geom_point(
    data = df_data_obs_full |> filter(ID_experiment == ID_exp_plot),    
    aes(  
      x = Time, 
      y = Reproduction, 
      alpha = Adult
    ),
    color = col_data,
    stroke = point_stroke
  )+
  
  scale_color_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_fill_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_alpha_manual(
    name = "Status",
    values = c(0.2, 0.7),
    labels = c("Juvenile", "Adult")
  )+
  labs(
    x = "Time (days)", 
    y = "Reproduction (#)",
    title = ID_exp_plot
  )+
  
  theme_minimal()+
  theme(
    plot.title = element_text(face="bold", size = 10),
    legend.text = element_text(size = 11)
  )

ID_exp_plot <- "Gollot2026_dens_D1"

p_D1 <- ggplot()+
  
  geom_ribbon(
    data = subset(df_pred_full, Endpt == "Reproduction" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      ymax = up,
      ymin = low,
      fill = kappa
    ),
    alpha = alpha_ribbon
  )+
  
  geom_line(
    data = subset(df_pred_full, Endpt == "Reproduction" & ID_experiment == ID_exp_plot),
    aes(
      x = Time,
      y = predict.endpoint,
      color = kappa
    ),
    linewidth = line_width,
    alpha = alpha_line
  )+
  
  geom_point(
    data = df_data_obs_full |> filter(ID_experiment == ID_exp_plot),    
    aes(  
      x = Time, 
      y = Reproduction, 
      alpha = Adult
    ),
    color = col_data,
    stroke = point_stroke
  )+
  
  scale_color_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_fill_manual(
    name = "Kappa for adults",
    labels = expression(kappa[J], kappa[A]),
    values = col_kappa
  )+
  scale_alpha_manual(
    name = "Status",
    values = c(0.2, 0.7),
    labels = c("Juvenile", "Adult")
  )+
  labs(
    x = "Time (days)", 
    y = "Reproduction (#)",
    title = ID_exp_plot
  )+
  
  theme_minimal()+
  theme(
    plot.title = element_text(face="bold", size = 10),
    legend.text = element_text(size = 11)
  )

pR <- p_XP11 + p_XP41 + p_D1 + 
  plot_layout(ncol=3, guides = "collect") # +
  # plot_annotation(tag_levels = "A")
pR
```

```{r savetrajR, include = F}
ggsave(
  filename="Y_IsolatedAdults_trajR.png", 
  plot=pR, 
  width=8, height = 4, 
  path=path_fig
  )
```
