```{r lib, include = F}
library(here)
source(file = here::here("functions/fun.R"))
source(file = here::here("functions/fun_MCSim.R"))
f_load_libraries_colors()
col_Molecule <- rev(col_Molecule)
pal_chains <- c(Nord_aurora, Nord_frost, Nord_polar)
lab_chains <- c("1", "2", "3", "4", "5", "6", "7", "8")
```

## DEB-TKTD - Epoxiconazole

### Model fit

```{r}
Molec <- "EPX"
path_fig <- here::here("fig/DEBTKTD_Models")

# 1 pMoA
path_A_EPX_A <- here::here("mod/Z_DEB-TKTD/EPX/A_EPX_A")
path_B_EPX_M <- here::here("mod/Z_DEB-TKTD/EPX/B_EPX_M")
path_C_EPX_G <- here::here("mod/Z_DEB-TKTD/EPX/C_EPX_G")
path_D_EPX_R <- here::here("mod/Z_DEB-TKTD/EPX/D_EPX_R")

# 2 pMoA
path_E_EPX_AM <- here::here("mod/Z_DEB-TKTD/EPX/E_EPX_AM")
path_F_EPX_AG <- here::here("mod/Z_DEB-TKTD/EPX/F_EPX_AG")
path_G_EPX_AR <- here::here("mod/Z_DEB-TKTD/EPX/G_EPX_AR")
path_H_EPX_MG <- here::here("mod/Z_DEB-TKTD/EPX/H_EPX_MG")
path_I_EPX_MR <- here::here("mod/Z_DEB-TKTD/EPX/I_EPX_MR")
path_J_EPX_GR <- here::here("mod/Z_DEB-TKTD/EPX/J_EPX_GR")

# 3 pMoA
# path_K_EPX_AMG <- here::here("mod/Z_DEB-TKTD/EPX/K_EPX_AMG")
# path_L_EPX_AMR <- here::here("mod/Z_DEB-TKTD/EPX/L_EPX_AMR")
# path_M_EPX_AGR <- here::here("mod/Z_DEB-TKTD/EPX/M_EPX_AGR")
# path_N_EPX_MGR <- here::here("mod/Z_DEB-TKTD/EPX/N_EPX_MGR")


df_data_fit_EPX <- f_import_data_DEBTKTD() |> 
  filter(Molecule == Molec) |> 
  mutate(No_sim = case_when(
    Experiment_type == "Repro" ~ No_sim+9,
    .default = No_sim
  ))


```

```{r fit_EPX, message=F, warning=F}

path_fig <- here::here("fig/DEBTKTD_Models")
Molec <- "EPX"
df_data_fit_EPX <- f_import_data_DEBTKTD() |> filter(Molecule == Molec)
OM_diff <- TRUE

NbIter <- 30000
RTOL <- 1e-10
ATOL <- 1e-9

text_priors <- '

Distrib (nec,          TruncNormal_cv,                50000,     0.5, 100, 10000000);
Distrib (b,            LogUniform,                0.0000001,          0.01);

# Calcul des vraissemblances
Distrib (Sigma_W, TruncNormal,  0.005, 1, 0.01, 100);'

text_likelihood <- 'Likelihood (Weight,   Normal, Prediction(Weight), Sigma_W); 
Likelihood (Reproduction, Poisson, Prediction(Reproduction));'

######## A_EPX_A ##############################################################
seeds <- c(C1 = 3303, C2 = 6666, C3 = 2212)
f_In_TKTD_tot(path_A_EPX_A, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

######## B_EPX_M ##############################################################
seeds <- c(C1 = 3345, C2 = 6666, C3 = 2112)
f_In_TKTD_tot(path_B_EPX_M, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

######## C_EPX_G ##############################################################
seeds <- c(C1 = 3303, C2 = 6666, C3 = 2212)
f_In_TKTD_tot(path_C_EPX_G, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

######## D_EPX_R ##############################################################
seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
f_In_TKTD_tot(path_D_EPX_R, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

######## E_EPX_AM ##############################################################
seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
f_In_TKTD_tot(path_E_EPX_AM, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

######## F_EPX_AG ##############################################################
seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
f_In_TKTD_tot(path_F_EPX_AG, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

######## G_EPX_AR ##############################################################
seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
f_In_TKTD_tot(path_G_EPX_AR, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

######## H_EPX_MG ##############################################################
seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
f_In_TKTD_tot(path_H_EPX_MG, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

######## I_EPX_MR ##############################################################
seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
f_In_TKTD_tot(path_I_EPX_MR, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

######## J_EPX_GR ##############################################################
seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
f_In_TKTD_tot(path_J_EPX_GR, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

# ######## K_EPX_AMG ##############################################################
# seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
# f_In_TKTD_tot(path_K_EPX_AMG, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)
# 
# ######## L_EPX_AMR ##############################################################
# seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
# f_In_TKTD_tot(path_L_EPX_AMR, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)
# 
# ######## M_EPX_AGR ##############################################################
# seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
# f_In_TKTD_tot(path_M_EPX_AGR, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)
# 
# ######## N_EPX_MGR ##############################################################
# seeds <- c(C1 = 3345, C2 = 3666, C3 = 2212)
# f_In_TKTD_tot(path_N_EPX_MGR, Molec, text_priors, text_likelihood, NbIter, seeds, RTOL, ATOL)

# ./mcsim.DEB-EPX DEB_TKTD_C1.in

```

### Estimates results

```{r}
n_data_Weight <- length(na.omit(df_data_fit_EPX$Weight))
n_data_Reproduction <- length(na.omit(df_data_fit_EPX$Reproduction))
n_data_fit <- n_data_Weight + n_data_Reproduction

######### A_EPX_A ###############################################################

MCMC_out_A_EPX_A <- f_MCSim(path_A_EPX_A)

NC_A_EPX_A <- MCMC_out_A_EPX_A$NC
Nb_param_A_EPX_A <- MCMC_out_A_EPX_A$Nb_param
Nb_experiment_A_EPX_A <- MCMC_out_A_EPX_A$Nb_experiment
Nb_iter_kept_A_EPX_A <- MCMC_out_A_EPX_A$Nb_iter_kept
N_iter_setpoint_A_EPX_A <- MCMC_out_A_EPX_A$N_iter_setpoint
L_parameters_A_EPX_A <- unique(MCMC_out_A_EPX_A$Priors$Nom)

LL_A_EPX_A <- f_get_mode(MCMC_out_A_EPX_A$df_LnData$LnData)
k_A_EPX_A <- Nb_param_A_EPX_A - 1 # On enlève le Sigma_W

BIC_A_EPX_A <- -2*LL_A_EPX_A+k_A_EPX_A*log(n_data_fit)

Summary_res_A_EPX_A <- 
  as.data.frame(MCMC_out_A_EPX_A$Summary_res)[1:length(L_parameters_A_EPX_A)] |>
  mutate(Model = "A_EPX_A")

#Summary_res_A_EPX_A

######### B_EPX_M ###############################################################

MCMC_out_B_EPX_M <- f_MCSim(path_B_EPX_M)

NC_B_EPX_M <- MCMC_out_B_EPX_M$NC
Nb_param_B_EPX_M <- MCMC_out_B_EPX_M$Nb_param
Nb_experiment_B_EPX_M <- MCMC_out_B_EPX_M$Nb_experiment
Nb_iter_kept_B_EPX_M <- MCMC_out_B_EPX_M$Nb_iter_kept
N_iter_setpoint_B_EPX_M <- MCMC_out_B_EPX_M$N_iter_setpoint
L_parameters_B_EPX_M <- unique(MCMC_out_B_EPX_M$Priors$Nom)

LL_B_EPX_M <- f_get_mode(MCMC_out_B_EPX_M$df_LnData$LnData)
k_B_EPX_M <- Nb_param_B_EPX_M - 1 # On enlève le Sigma_W

BIC_B_EPX_M <- -2*LL_B_EPX_M+k_B_EPX_M*log(n_data_fit)

Summary_res_B_EPX_M <-
  as.data.frame(MCMC_out_B_EPX_M$Summary_res)[1:length(L_parameters_B_EPX_M)] |>
  mutate(Model = "B_EPX_M")

# Summary_res_B_EPX_M

######### C_EPX_G ###############################################################

MCMC_out_C_EPX_G <- f_MCSim(path_C_EPX_G)

NC_C_EPX_G <- MCMC_out_C_EPX_G$NC
Nb_param_C_EPX_G <- MCMC_out_C_EPX_G$Nb_param
Nb_experiment_C_EPX_G <- MCMC_out_C_EPX_G$Nb_experiment
Nb_iter_kept_C_EPX_G <- MCMC_out_C_EPX_G$Nb_iter_kept
N_iter_setpoint_C_EPX_G <- MCMC_out_C_EPX_G$N_iter_setpoint
L_parameters_C_EPX_G <- unique(MCMC_out_C_EPX_G$Priors$Nom)

LL_C_EPX_G <- f_get_mode(MCMC_out_C_EPX_G$df_LnData$LnData)
k_C_EPX_G <- Nb_param_C_EPX_G - 1 # On enlève le Sigma_W

BIC_C_EPX_G <- -2*LL_C_EPX_G+k_C_EPX_G*log(n_data_fit)

Summary_res_C_EPX_G <- 
  as.data.frame(MCMC_out_C_EPX_G$Summary_res)[1:length(L_parameters_C_EPX_G)] |> 
  mutate(Model = "C_EPX_G")

#Summary_res_C_EPX_G

######### D_EPX_R ###############################################################

MCMC_out_D_EPX_R <- f_MCSim(path_D_EPX_R)

NC_D_EPX_R <- MCMC_out_D_EPX_R$NC
Nb_param_D_EPX_R <- MCMC_out_D_EPX_R$Nb_param
Nb_experiment_D_EPX_R <- MCMC_out_D_EPX_R$Nb_experiment
Nb_iter_kept_D_EPX_R <- MCMC_out_D_EPX_R$Nb_iter_kept
N_iter_setpoint_D_EPX_R <- MCMC_out_D_EPX_R$N_iter_setpoint
L_parameters_D_EPX_R <- unique(MCMC_out_D_EPX_R$Priors$Nom)

LL_D_EPX_R <- f_get_mode(MCMC_out_D_EPX_R$df_LnData$LnData)
k_D_EPX_R <- Nb_param_D_EPX_R - 1 # On enlève le Sigma_W

BIC_D_EPX_R <- -2*LL_D_EPX_R+k_D_EPX_R*log(n_data_fit)

Summary_res_D_EPX_R <- 
  as.data.frame(MCMC_out_D_EPX_R$Summary_res)[1:length(L_parameters_D_EPX_R)] |>
  mutate(Model = "D_EPX_R")

#Summary_res_D_EPX_R

######### E_EPX_AM ###############################################################

MCMC_out_E_EPX_AM <- f_MCSim(path_E_EPX_AM)

NC_E_EPX_AM <- MCMC_out_E_EPX_AM$NC
Nb_param_E_EPX_AM <- MCMC_out_E_EPX_AM$Nb_param
Nb_experiment_E_EPX_AM <- MCMC_out_E_EPX_AM$Nb_experiment
Nb_iter_kept_E_EPX_AM <- MCMC_out_E_EPX_AM$Nb_iter_kept
N_iter_setpoint_E_EPX_AM <- MCMC_out_E_EPX_AM$N_iter_setpoint
L_parameters_E_EPX_AM <- unique(MCMC_out_E_EPX_AM$Priors$Nom)

LL_E_EPX_AM <- f_get_mode(MCMC_out_E_EPX_AM$df_LnData$LnData)
k_E_EPX_AM <- Nb_param_E_EPX_AM - 1 # On enlève le Sigma_W

BIC_E_EPX_AM <- -2*LL_E_EPX_AM+k_E_EPX_AM*log(n_data_fit)

Summary_res_E_EPX_AM <- 
  as.data.frame(MCMC_out_E_EPX_AM$Summary_res)[1:length(L_parameters_E_EPX_AM)] |>
  mutate(Model = "E_EPX_AM")

######### F_EPX_AG ###############################################################

MCMC_out_F_EPX_AG <- f_MCSim(path_F_EPX_AG)

NC_F_EPX_AG <- MCMC_out_F_EPX_AG$NC
Nb_param_F_EPX_AG <- MCMC_out_F_EPX_AG$Nb_param
Nb_experiment_F_EPX_AG <- MCMC_out_F_EPX_AG$Nb_experiment
Nb_iter_kept_F_EPX_AG <- MCMC_out_F_EPX_AG$Nb_iter_kept
N_iter_setpoint_F_EPX_AG <- MCMC_out_F_EPX_AG$N_iter_setpoint
L_parameters_F_EPX_AG <- unique(MCMC_out_F_EPX_AG$Priors$Nom)

LL_F_EPX_AG <- f_get_mode(MCMC_out_F_EPX_AG$df_LnData$LnData)
k_F_EPX_AG <- Nb_param_F_EPX_AG - 1 # On enlève le Sigma_W

BIC_F_EPX_AG <- -2*LL_F_EPX_AG+k_F_EPX_AG*log(n_data_fit)

Summary_res_F_EPX_AG <- 
  as.data.frame(MCMC_out_F_EPX_AG$Summary_res)[1:length(L_parameters_F_EPX_AG)] |>
  mutate(Model = "F_EPX_AG")

######### G_EPX_AR ###############################################################

MCMC_out_G_EPX_AR <- f_MCSim(path_G_EPX_AR)

NC_G_EPX_AR <- MCMC_out_G_EPX_AR$NC
Nb_param_G_EPX_AR <- MCMC_out_G_EPX_AR$Nb_param
Nb_experiment_G_EPX_AR <- MCMC_out_G_EPX_AR$Nb_experiment
Nb_iter_kept_G_EPX_AR <- MCMC_out_G_EPX_AR$Nb_iter_kept
N_iter_setpoint_G_EPX_AR <- MCMC_out_G_EPX_AR$N_iter_setpoint
L_parameters_G_EPX_AR <- unique(MCMC_out_G_EPX_AR$Priors$Nom)

LL_G_EPX_AR <- f_get_mode(MCMC_out_G_EPX_AR$df_LnData$LnData)
k_G_EPX_AR <- Nb_param_G_EPX_AR - 1 # On enlève le Sigma_W

BIC_G_EPX_AR <- -2*LL_G_EPX_AR+k_G_EPX_AR*log(n_data_fit)

Summary_res_G_EPX_AR <- 
  as.data.frame(MCMC_out_G_EPX_AR$Summary_res)[1:length(L_parameters_G_EPX_AR)] |>
  mutate(Model = "G_EPX_AR")

#Summary_res_G_EPX_AR

######### H_EPX_MG ###############################################################

MCMC_out_H_EPX_MG <- f_MCSim(path_H_EPX_MG)

NC_H_EPX_MG <- MCMC_out_H_EPX_MG$NC
Nb_param_H_EPX_MG <- MCMC_out_H_EPX_MG$Nb_param
Nb_experiment_H_EPX_MG <- MCMC_out_H_EPX_MG$Nb_experiment
Nb_iter_kept_H_EPX_MG <- MCMC_out_H_EPX_MG$Nb_iter_kept
N_iter_setpoint_H_EPX_MG <- MCMC_out_H_EPX_MG$N_iter_setpoint
L_parameters_H_EPX_MG <- unique(MCMC_out_H_EPX_MG$Priors$Nom)

LL_H_EPX_MG <- f_get_mode(MCMC_out_H_EPX_MG$df_LnData$LnData)
k_H_EPX_MG <- Nb_param_H_EPX_MG - 1 # On enlève le Sigma_W

BIC_H_EPX_MG <- -2*LL_H_EPX_MG+k_H_EPX_MG*log(n_data_fit)

Summary_res_H_EPX_MG <- 
  as.data.frame(MCMC_out_H_EPX_MG$Summary_res)[1:length(L_parameters_H_EPX_MG)] |>
  mutate(Model = "H_EPX_MG")

#Summary_res_H_EPX_MG

######### I_EPX_MR ###############################################################

MCMC_out_I_EPX_MR <- f_MCSim(path_I_EPX_MR)

NC_I_EPX_MR <- MCMC_out_I_EPX_MR$NC
Nb_param_I_EPX_MR <- MCMC_out_I_EPX_MR$Nb_param
Nb_experiment_I_EPX_MR <- MCMC_out_I_EPX_MR$Nb_experiment
Nb_iter_kept_I_EPX_MR <- MCMC_out_I_EPX_MR$Nb_iter_kept
N_iter_setpoint_I_EPX_MR <- MCMC_out_I_EPX_MR$N_iter_setpoint
L_parameters_I_EPX_MR <- unique(MCMC_out_I_EPX_MR$Priors$Nom)

LL_I_EPX_MR <- f_get_mode(MCMC_out_I_EPX_MR$df_LnData$LnData)
k_I_EPX_MR <- Nb_param_I_EPX_MR - 1 # On enlève le Sigma_W

BIC_I_EPX_MR <- -2*LL_I_EPX_MR+k_I_EPX_MR*log(n_data_fit)

Summary_res_I_EPX_MR <- 
  as.data.frame(MCMC_out_I_EPX_MR$Summary_res)[1:length(L_parameters_I_EPX_MR)] |>
  mutate(Model = "I_EPX_MR")

#Summary_res_I_EPX_MR

######### J_EPX_GR ###############################################################

MCMC_out_J_EPX_GR <- f_MCSim(path_J_EPX_GR)

NC_J_EPX_GR <- MCMC_out_J_EPX_GR$NC
Nb_param_J_EPX_GR <- MCMC_out_J_EPX_GR$Nb_param
Nb_experiment_J_EPX_GR <- MCMC_out_J_EPX_GR$Nb_experiment
Nb_iter_kept_J_EPX_GR <- MCMC_out_J_EPX_GR$Nb_iter_kept
N_iter_setpoint_J_EPX_GR <- MCMC_out_J_EPX_GR$N_iter_setpoint
L_parameters_J_EPX_GR <- unique(MCMC_out_J_EPX_GR$Priors$Nom)

LL_J_EPX_GR <- f_get_mode(MCMC_out_J_EPX_GR$df_LnData$LnData)
k_J_EPX_GR <- Nb_param_J_EPX_GR - 1 # On enlève le Sigma_W

BIC_J_EPX_GR <- -2*LL_J_EPX_GR+k_J_EPX_GR*log(n_data_fit)

Summary_res_J_EPX_GR <- 
  as.data.frame(MCMC_out_J_EPX_GR$Summary_res)[1:length(L_parameters_J_EPX_GR)] |>
  mutate(Model = "J_EPX_GR")

#Summary_res_D_EPX_R

list_models <- c("A_EPX_A", "B_EPX_M", "C_EPX_G", "D_EPX_R", 
                 "E_EPX_AM", "F_EPX_AG", "G_EPX_AR", "H_EPX_MG", "I_EPX_MR", "J_EPX_GR")
df_LL_BIC <- data.frame(
  Model = list_models,
  LL = round(unlist(mget(paste0("LL_", list_models))), 2),
  BIC = round(unlist(mget(paste0("BIC_", list_models))), 2)
)
```

```{r resall}
#| tbl-cap: Estimation results from all models. 

list_models <- c("A_EPX_A", "B_EPX_M", "C_EPX_G", "D_EPX_R", 
                 "E_EPX_AM", "F_EPX_AG", "G_EPX_AR", "H_EPX_MG", "I_EPX_MR", "J_EPX_GR")
list_model_summary <- mget(paste0("Summary_res_", list_models))

param_order <- c(
  "nec", "b"
)

format_summary <- function(df) {
  df %>%
    rename_with(~ str_remove(., "\\.1\\.$")) %>%
    rownames_to_column("stat") %>%
    pivot_longer(
      cols = -c(stat, Model),
      names_to = "param",
      values_to = "value"
    ) %>%
    pivot_wider(
      names_from = stat,
      values_from = value
    ) %>%
    mutate(
      value = if_else(
        param == "b",
        str_c(
          formatC(Result_mode, format = "e", digits = 2),
          " [", formatC(`2.5%`, format = "e", digits = 2),
          " ; ", formatC(`97.5%`, format = "e", digits = 2), "]"
        ),
        str_c(
          round(Result_mode, 3),
          " [", round(`2.5%`, 3),
          " ; ", round(`97.5%`, 3), "]"
        )
      )
    ) %>%
    dplyr::select(Model, param, value) %>%
    pivot_wider(
      names_from = param,
      values_from = value
    )
}

df_result <- list_model_summary %>%
  map(format_summary) %>%
  bind_rows() %>%
  dplyr::select(
    Model,
    any_of(param_order),
    everything()
  ) |> 
  left_join(df_LL_BIC) |> 
  arrange(BIC)

df_result |> datatable(
  options = list(
    dom = 't',
    autoWidth = TRUE,
    columnDefs = list(
      list(className = 'dt-left', targets = "_all")
      )
    ),
  class="hover"
  )
```

### Chains

::: panel-tabset
## A_EPX_A

```{r, echo=F, message=F, warning=F}
#| fig-cap: Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.
#| label: fig-chains_A_EPX_A
#| fig-height: 8
#| fig-width: 8

p_chains <-  
  ggplot(
    data = MCMC_out_A_EPX_A$Chains |> 
      filter(Iteration !=1), 
    aes(
      x = Iteration, 
      y = value, 
      color = as.factor(Chain), 
      group = as.factor(Chain)
      )
  )+
  geom_line(alpha=0.7)+
  scale_y_log10()+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  
  scale_color_manual(name = "Chains", values = pal_chains)+
  
  theme_bw()+
  theme(
    legend.position = "right", 
    title=element_text(size=12, face="plain"), 
    axis.title.x = element_text(face="plain"),
    strip.background = element_rect(fill="white")
    )

p_chains
  
```

```{r savechainsA_EPX_A, include = F}
ggsave(
  filename="A_EPX_A_chains.png", 
  plot=p_chains, 
  width=8, height = 8, 
  path=path_fig
  )
```

## B_EPX_M

```{r, echo=F, message=F, warning=F}
#| fig-cap: Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.
#| label: fig-chains_B_EPX_M
#| fig-height: 8
#| fig-width: 8

p_chains <-  
  ggplot(
    data = MCMC_out_B_EPX_M$Chains |> 
      filter(Iteration !=1), 
    aes(
      x = Iteration, 
      y = value, 
      color = as.factor(Chain), 
      group = as.factor(Chain)
      )
  )+
  geom_line(alpha=0.7)+
 # scale_y_log10()+
  scale_x_continuous(limits = c(0,2500))+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  
  scale_color_manual(name = "Chains", values = pal_chains)+
  
  theme_bw()+
  theme(
    legend.position = "right", 
    title=element_text(size=12, face="plain"), 
    axis.title.x = element_text(face="plain"),
    strip.background = element_rect(fill="white")
    )

p_chains
  
```

```{r savechainsB_EPX_M, include = F}
ggsave(
  filename="B_EPX_M_chains.png", 
  plot=p_chains, 
  width=8, height = 8, 
  path=path_fig
  )
```

## C_EPX_G

```{r, echo=F, message=F, warning=F}
#| fig-cap: Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.
#| label: fig-chains_C_EPX_G
#| fig-height: 8
#| fig-width: 8

p_chains <-  
  ggplot(
    data = MCMC_out_C_EPX_G$Chains |> 
      filter(Iteration !=1), 
    aes(
      x = Iteration, 
      y = value, 
      color = as.factor(Chain), 
      group = as.factor(Chain)
      )
  )+
  geom_line(alpha=0.7)+
 # scale_y_log10()+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  
  scale_color_manual(name = "Chains", values = pal_chains)+
  
  theme_bw()+
  theme(
    legend.position = "right", 
    title=element_text(size=12, face="plain"), 
    axis.title.x = element_text(face="plain"),
    strip.background = element_rect(fill="white")
    )

p_chains
  
```

```{r savechainsC_EPX_G, include = F}
ggsave(
  filename="C_EPX_G_chains.png", 
  plot=p_chains, 
  width=8, height = 8, 
  path=path_fig
  )
```

## D_EPX_R

```{r, echo=F, message=F, warning=F}
#| fig-cap: Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.
#| label: fig-chains_D_EPX_R
#| fig-height: 8
#| fig-width: 8

p_chains <-  
  ggplot(
    data = MCMC_out_D_EPX_R$Chains |> 
      filter(Iteration !=1), 
    aes(
      x = Iteration, 
      y = value, 
      color = as.factor(Chain), 
      group = as.factor(Chain)
      )
  )+
  geom_line(alpha=0.7)+
  scale_y_log10()+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  
  scale_color_manual(name = "Chains", values = pal_chains)+
  
  theme_bw()+
  theme(
    legend.position = "right", 
    title=element_text(size=12, face="plain"), 
    axis.title.x = element_text(face="plain"),
    strip.background = element_rect(fill="white")
    )

p_chains
  
```

```{r savechainsD_EPX_R, include = F}
ggsave(
  filename="D_EPX_R_chains.png", 
  plot=p_chains, 
  width=8, height = 8, 
  path=path_fig
  )
```

## E_EPX_AM

```{r, echo=F, message=F, warning=F}
#| fig-cap: Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.
#| label: fig-chains_E_EPX_AM
#| fig-height: 8
#| fig-width: 8

p_chains <-  
  ggplot(
    data = MCMC_out_E_EPX_AM$Chains |> 
      filter(Iteration !=1), 
    aes(
      x = Iteration, 
      y = value, 
      color = as.factor(Chain), 
      group = as.factor(Chain)
      )
  )+
  geom_line(alpha=0.7)+
  scale_y_log10()+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  
  scale_color_manual(name = "Chains", values = pal_chains)+
  
  theme_bw()+
  theme(
    legend.position = "right", 
    title=element_text(size=12, face="plain"), 
    axis.title.x = element_text(face="plain"),
    strip.background = element_rect(fill="white")
    )

p_chains
  
```

```{r savechainsE_EPX_AM, include = F}
ggsave(
  filename="E_EPX_AM_chains.png", 
  plot=p_chains, 
  width=8, height = 8, 
  path=path_fig
  )
```

## F_EPX_AG

```{r, echo=F, message=F, warning=F}
#| fig-cap: Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.
#| label: fig-chains_F_EPX_AG
#| fig-height: 8
#| fig-width: 8

p_chains <-  
  ggplot(
    data = MCMC_out_F_EPX_AG$Chains |> 
      filter(Iteration !=1), 
    aes(
      x = Iteration, 
      y = value, 
      color = as.factor(Chain), 
      group = as.factor(Chain)
      )
  )+
  geom_line(alpha=0.7)+
  scale_y_log10()+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  
  scale_color_manual(name = "Chains", values = pal_chains)+
  
  theme_bw()+
  theme(
    legend.position = "right", 
    title=element_text(size=12, face="plain"), 
    axis.title.x = element_text(face="plain"),
    strip.background = element_rect(fill="white")
    )

p_chains
  
```

```{r savechainsF_EPX_AG, include = F}
ggsave(
  filename="F_EPX_AG_chains.png", 
  plot=p_chains, 
  width=8, height = 8, 
  path=path_fig
  )
```

## G_EPX_AR

```{r, echo=F, message=F, warning=F}
#| fig-cap: Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.
#| label: fig-chains_G_EPX_AR
#| fig-height: 8
#| fig-width: 8

p_chains <-  
  ggplot(
    data = MCMC_out_G_EPX_AR$Chains |> 
      filter(Iteration !=1), 
    aes(
      x = Iteration, 
      y = value, 
      color = as.factor(Chain), 
      group = as.factor(Chain)
      )
  )+
  geom_line(alpha=0.7)+
  scale_y_log10()+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  
  scale_color_manual(name = "Chains", values = pal_chains)+
  
  theme_bw()+
  theme(
    legend.position = "right", 
    title=element_text(size=12, face="plain"), 
    axis.title.x = element_text(face="plain"),
    strip.background = element_rect(fill="white")
    )

p_chains
  
```

```{r savechainsG_EPX_AR, include = F}
ggsave(
  filename="G_EPX_AR_chains.png", 
  plot=p_chains, 
  width=8, height = 8, 
  path=path_fig
  )
```

## H_EPX_MG

```{r, echo=F, message=F, warning=F}
#| fig-cap: Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.
#| label: fig-chains_H_EPX_MG
#| fig-height: 8
#| fig-width: 8

p_chains <-  
  ggplot(
    data = MCMC_out_H_EPX_MG$Chains |> 
      filter(Iteration !=1), 
    aes(
      x = Iteration, 
      y = value, 
      color = as.factor(Chain), 
      group = as.factor(Chain)
      )
  )+
  geom_line(alpha=0.7)+
  scale_y_log10()+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  
  scale_color_manual(name = "Chains", values = pal_chains)+
  
  theme_bw()+
  theme(
    legend.position = "right", 
    title=element_text(size=12, face="plain"), 
    axis.title.x = element_text(face="plain"),
    strip.background = element_rect(fill="white")
    )

p_chains
  
```

```{r savechainsH_EPX_MG, include = F}
ggsave(
  filename="H_EPX_MG_chains.png", 
  plot=p_chains, 
  width=8, height = 8, 
  path=path_fig
  )
```

## I_EPX_MR

```{r, echo=F, message=F, warning=F}
#| fig-cap: Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.
#| label: fig-chains_I_EPX_MR
#| fig-height: 8
#| fig-width: 8

p_chains <-  
  ggplot(
    data = MCMC_out_I_EPX_MR$Chains |> 
      filter(Iteration !=1), 
    aes(
      x = Iteration, 
      y = value, 
      color = as.factor(Chain), 
      group = as.factor(Chain)
      )
  )+
  geom_line(alpha=0.7)+
  scale_y_log10()+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  
  scale_color_manual(name = "Chains", values = pal_chains)+
  
  theme_bw()+
  theme(
    legend.position = "right", 
    title=element_text(size=12, face="plain"), 
    axis.title.x = element_text(face="plain"),
    strip.background = element_rect(fill="white")
    )

p_chains
  
```

```{r savechainsI_EPX_MR, include = F}
ggsave(
  filename="I_EPX_MR_chains.png", 
  plot=p_chains, 
  width=8, height = 8, 
  path=path_fig
  )
```

## J_EPX_GR

```{r, echo=F, message=F, warning=F}
#| fig-cap: Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.
#| label: fig-chains_J_EPX_GR
#| fig-height: 8
#| fig-width: 8

p_chains <-  
  ggplot(
    data = MCMC_out_J_EPX_GR$Chains |> 
      filter(Iteration !=1), 
    aes(
      x = Iteration, 
      y = value, 
      color = as.factor(Chain), 
      group = as.factor(Chain)
      )
  )+
  geom_line(alpha=0.7)+
  scale_y_log10()+
  facet_wrap(~Parameter, scales = "free", ncol = 2)+
  
  scale_color_manual(name = "Chains", values = pal_chains)+
  
  theme_bw()+
  theme(
    legend.position = "right", 
    title=element_text(size=12, face="plain"), 
    axis.title.x = element_text(face="plain"),
    strip.background = element_rect(fill="white")
    )

p_chains
  
```

```{r savechainsJ_EPX_GR, include = F}
ggsave(
  filename="J_EPX_GR_chains.png", 
  plot=p_chains, 
  width=8, height = 8, 
  path=path_fig
  )
```
:::

### Likelihood

::: panel-tabset
## A_EPX_A

```{r, message=F, warning=F, echo=F}
#| fig-cap: Evolution of likelihood and deviance ratio through the iterations.
#| label: fig-like_A_EPX_A
#| fig-height: 8
#| fig-width: 8

p1 <- ggplot(
  MCMC_out_A_EPX_A$df_LnPost_start |> 
      filter(iteration !=1), 
  aes(
    x = iteration, 
    y = LnPosterior, 
    color = Chain
    )
  ) +
  geom_line() +
  scale_color_manual(name = "Chains", label = lab_chains, values = pal_chains) +
  labs(
    x = "First half iterations", 
    y = "LnPosterior"
    ) +
  theme_minimal()

p2 <- ggplot(
  MCMC_out_A_EPX_A$df_LnPost |> 
      filter(iteration !=1), 
  aes(
    x = iteration, 
    y = LnPosterior, 
    color = Chain
    )
  ) +
  geom_line() +
  scale_color_manual(name = "Chains", label = lab_chains, values = pal_chains) +
  labs(
    x = paste(MCMC_out_A_EPX_A$Nb_iter_kept, "last iterations"), 
    y = "LnPosterior"
    ) +
  theme_minimal()

p3 <- ggplot(
  MCMC_out_A_EPX_A$df_Devc |> 
      filter(iteration !=1), 
  aes(
    x = iteration, 
    y = RatioDeviance, 
    color = Chain
    )
  ) +
  geom_line() +
  scale_color_manual(name = "Chains", label = lab_chains, values = pal_chains) +
  labs(
    x = paste(MCMC_out_A_EPX_A$Nb_iter_kept, "last iterations"), 
    y = "Ratio Deviance"
    ) +
  theme_minimal()

p_LL <- p1 + p2 + p3 +
  plot_layout(ncol=3, guides = "collect")
p_LL

```

```{r saveLLA_EPX_A, include = F}
ggsave(
  filename="A_EPX_A_chainsLL.png", 
  plot=p_LL, 
  width=8, height = 4, 
  path=path_fig
  )
```

## F_EPX_AG

```{r, message=F, warning=F, echo=F}
#| fig-cap: Evolution of likelihood and deviance ratio through the iterations.
#| label: fig-like_F_EPX_AG
#| fig-height: 8
#| fig-width: 8

p1 <- ggplot(
  MCMC_out_F_EPX_AG$df_LnPost_start |> 
      filter(iteration !=1), 
  aes(
    x = iteration, 
    y = LnPosterior, 
    color = Chain
    )
  ) +
  geom_line() +
  scale_color_manual(name = "Chains", label = lab_chains, values = pal_chains) +
  labs(
    x = "First half iterations", 
    y = "LnPosterior"
    ) +
  theme_minimal()

p2 <- ggplot(
  MCMC_out_F_EPX_AG$df_LnPost |> 
      filter(iteration !=1), 
  aes(
    x = iteration, 
    y = LnPosterior, 
    color = Chain
    )
  ) +
  geom_line() +
  scale_color_manual(name = "Chains", label = lab_chains, values = pal_chains) +
  labs(
    x = paste(MCMC_out_F_EPX_AG$Nb_iter_kept, "last iterations"), 
    y = "LnPosterior"
    ) +
  theme_minimal()

p3 <- ggplot(
  MCMC_out_F_EPX_AG$df_Devc |> 
      filter(iteration !=1), 
  aes(
    x = iteration, 
    y = RatioDeviance, 
    color = Chain
    )
  ) +
  geom_line() +
  scale_color_manual(name = "Chains", label = lab_chains, values = pal_chains) +
  labs(
    x = paste(MCMC_out_F_EPX_AG$Nb_iter_kept, "last iterations"), 
    y = "Ratio Deviance"
    ) +
  theme_minimal()

p_LL <- p1 + p2 + p3 +
  plot_layout(ncol=3, guides = "collect")
p_LL

```

```{r saveLLF_EPX_AG, include = F}
ggsave(
  filename="F_EPX_AG_chainsLL.png", 
  plot=p_LL, 
  width=8, height = 4, 
  path=path_fig
  )
```
:::

### Posterior distributions

::: panel-tabset
## A_EPX_A

```{r, echo=F, message=F, warning=F}
#| fig-cap: Distributions of the priors and the posteriors.
#| label: fig-post_A_EPX_A
#| fig-height: 8
#| fig-width: 8

n_samples <- 1e5 # Simulation of the distribution

df_priors_dist <- MCMC_out_A_EPX_A$Priors |> 
  dplyr::select(Nom, Distribution, P1, P2, P3, P4) |> 
  rowwise() |> 
  mutate(samples = case_when(
    Distribution == "Uniform" ~ list(runif(n_samples, min = P1, max = P2)),
    Distribution == "Normal" ~ list(rnorm(n_samples, mean = P1, sd = P2)),
    Distribution == "LogUniform" ~ list(exp(runif(n_samples, min = log(P1), max = log(P2)))),
    Distribution == "TruncNormal" ~ list(rtruncnorm(n_samples, a = P3, b = P4, mean = P1, sd = P2)),     Distribution == "TruncNormal_cv" ~ list(rtruncnorm(n_samples, a = P3, b = P4, mean = P1, sd = P2*P1))
  )) |> 
  unnest(samples)

alpha_prior <- 0.5
alpha_post <- 0.5
col_prior <- Nord_snow[1]
col_post <- col_IMD

MCMC_out_A_EPX_A$Chains_plot <- MCMC_out_A_EPX_A$Chains |> 
  mutate(Nom = str_remove(Parameter, "\\.\\d+\\.$")) 

p_post <- ggplot() +
  
  # Priors
  stat_halfeye(
    data = df_priors_dist,
    aes(
       x = samples,
       ),
    alpha = alpha_prior,
    fill = col_prior,
    color = col_prior,
    normalize = "xy"
    ) +
  
  # Posterior
  stat_halfeye(
    data = subset(MCMC_out_A_EPX_A$Chains_plot, Nom %in% L_parameters_A_EPX_A),
    mapping = aes(
      x=value
    ),
    fill = col_post,
    color = col_post,
    alpha = alpha_post,
    normalize = "xy"
  ) +
  
  facet_wrap(~Nom, scales = "free")+
  scale_x_log10()+
  labs(
    title = "Posterior and prior distributions", 
    x = "Parameter value", 
    y = "Density"
    ) +
  theme_minimal()+
  theme(
    title=element_text(face="bold")
  )

p_post
```

```{r savepostA_EPX_A, include = F}
ggsave(
  filename="A_EPX_A_post.png", 
  plot=p_post, 
  width=8, height = 8, 
  path=path_fig
  )
```

## F_EPX_AG

```{r, echo=F, message=F, warning=F}
#| fig-cap: Distributions of the priors and the posteriors.
#| label: fig-post_F_EPX_AG
#| fig-height: 8
#| fig-width: 8

n_samples <- 1e5 # Simulation of the distribution

df_priors_dist <- MCMC_out_F_EPX_AG$Priors |> 
  dplyr::select(Nom, Distribution, P1, P2, P3, P4) |> 
  rowwise() |> 
  mutate(samples = case_when(
    Distribution == "Uniform" ~ list(runif(n_samples, min = P1, max = P2)),
    Distribution == "Normal" ~ list(rnorm(n_samples, mean = P1, sd = P2)),
    Distribution == "LogUniform" ~ list(exp(runif(n_samples, min = log(P1), max = log(P2)))),
    Distribution == "TruncNormal" ~ list(rtruncnorm(n_samples, a = P3, b = P4, mean = P1, sd = P2)),     Distribution == "TruncNormal_cv" ~ list(rtruncnorm(n_samples, a = P3, b = P4, mean = P1, sd = P2*P1))
  )) |> 
  unnest(samples)

alpha_prior <- 0.5
alpha_post <- 0.5
col_prior <- Nord_snow[1]
col_post <- col_IMD

MCMC_out_F_EPX_AG$Chains_plot <- MCMC_out_F_EPX_AG$Chains |> 
  mutate(Nom = str_remove(Parameter, "\\.\\d+\\.$")) 

p_post <- ggplot() +
  
  # Priors
  stat_halfeye(
    data = df_priors_dist,
    aes(
       x = samples,
       ),
    alpha = alpha_prior,
    fill = col_prior,
    color = col_prior,
    normalize = "xy"
    ) +
  
  # Posterior
  stat_halfeye(
    data = subset(MCMC_out_F_EPX_AG$Chains_plot, Nom %in% L_parameters_F_EPX_AG),
    mapping = aes(
      x=value
    ),
    fill = col_post,
    color = col_post,
    alpha = alpha_post,
    normalize = "xy"
  ) +
  
  facet_wrap(~Nom, scales = "free")+
  labs(
    title = "Posterior and prior distributions", 
    x = "Parameter value", 
    y = "Density"
    ) +
  theme_minimal()+
  theme(
    title=element_text(face="bold")
  )

p_post
```

```{r savepostF_EPX_AG, include = F}
ggsave(
  filename="F_EPX_AG_post.png", 
  plot=p_post, 
  width=8, height = 8, 
  path=path_fig
  )
```
:::

### Predicted vs. Obs

```{r}
l_param_name_A_EPX_A <- names(Summary_res_A_EPX_A) |>
  head(-1) |>
  stringr::str_remove_all("\\.1\\.") 

f_In_predobs_TKTD(path_A_EPX_A, Molec, l_param_name_A_EPX_A)

l_param_name_F_EPX_AG <- names(Summary_res_F_EPX_AG) |>
  head(-1) |>
  stringr::str_remove_all("\\.1\\.") 

f_In_predobs_TKTD(path_F_EPX_AG, Molec, l_param_name_F_EPX_AG)

```

```{bash, eval=F, execute=F}
for j in $(seq 1 18); do
./mcsim.DEB-EPX DEB_setpoint_predobs_${j}.in
done
```

```{r, results=F, message=F, warning=F}

Nb_experiment <- 18

df_data_obs_EPX <- df_data_fit_EPX |> 
  mutate(
    Weight_obs = Weight,
    Reproduction_obs = Reproduction
    ) |> 
  dplyr::select(-c(Weight, Reproduction))

######## A_EPX_A ###############################################################

df_pred_A_EPX_A <- f_read_predobs(path_A_EPX_A, Nb_experiment, df_data_obs_EPX)

df_pred_Weight_A_EPX_A <- subset(df_pred_A_EPX_A, Endpt == "Weight" & Time !=0)
df_pred_Reproduction_A_EPX_A <- subset(df_pred_A_EPX_A, Endpt == "Reproduction" & Time !=0)

df_predobs_Reproduction_A_EPX_A <- df_data_obs_EPX |> 
  filter(Time !=0) |>
  left_join(df_pred_Reproduction_A_EPX_A, suffix = c("_obs", "_pred")) |> 
  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> 
  drop_na()

df_predobs_Weight_A_EPX_A <- df_data_obs_EPX |> 
  filter(Time !=0) |>
  left_join(df_pred_Weight_A_EPX_A, suffix = c("_obs", "_pred"))|>
  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> 
  drop_na()

######## F_EPX_AG ###############################################################

df_pred_F_EPX_AG <- f_read_predobs(path_F_EPX_AG, Nb_experiment, df_data_obs_EPX)

df_pred_Weight_F_EPX_AG <- subset(df_pred_F_EPX_AG, Endpt == "Weight" & Time !=0)
df_pred_Reproduction_F_EPX_AG <- subset(df_pred_F_EPX_AG, Endpt == "Reproduction" & Time !=0)

df_predobs_Reproduction_F_EPX_AG <- df_data_obs_EPX |> 
  filter(Time !=0) |>
  left_join(df_pred_Reproduction_F_EPX_AG, suffix = c("_obs", "_pred")) |> 
  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> 
  drop_na()

df_predobs_Weight_F_EPX_AG <- df_data_obs_EPX |> 
  filter(Time !=0) |>
  left_join(df_pred_Weight_F_EPX_AG, suffix = c("_obs", "_pred"))|>
  mutate(across(everything(), ~replace(.x, .x == -1, NA))) |> 
  drop_na()

```

::: panel-tabset
## A_EPX_A

```{r, message=F, warning=F}
#| fig-cap: Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line. 
#| label: fig-predobs_A_EPX_A
#| fig-height: 4
#| fig-width: 8

fact_1 <- 2
fact_2 <- 5

col_line0 <- Nord_polar[1]
col_line1 <- Nord_polar[4]
col_line2 <- Nord_snow[1]

col_exp1 <- c(
  rev(nord("aurora", 12)[1:8]),
  Nord_aurora[4]
)

col_experiment <- rep(col_exp1, 2)

seq_line <- seq(0.05, 1.5, 0.01)

df_line <- data.frame(
  x1  = seq_line,
  y1  = seq_line*fact_1,
  x_1 = seq_line,
  y_1 = seq_line/fact_1,
  x2  = seq_line,
  y2  = seq_line*fact_2,
  x_2 = seq_line,
  y_2 = seq_line/fact_2
  )

p_W <- ggplot(
  data = df_predobs_Weight_A_EPX_A,
  mapping = aes(
      x = Weight_obs,
      y = predict.endpoint
    )
  )+
  geom_line(
    data=df_line,
    mapping=aes(x=x1, y=y1),
    color = col_line1
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x_1, y=y_1),
    color = col_line1
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x2, y=y2),
    color = col_line2
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x_2, y=y_2),
    color = col_line2
    )+
  
  geom_abline(
    slope=1, 
    intercept = 0, 
    color = col_line0,
    linewidth = 1
    )+
  geom_pointrange(
    mapping = aes(
      ymin = low,
      ymax = up,
    color = Condition
    ),
    alpha = 0.5
  )+
  scale_x_log10(
    labels = scales::label_number()
    )+
  scale_y_log10(
    labels = scales::label_number()
    )+
  scale_color_manual(
    name = "Experiments",
    values = col_experiment
    )+
  labs(
    x = "Observed weight of earthworms (g)",
    y = "Predicted weight of earthworms (g)"
  )+
  theme_minimal()

fact_1 <- 2
fact_2 <- 5

seq_line <- seq(5, 30, 0.1)

df_line <- data.frame(
  x1  = seq_line,
  y1  = seq_line*fact_1,
  x_1 = seq_line,
  y_1 = seq_line/fact_1,
  x2  = seq_line,
  y2  = seq_line*fact_2,
  x_2 = seq_line,
  y_2 = seq_line/fact_2
  )

p_R <- ggplot(
  data = df_predobs_Reproduction_A_EPX_A,
  mapping = aes(
      x = Reproduction_obs,
      y = predict.endpoint
    )
  )+
  geom_path(
    data=df_line,
    mapping=aes(x=x1, y=y1),
    color = col_line1
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x_1, y=y_1),
    color = col_line1
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x2, y=y2),
    color = col_line2
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x_2, y=y_2),
    color = col_line2
    )+
  geom_abline(
    slope=1, 
    intercept = 0, 
    color = col_line0,
    linewidth = 1
    )+
  geom_pointrange(
    mapping = aes(
      ymin = low,
      ymax = up,
      color = Condition
    ),
    alpha = 0.5
  )+
  labs(
    x = "Observed reproduction (#)",
    y = "Predicted reproduction (#)"
  )+
  scale_color_manual(
    name = "Experiments",
    values = col_experiment
    )+
  scale_x_log10(
   labels = scales::label_number()
    )+
  scale_y_log10(
   labels = scales::label_number()
    )+
  theme_minimal()

p_predobs <- p_W + p_R +plot_layout(guides="collect") +
  plot_annotation(tag_levels = "A")

p_predobs

```

```{r savepredobsA_EPX_A, include = F}

ggsave(
  filename = "A_EPX_A_predobs.png",
  plot = p_predobs,
  width = 8, height = 4,
  path = path_fig
) 
```

## F_EPX_AG

```{r, message=F, warning=F}
#| fig-cap: Results of the model fit on experimental data. Predicted values are represented with points with their respective credibility interval of 95%. Thin black and grey lines represent the 2-folds and 5-fold changes, respectively. The thicker black line represents the identity line. 
#| label: fig-predobs_F_EPX_AG
#| fig-height: 4
#| fig-width: 8

fact_1 <- 2
fact_2 <- 5

col_line0 <- Nord_polar[1]
col_line1 <- Nord_polar[4]
col_line2 <- Nord_snow[1]

col_exp1 <- c(
  rev(nord("aurora", 12)[1:8]),
  Nord_aurora[4]
)

col_experiment <- rep(col_exp1, 2)

seq_line <- seq(0.05, 1.5, 0.01)

df_line <- data.frame(
  x1  = seq_line,
  y1  = seq_line*fact_1,
  x_1 = seq_line,
  y_1 = seq_line/fact_1,
  x2  = seq_line,
  y2  = seq_line*fact_2,
  x_2 = seq_line,
  y_2 = seq_line/fact_2
  )

p_W <- ggplot(
  data = df_predobs_Weight_F_EPX_AG,
  mapping = aes(
      x = Weight_obs,
      y = predict.endpoint
    )
  )+
  geom_line(
    data=df_line,
    mapping=aes(x=x1, y=y1),
    color = col_line1
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x_1, y=y_1),
    color = col_line1
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x2, y=y2),
    color = col_line2
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x_2, y=y_2),
    color = col_line2
    )+
  
  geom_abline(
    slope=1, 
    intercept = 0, 
    color = col_line0,
    linewidth = 1
    )+
  geom_pointrange(
    mapping = aes(
      ymin = low,
      ymax = up,
    color = Condition
    ),
    alpha = 0.5
  )+
  scale_x_log10(
    labels = scales::label_number()
    )+
  scale_y_log10(
    labels = scales::label_number()
    )+
  scale_color_manual(
    name = "Experiments",
    values = col_experiment
    )+
  labs(
    x = "Observed weight of earthworms (g)",
    y = "Predicted weight of earthworms (g)"
  )+
  theme_minimal()

fact_1 <- 2
fact_2 <- 5

seq_line <- seq(5, 30, 0.1)

df_line <- data.frame(
  x1  = seq_line,
  y1  = seq_line*fact_1,
  x_1 = seq_line,
  y_1 = seq_line/fact_1,
  x2  = seq_line,
  y2  = seq_line*fact_2,
  x_2 = seq_line,
  y_2 = seq_line/fact_2
  )

p_R <- ggplot(
  data = df_predobs_Reproduction_F_EPX_AG,
  mapping = aes(
      x = Reproduction_obs,
      y = predict.endpoint
    )
  )+
  geom_path(
    data=df_line,
    mapping=aes(x=x1, y=y1),
    color = col_line1
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x_1, y=y_1),
    color = col_line1
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x2, y=y2),
    color = col_line2
    )+
  geom_line(
    data=df_line,
    mapping=aes(x=x_2, y=y_2),
    color = col_line2
    )+
  geom_abline(
    slope=1, 
    intercept = 0, 
    color = col_line0,
    linewidth = 1
    )+
  geom_pointrange(
    mapping = aes(
      ymin = low,
      ymax = up,
      color = Condition
    ),
    alpha = 0.5
  )+
  labs(
    x = "Observed reproduction (#)",
    y = "Predicted reproduction (#)"
  )+
  scale_color_manual(
    name = "Experiments",
    values = col_experiment
    )+
  scale_x_log10(
   labels = scales::label_number()
    )+
  scale_y_log10(
   labels = scales::label_number()
    )+
  theme_minimal()

p_predobs <- p_W + p_R +plot_layout(guides="collect") +
  plot_annotation(tag_levels = "A")

p_predobs

```

```{r savepredobsF_EPX_AG, include = F}

ggsave(
  filename = "F_EPX_AG_predobs.png",
  plot = p_predobs,
  width = 8, height = 4,
  path = path_fig
) 
```
:::

### Predicted trajectories for Weight and Reproduction

```{r setpointfullin}

Nb_experiment <- 18
step_sim <- 0.05
select_times <- seq(0,400, 0.1)

Endpoints_print <- "Weight,
    Reproduction"


l_param_name_A_EPX_A <- names(Summary_res_A_EPX_A) |>
  head(-1) |>
  stringr::str_remove_all("\\.1\\.")

f_In_Setpoint_full_TKTD(
  path_A_EPX_A, Molec, 
  l_param_name_A_EPX_A, step_sim, Endpoints_print
  )


l_param_name_F_EPX_AG <- names(Summary_res_F_EPX_AG) |>
  head(-1) |>
  stringr::str_remove_all("\\.1\\.")

f_In_Setpoint_full_TKTD(
  path_F_EPX_AG, Molec, 
  l_param_name_F_EPX_AG, step_sim, Endpoints_print
  )

```

```{bash, eval=F, execute=F}
for j in $(seq 1 18); do
./mcsim.DEB-EPX DEB_setpoint_full_${j}.in
done
```

```{r, message = F, warning = F}

width_plot <- 12
height_plot <- 12

file_rds_A_EPX_A <- file.path(path_A_EPX_A, paste0("Sim.Res.Exp.full.rds"))

if (file.exists(file_rds_A_EPX_A)) {
  df_pred_full_A_EPX_A <- readRDS(file_rds_A_EPX_A)
} else {
  df_pred_full_A_EPX_A <- f_read_Setpoint_full_TKTD(path_A_EPX_A, Molec, select_times, step_sim)
}

file_rds_F_EPX_AG <- file.path(path_F_EPX_AG, paste0("Sim.Res.Exp.full.rds"))

if (file.exists(file_rds_F_EPX_AG)) {
  df_pred_full_F_EPX_AG <- readRDS(file_rds_F_EPX_AG)
} else {
  df_pred_full_F_EPX_AG <- f_read_Setpoint_full_TKTD(path_F_EPX_AG, Molec, select_times, step_sim)
}

```

::: panel-tabset
## A_EPX_A

```{r, echo=F, message=F, warning=F}
#| fig-cap: Predicted Weight and Reproduction for each experiment.
#| label: fig-pred_A_EPX_A
#| fig-height: 18
#| fig-width: 12

# Plot
  alpha_ribbon <- 0.15
  line_width <- 1.1
  point_stroke <- 0.9
  alpha_line <- 0.7
  wrap_nb_col <- 2
  
col_exp1 <- c(
  rev(nord("aurora", 12)[1:8]),
  Nord_aurora[4]
)

col_experiment <- rep(col_exp1, 2)
  
  pW <- ggplot()+
    
    geom_ribbon(
      data = subset(df_pred_full_A_EPX_A, Endpt == "Weight"),
      aes(
        x = Time,
        ymax = up,
        ymin = low,
        fill = ID_experiment
      ),
      alpha = alpha_ribbon
    )+
    
    geom_line(
      data = subset(df_pred_full_A_EPX_A, Endpt == "Weight"),
      aes(
        x = Time,
        y = predict.endpoint,
        color = ID_experiment
      ),
      linewidth = line_width,
      alpha = alpha_line
    )+
    
    geom_point(
      data = df_data_obs_EPX,    
      mapping = 
        aes(  
          x = Time, 
          y = Weight_obs, 
          color = ID_experiment  
        ),
      alpha = 0.7,
      stroke = point_stroke
    )+
    
    scale_color_manual(
      name = "Experiments",
      values = col_experiment
      )+
    scale_fill_manual(
      name = "Experiments",
      values = col_experiment
      )+
    facet_wrap(
      ~ID_experiment,
      ncol = wrap_nb_col
      )+
    scale_y_continuous(limits = c(0, 1.1))+
    labs(
      x="Time (days)", 
      y = "Weight (g)",
      title ="Earthworm growth"
    )+
    theme_minimal()+
  theme(
    plot.title = element_text(face = "bold")
  )
  
  pR <- ggplot()+
    
    geom_ribbon(
      data = subset(df_pred_full_A_EPX_A, Endpt == "Reproduction"),
      aes(
        x = Time,
        ymax = up,
        ymin = low,
        fill = ID_experiment
      ),
      alpha = alpha_ribbon
    )+
    
    geom_line(
      data = subset(df_pred_full_A_EPX_A, Endpt == "Reproduction"),
      aes(
        x = Time,
        y = predict.endpoint,
        color = ID_experiment
      ),
      linewidth = line_width,
      alpha = alpha_line
    )+
    
    geom_point(
      data = df_data_obs_EPX,    
      mapping = 
        aes(  
          x = Time, 
          y = Reproduction_obs, 
          color = ID_experiment  
        ),
      alpha = 0.8,
      stroke = point_stroke
    )+
    
    scale_color_manual(
      name = "Experiments",
      values = col_experiment
      )+
    scale_fill_manual(
      name = "Experiments",
      values = col_experiment
      )+
    facet_wrap(
      ~ID_experiment, 
      ncol=wrap_nb_col
      )+
    scale_y_continuous(limits = c(0, 20))+
    labs(
      x="Time (days)", 
      y = "Reproduction (#)",
      title ="Earthworm reproduction"
    )+
    theme_minimal()+
  theme(
    plot.title = element_text(face = "bold")
  )
  
  

pA <- pW + pR +
  plot_layout(guides = "collect") &
  guides(color = guide_legend("Experiments")) &
  theme(legend.position = "none")

pA
```

```{r savetrajWRA_EPX_A, include = F}
ggsave(
  filename="A_EPX_A_trajWR.png", 
  plot=pA, 
  width=width_plot, height = height_plot, 
  path=path_fig
  )
```

## F_EPX_AG

```{r, echo=F, message=F, warning=F}
#| fig-cap: Predicted Weight and Reproduction for each experiment.
#| label: fig-pred_F_EPX_AG
#| fig-height: 18
#| fig-width: 12

# Plot
  alpha_ribbon <- 0.15
  line_width <- 1.1
  point_stroke <- 0.9
  alpha_line <- 0.7
  wrap_nb_col <- 2
  
col_exp1 <- c(
  rev(nord("aurora", 12)[1:8]),
  Nord_aurora[4]
)

col_experiment <- rep(col_exp1, 2)
  
  pW <- ggplot()+
    
    geom_ribbon(
      data = subset(df_pred_full_F_EPX_AG, Endpt == "Weight"),
      aes(
        x = Time,
        ymax = up,
        ymin = low,
        fill = ID_experiment
      ),
      alpha = alpha_ribbon
    )+
    
    geom_line(
      data = subset(df_pred_full_F_EPX_AG, Endpt == "Weight"),
      aes(
        x = Time,
        y = predict.endpoint,
        color = ID_experiment
      ),
      linewidth = line_width,
      alpha = alpha_line
    )+
    
    geom_point(
      data = df_data_obs_EPX,    
      mapping = 
        aes(  
          x = Time, 
          y = Weight_obs, 
          color = ID_experiment  
        ),
      alpha = 0.7,
      stroke = point_stroke
    )+
    
    scale_color_manual(
      name = "Experiments",
      values = col_experiment
      )+
    scale_fill_manual(
      name = "Experiments",
      values = col_experiment
      )+
    facet_wrap(
      ~ID_experiment,
      ncol = wrap_nb_col
      )+
    scale_y_continuous(limits = c(0, 1.1))+
    labs(
      x="Time (days)", 
      y = "Weight (g)",
      title ="Earthworm growth"
    )+
    theme_minimal()+
  theme(
    plot.title = element_text(face = "bold")
  )
  
  pR <- ggplot()+
    
    geom_ribbon(
      data = subset(df_pred_full_F_EPX_AG, Endpt == "Reproduction"),
      aes(
        x = Time,
        ymax = up,
        ymin = low,
        fill = ID_experiment
      ),
      alpha = alpha_ribbon
    )+
    
    geom_line(
      data = subset(df_pred_full_F_EPX_AG, Endpt == "Reproduction"),
      aes(
        x = Time,
        y = predict.endpoint,
        color = ID_experiment
      ),
      linewidth = line_width,
      alpha = alpha_line
    )+
    
    geom_point(
      data = df_data_obs_EPX,    
      mapping = 
        aes(  
          x = Time, 
          y = Reproduction_obs, 
          color = ID_experiment  
        ),
      alpha = 0.8,
      stroke = point_stroke
    )+
    
    scale_color_manual(
      name = "Experiments",
      values = col_experiment
      )+
    scale_fill_manual(
      name = "Experiments",
      values = col_experiment
      )+
    facet_wrap(
      ~ID_experiment, 
      ncol=wrap_nb_col
      )+
    scale_y_continuous(limits = c(0, 20))+
    labs(
      x="Time (days)", 
      y = "Reproduction (#)",
      title ="Earthworm reproduction"
    )+
    theme_minimal()+
  theme(
    plot.title = element_text(face = "bold")
  )
  
  

pB <- pW + pR +
  plot_layout(guides = "collect") &
  guides(color = guide_legend("Experiments")) &
  theme(legend.position = "none")

pB
```

```{r savetrajWRF_EPX_AG, include = F}
ggsave(
  filename="F_EPX_AG_trajWR.png", 
  plot=pB, 
  width=width_plot, height = height_plot, 
  path=path_fig
  )
```
:::

## Summary

```{r}

Condition_order <- c(
  "Control", "C1", "C2", "C3", "C4", "C5",
  "C6", "C7", "C8"
)

df_Exp_type_Dose_Condition_G <- df_data_obs_EPX |> 
  filter(Experiment_type == "Growth") |> 
  dplyr::select(ID_experiment, Experiment_type, Dose, Condition) |> 
  distinct() |> 
  mutate(
    Condition = dplyr::recode(Condition, "Ctrl" = "Control"),
    Condition = factor(Condition, levels = Condition_order)
  )

df_Exp_type_Dose_Condition_R <- df_data_obs_EPX |> 
  filter(Experiment_type == "Repro") |> 
  dplyr::select(ID_experiment, Experiment_type, Dose, Condition) |> 
  distinct() |> 
  mutate(
    Condition = dplyr::recode(Condition, "Ctrl" = "Control"),
    Condition = factor(Condition, levels = Condition_order)
  )

ID_levels_growth <- df_Exp_type_Dose_Condition_G |> 
  filter(Experiment_type == "Growth") |> 
  arrange(Condition) |> 
  pull(ID_experiment)

Facet_levels_growth <- df_Exp_type_Dose_Condition_G |> 
  filter(Experiment_type == "Growth") |> 
  arrange(Condition) |> 
  mutate(Facet_label = paste(Condition, ":", Dose/1000, "mg/kg")) |> 
  pull(Facet_label)

ID_levels_repro <- df_Exp_type_Dose_Condition_R |> 
  filter(Experiment_type == "Repro") |> 
  arrange(Condition) |> 
  pull(ID_experiment)

Facet_levels_repro <- df_Exp_type_Dose_Condition_R |> 
  filter(Experiment_type == "Repro") |> 
  arrange(Condition) |> 
  mutate(Facet_label = paste(Condition, ":", Dose/1000, "mg/kg")) |> 
  pull(Facet_label)


df_pred_full_A_EPX_A_plot_G <- df_pred_full_A_EPX_A |> 
  left_join(
    df_Exp_type_Dose_Condition_G,
    by = c("ID_experiment")
  ) |> 
  mutate(
    ID_experiment = factor(ID_experiment, levels = ID_levels_growth),
    Facet_label = paste(Condition, ":", Dose/1000, "mg/kg"),
    Facet_label = factor(Facet_label, levels = Facet_levels_growth)
  )

df_data_obs_EPX_G <- df_data_obs_EPX |> 
  mutate(
    Condition = dplyr::recode(Condition, "Ctrl" = "Control"),
    Condition = factor(Condition, levels = Condition_order),
    ID_experiment = factor(ID_experiment, levels = ID_levels_growth),
    Facet_label = paste(Condition, ":", Dose/1000, "mg/kg"),
    Facet_label = factor(Facet_label, levels = Facet_levels_growth)
  )


df_pred_full_A_EPX_A_plot_R <- df_pred_full_A_EPX_A |> 
  left_join(
    df_Exp_type_Dose_Condition_R,
    by = c("ID_experiment")
  ) |> 
  filter(Experiment_type == "Repro") |> 
  mutate(
    ID_experiment = factor(ID_experiment, levels = ID_levels_repro),
    Facet_label = paste(Condition, ":", Dose/1000, "mg/kg"),
    Facet_label = factor(Facet_label, levels = Facet_levels_repro)
  )

df_data_obs_EPX_R <- df_data_obs_EPX |> 
  mutate(
    Condition = dplyr::recode(Condition, "Ctrl" = "Control"),
    Condition = factor(Condition, levels = Condition_order),
    ID_experiment = factor(ID_experiment, levels = ID_levels_repro),
    Facet_label = paste(Condition, ":", Dose/1000, "mg/kg"),
    Facet_label = factor(Facet_label, levels = Facet_levels_repro)
  )
  
```

```{r, echo=F, message=F, warning=F}
#| fig-cap: Predicted Weight and Reproduction for each experiment.
#| label: fig-pred_A_EPX_Asummary
#| fig-height: 18
#| fig-width: 12

# Plot
  alpha_ribbon <- 0.15
  line_width <- 1.1
  point_stroke <- 0.9
  alpha_line <- 0.7
  wrap_nb_col <- 2
  
col_exp1 <- c(
  Nord_aurora[4],
  rev(nord("aurora", 12)[1:10])
)

col_experiment <- rep(col_exp1, 2)
  
  pW_G <- ggplot()+

    geom_ribbon(
      data = subset(df_pred_full_A_EPX_A_plot_G, Endpt == "Weight" & Experiment_type == "Growth"),
      aes(
        x = Time,
        ymax = up,
        ymin = low,
        fill = ID_experiment
      ),
      alpha = alpha_ribbon
    )+
    
    geom_line(
      data = subset(df_pred_full_A_EPX_A_plot_G, Endpt == "Weight" & Experiment_type == "Growth"),
      aes(
        x = Time,
        y = predict.endpoint,
        color = ID_experiment
      ),
      linewidth = line_width,
      alpha = alpha_line
    )+
    
    geom_point(
      data = subset(df_data_obs_EPX_G, Experiment_type == "Growth"),    
      mapping = 
        aes(  
          x = Time, 
          y = Weight_obs, 
          color = ID_experiment  
        ),
      alpha = 0.7,
      stroke = point_stroke
    )+
    
    scale_color_manual(
      name = "Experiments",
      values = col_experiment
      )+
    scale_fill_manual(
      name = "Experiments",
      values = col_experiment
      )+
    facet_wrap(
      ~Facet_label,
      ncol = wrap_nb_col
      )+
    labs(
      x="Time (days)", 
      y = "Weight (g)",
      title ="Effect of imidacloprid on juvenile growth"
    )+
    theme_minimal()+
  theme(
    plot.title = element_text(face = "bold", size = 11),
    legend.position = "none"
  )
  
  pW_R <- ggplot()+

    geom_ribbon(
      data = subset(df_pred_full_A_EPX_A_plot_R, Endpt == "Weight" & Experiment_type == "Repro"),
      aes(
        x = Time,
        ymax = up,
        ymin = low,
        fill = ID_experiment
      ),
      alpha = alpha_ribbon
    )+
    
    geom_line(
      data = subset(df_pred_full_A_EPX_A_plot_R, Endpt == "Weight" & Experiment_type == "Repro"),
      aes(
        x = Time,
        y = predict.endpoint,
        color = ID_experiment
      ),
      linewidth = line_width,
      alpha = alpha_line
    )+
    
    geom_point(
      data = subset(df_data_obs_EPX_R, Experiment_type == "Repro"),    
      mapping = 
        aes(  
          x = Time, 
          y = Weight_obs, 
          color = ID_experiment  
        ),
      alpha = 0.7,
      stroke = point_stroke
    )+
    
    scale_color_manual(
      name = "Experiments",
      values = col_experiment
      )+
    scale_fill_manual(
      name = "Experiments",
      values = col_experiment
      )+
    facet_wrap(
      ~Facet_label,
      ncol = wrap_nb_col
      )+
    labs(
      x="Time (days)", 
      y = "Weight (g)",
      title ="Effect of imidacloprid on adult growth"
    )+
    theme_minimal()+
  theme(
    plot.title = element_text(face = "bold", size = 11),
    legend.position = "none"
  )
  
   pR_R <- ggplot()+

    geom_ribbon(
      data = subset(df_pred_full_A_EPX_A_plot_R, Endpt == "Reproduction" & Experiment_type == "Repro"),
      aes(
        x = Time,
        ymax = up,
        ymin = low,
        fill = ID_experiment
      ),
      alpha = alpha_ribbon
    )+
    
    geom_line(
      data = subset(df_pred_full_A_EPX_A_plot_R, Endpt == "Reproduction" & Experiment_type == "Repro"),
      aes(
        x = Time,
        y = predict.endpoint,
        color = ID_experiment
      ),
      linewidth = line_width,
      alpha = alpha_line
    )+
    
    geom_point(
      data = subset(df_data_obs_EPX_R, Experiment_type == "Repro"),    
      mapping = 
        aes(  
          x = Time, 
          y = Reproduction_obs, 
          color = ID_experiment  
        ),
      alpha = 0.7,
      stroke = point_stroke
    )+
    
    scale_color_manual(
      name = "Experiments",
      values = col_experiment
      )+
    scale_fill_manual(
      name = "Experiments",
      values = col_experiment
      )+
    facet_wrap(
      ~Facet_label,
      ncol = wrap_nb_col
      )+
    labs(
      x="Time (days)", 
      y = "Cumulated reproduction (#)",
      title ="Effect of imidacloprid on reproduction"
    )+
    theme_minimal()+
  theme(
    plot.title = element_text(face = "bold", size = 11),
    legend.position = "none"
  )

p_WR_R <- pW_R + pR_R 

p_WR_summary <- pW_G + pW_R + pR_R +
  plot_layout(ncol=3)

```

```{r savetrajWRA_EPX_A_summary, include = F}
ggsave(
  filename="A_EPX_A_trajWR_G.png", 
  plot=pW_G, 
  width=6, height = 6, 
  path=path_fig
  )

ggsave(
  filename="A_EPX_A_trajWR_R.png", 
  plot=p_WR_R, 
  width=12, height = 6, 
  path=path_fig
  )

ggsave(
  filename="A_EPX_A_trajWR_summary.png", 
  plot=p_WR_summary, 
  width=12, height = 9, 
  path=path_fig
  )
```

:::
