{
  "hash": "6b47c64140af379ac30a0841c34a6539",
  "result": {
    "engine": "knitr",
    "markdown": "\n\n\n\n\n# Data and adjustments\n\n## Available data\n\nToxicodynamic calibration of the DEB-TKTD models relies on experimental data previously reported in @gollot_2026 presented [here](https://lisagllt.github.io/Ew-Mix-TD/quarto/B_TD_Single/BB_Effect_single.html). The dataset includes juvenile growth, adult growth, and cocoon production under single-substance exposure conditions for epoxiconazole and imidacloprid, while mixture reproduction data are retained for subsequent model evaluation rather than parameter calibration.\n\nTo remain consistent with the deterministic formulation of the DEB model and previous calibration procedures, observed responses are aggregated as mean values at the treatment-condition level before model fitting. This aggregation reduces the influence of inter-individual variability and experimental noise while preserving treatment-level temporal trajectories relevant to DEB processes.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import data\ndf_data_obs <- f_import_data_DEBTKTD()\ndf_data_obs_EPX <- df_data_obs |> \n  filter(Molecule == \"EPX\")\ndf_data_obs_IMD <- df_data_obs |> \n  filter(Molecule == \"IMD\")\n\n####### EPX ########################\n\n# Generate labels for each conditions\nCondition_order <- c(\n  \"Control\", \"C1\", \"C2\", \"C3\", \"C4\", \"C5\",\n  \"C6\", \"C7\", \"C8\"\n)\n\ndf_Exp_type_Dose_Condition_G <- df_data_obs_EPX |> \n  filter(Experiment_type == \"Growth\") |> \n  dplyr::select(ID_experiment, Experiment_type, Dose, Condition) |> \n  distinct() |> \n  mutate(\n    Condition = dplyr::recode(Condition, \"Ctrl\" = \"Control\"),\n    Condition = factor(Condition, levels = Condition_order)\n  )\n\ndf_Exp_type_Dose_Condition_R <- df_data_obs_EPX |> \n  filter(Experiment_type == \"Repro\") |> \n  dplyr::select(ID_experiment, Experiment_type, Dose, Condition) |> \n  distinct() |> \n  mutate(\n    Condition = dplyr::recode(Condition, \"Ctrl\" = \"Control\"),\n    Condition = factor(Condition, levels = Condition_order)\n  )\n\nID_levels_growth <- df_Exp_type_Dose_Condition_G |> \n  filter(Experiment_type == \"Growth\") |> \n  arrange(Condition) |> \n  pull(ID_experiment)\n\nFacet_levels_growth <- df_Exp_type_Dose_Condition_G |> \n  filter(Experiment_type == \"Growth\") |> \n  arrange(Condition) |> \n  mutate(Facet_label = paste(Condition, \":\", Dose/1000, \"mg/kg\")) |> \n  pull(Facet_label)\n\nID_levels_repro <- df_Exp_type_Dose_Condition_R |> \n  filter(Experiment_type == \"Repro\") |> \n  arrange(Condition) |> \n  pull(ID_experiment)\n\nFacet_levels_repro <- df_Exp_type_Dose_Condition_R |> \n  filter(Experiment_type == \"Repro\") |> \n  arrange(Condition) |> \n  mutate(Facet_label = paste(Condition, \":\", Dose/1000, \"mg/kg\")) |> \n  pull(Facet_label)\n\n# Data from juvenile growth experiment\ndf_data_obs_EPX_G <- df_data_obs_EPX |> \n  mutate(\n    Condition = dplyr::recode(Condition, \"Ctrl\" = \"Control\"),\n    Condition = factor(Condition, levels = Condition_order),\n    ID_experiment = factor(ID_experiment, levels = ID_levels_growth),\n    Facet_label = paste(Condition, \":\", Dose/1000, \"mg/kg\"),\n    Facet_label = factor(Facet_label, levels = Facet_levels_growth)\n  )\n\n# Data from adult reproduction experiment\ndf_data_obs_EPX_R <- df_data_obs_EPX |> \n  mutate(\n    Condition = dplyr::recode(Condition, \"Ctrl\" = \"Control\"),\n    Condition = factor(Condition, levels = Condition_order),\n    ID_experiment = factor(ID_experiment, levels = ID_levels_repro),\n    Facet_label = paste(Condition, \":\", Dose/1000, \"mg/kg\"),\n    Facet_label = factor(Facet_label, levels = Facet_levels_repro)\n  ) |> \n  filter(!(Time == 14))\n\n###### IMD ############################\n\n# Generate labels for each conditions\nCondition_order <- c(\n  \"Control\", \"C1\", \"C2\", \"C3\", \"C4\", \"C5\",\n  \"C6\", \"C7\", \"C8\", \"C9\", \"C10\"\n)\n\ndf_Exp_type_Dose_Condition_G <- df_data_obs_IMD |> \n  filter(Experiment_type == \"Growth\") |> \n  dplyr::select(ID_experiment, Experiment_type, Dose, Condition) |> \n  distinct() |> \n  mutate(\n    Condition = dplyr::recode(Condition, \"Ctrl\" = \"Control\"),\n    Condition = factor(Condition, levels = Condition_order)\n  )\n\ndf_Exp_type_Dose_Condition_R <- df_data_obs_IMD |> \n  filter(Experiment_type == \"Repro\") |> \n  dplyr::select(ID_experiment, Experiment_type, Dose, Condition) |> \n  distinct() |> \n  mutate(\n    Condition = dplyr::recode(Condition, \"Ctrl\" = \"Control\"),\n    Condition = factor(Condition, levels = Condition_order)\n  )\n\nID_levels_growth <- df_Exp_type_Dose_Condition_G |> \n  filter(Experiment_type == \"Growth\") |> \n  arrange(Condition) |> \n  pull(ID_experiment)\n\nFacet_levels_growth <- df_Exp_type_Dose_Condition_G |> \n  filter(Experiment_type == \"Growth\") |> \n  arrange(Condition) |> \n  mutate(Facet_label = paste(Condition, \":\", Dose/1000, \"mg/kg\")) |> \n  pull(Facet_label)\n\nID_levels_repro <- df_Exp_type_Dose_Condition_R |> \n  filter(Experiment_type == \"Repro\") |> \n  arrange(Condition) |> \n  pull(ID_experiment)\n\nFacet_levels_repro <- df_Exp_type_Dose_Condition_R |> \n  filter(Experiment_type == \"Repro\") |> \n  arrange(Condition) |> \n  mutate(Facet_label = paste(Condition, \":\", Dose/1000, \"mg/kg\")) |> \n  pull(Facet_label)\n\n# Data from juvenile growth experiment\ndf_data_obs_IMD_G <- df_data_obs_IMD |> \n  mutate(\n    Condition = dplyr::recode(Condition, \"Ctrl\" = \"Control\"),\n    Condition = factor(Condition, levels = Condition_order),\n    ID_experiment = factor(ID_experiment, levels = ID_levels_growth),\n    Facet_label = paste(Condition, \":\", Dose/1000, \"mg/kg\"),\n    Facet_label = factor(Facet_label, levels = Facet_levels_growth)\n  )\n\n# Data from adult reproduction experiment\ndf_data_obs_IMD_R <- df_data_obs_IMD |> \n  mutate(\n    Condition = dplyr::recode(Condition, \"Ctrl\" = \"Control\"),\n    Condition = factor(Condition, levels = Condition_order),\n    ID_experiment = factor(ID_experiment, levels = ID_levels_repro),\n    Facet_label = paste(Condition, \":\", Dose/1000, \"mg/kg\"),\n    Facet_label = factor(Facet_label, levels = Facet_levels_repro)\n  ) |> \n  filter(!(Time == 14))\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Available data on the toxicity of imidacloprid on earthworm growth and reproduction.](H_DEBTKTD_prep_files/figure-html/fig-DataIMD-1.png){#fig-DataIMD width=1152}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Available data on the toxicity of epoxiconazole on earthworm growth and reproduction.](H_DEBTKTD_prep_files/figure-html/fig-DataEPX-1.png){#fig-DataEPX width=1152}\n:::\n:::\n\n\n\n\n## Adjustment of the DEB model\n\n### Relationship between W, Eh and E for juveniles\n\nThe juvenile growth experiments were conducted with juvenile individuals housed individually in cosms containing 200 g of Closeaux soil, maintained at 18°C, and fed 3 g of horse dung per individual every 14 days. Individuals were exposed to a range of concentrations of either imidacloprid or epoxiconazole. In the DEB-TKTD model, the initial maturity of these individuals must be specified, although it was not and can not be directly measured. We therefore use a proxy based on the relationship between predicted body mass and predicted maturity obtained from the DEB model for the Gollot2026_dens_D5 experiment, which was conducted under the same experimental conditions as the culture from which these earthworms came from.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath_D_CWKe <- here::here(\"mod/D_DEB_CWKe/W_Eh_relationship\")\n\nMCMC_out_D_CWKe <- f_MCSim(path_D_CWKe)\nL_parameters_D_CWKe <- unique(MCMC_out_D_CWKe$Priors$Nom)\n\nSummary_res_D_CWKe <- \n  as.data.frame(MCMC_out_D_CWKe$Summary_res)[1:length(L_parameters_D_CWKe)] |> \n  mutate(Model = \"D_CWKe\") \n\nNb_experiment <- 1\nstep_sim <- 0.05\nselect_times <- seq(0,400, 0.1)\n\nEndpoints_print <- \"Weight,\n    Maturity,\n    Energy\"\n\nl_Experiment_D5 <- c(\"Gollot2026_dens_D5\")\n\nl_param_name_D_CWKe <- names(Summary_res_D_CWKe) |>\n  head(-1) |>\n  stringr::str_remove_all(\"\\\\.1\\\\.\")\n\nf_In_Setpoint_full(\n  path_D_CWKe, l_Experiment_D5, \n  Adults_alone = FALSE, OM_diff = TRUE, \n  l_param_name_D_CWKe, step_sim, Endpoints_print\n  )\n\n# ./mcsim.DEBcali DEB_setpoint_full_1.in\n\n\nfile_rds_D_CWKe <- file.path(path_D_CWKe, paste0(\"Sim.Res.Exp.full.rds\"))\n\nif (file.exists(file_rds_D_CWKe)) {\n  df_pred_full_D_CWKe <- readRDS(file_rds_D_CWKe)\n} else {\n  df_pred_full_D_CWKe <- f_read_Setpoint_full(path_D_CWKe, Adults_alone = FALSE, l_Experiment_D5, Nb_experiment, select_times, step_sim, bol_Eh = TRUE)\n}\n\ndf_pred_full_D_CWKe_wide <- df_pred_full_D_CWKe |> \n  pivot_wider(\n    id_cols = Time,\n    names_from = Endpt, \n    values_from = predict.endpoint\n    )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_RWEh <- lm(\n  Maturity ~ Weight + I(Weight^2), \n  data = df_pred_full_D_CWKe_wide |> filter(Weight < 0.5)\n  )\nsummary(mod_RWEh)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Maturity ~ Weight + I(Weight^2), data = filter(df_pred_full_D_CWKe_wide, \n    Weight < 0.5))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.65009 -0.18892  0.01263  0.12859  0.61326 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -0.87363    0.01921  -45.48   <2e-16 ***\nWeight      109.29263    0.22401  487.90   <2e-16 ***\nI(Weight^2)  71.61725    0.48304  148.26   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.254 on 861 degrees of freedom\nMultiple R-squared:  0.9998,\tAdjusted R-squared:  0.9998 \nF-statistic: 2.778e+06 on 2 and 861 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nc <- coef(mod_RWEh)[[\"(Intercept)\"]]\nb <- coef(mod_RWEh)[[\"Weight\"]]\na <- coef(mod_RWEh)[[\"I(Weight^2)\"]]\n\nequation <- paste0(\n  \"Maturity = \", round(a, 3), \" Weight² + \",\n  round(b, 3), \" Weight + \",\n  round(c, 3)\n)\n\nequation\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Maturity = 71.617 Weight² + 109.293 Weight + -0.874\"\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Relationship between weight and maturity in the Gollot2026_dens_D5 experiment.](H_DEBTKTD_prep_files/figure-html/fig-RWEhD5-1.png){#fig-RWEhD5 width=576}\n:::\n:::\n\n\n\n\nAs the initial weight in this dataset range from 0.055 to 0.141 g, a relationship established for weights under 0.5 g is enough.\n\nFor the initialisation of the energy in the reserve, we assume individuals were well fed in the culture and therefore the energy can be assumed to equal Em at the start of the experiment.\n\n### Re-estimations of $\\{\\dot{p}_{Am}\\}$, $E_{coc}$ and $\\kappa_A$\n\nBefore estimating toxicodynamic parameters, the baseline DEB model was evaluated against the control data from the juvenile growth, adult growth, and reproduction experiments. This preliminary step was used to account for possible physiological differences between the earthworms used in the toxicity experiments and the populations included in the original DEB calibration. When systematic discrepancies were identified between control observations and model predictions, selected DEB parameters associated with the affected biological process were allowed to vary, while the model structure and all remaining physiological parameters were retained from the original calibration. Candidate parameters were selected according to their mechanistic relationship with the response requiring adjustment, in order to limit the number of re-estimated parameters and preserve identifiability. All other DEB parameters were fixed to the posterior mode values obtained from the initial DEB model.\n\nPrior distributions were defined within $\\pm 30\\%$ of the values estimated in the initial DEB calibration. Parameter estimation was performed using Bayesian inference implemented in MCSim [@bois_2009] and using three independent MCMC chains of 30,000 iterations, of which the final 10,000 iterations were retained to characterize the posterior distributions. The posterior mode estimates of $\\{\\dot{p}_{Am}\\}$ and $E_{coc}$ were subsequently fixed during the estimation of the toxicodynamic parameters.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath_fig <- here::here(\"fig/DEBTKTD_Models\")\npath_DEB_refit <- here::here(\"mod/Z_DEB-TKTD/DEB_refit\")\n\nMCMC_out_DEB_refit <- f_MCSim(path_DEB_refit)\n\nNC_DEB_refit <- MCMC_out_DEB_refit$NC\nNb_param_DEB_refit <- MCMC_out_DEB_refit$Nb_param\nNb_experiment_DEB_refit <- MCMC_out_DEB_refit$Nb_experiment\nNb_iter_kept_DEB_refit <- MCMC_out_DEB_refit$Nb_iter_kept\nN_iter_setpoint_DEB_refit <- MCMC_out_DEB_refit$N_iter_setpoint\nL_parameters_DEB_refit <- unique(MCMC_out_DEB_refit$Priors$Nom)\n\nSummary_res_DEB_refit <- \n  as.data.frame(MCMC_out_DEB_refit$Summary_res)[1:length(L_parameters_DEB_refit)] |> \n  mutate(Model = \"DEB_refit\")\n\nSummary_res_DEB_refit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               pAm.1.  E_coc.1.    kapA.1. Sigma_W.1.     Model\nResult_mode 292.84500  79.53530 0.67495600 0.01012790 DEB_refit\n2.5%        238.16705  53.21390 0.63843800 0.01017950 DEB_refit\n97.5%       323.55000 114.23800 0.72654800 0.06157490 DEB_refit\nMin         113.78900  12.02130 0.49854700 0.01000710 DEB_refit\nMax         408.05200 147.01100 0.92976300 0.58365200 DEB_refit\nResult_mean 287.96834  81.94554 0.67818789 0.02045819 DEB_refit\nResult_sd    20.58767  15.49444 0.02235243 0.01584239 DEB_refit\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Parameters chains. Only the first iteration and the last `r Nb_iter_kept` are represented.](H_DEBTKTD_prep_files/figure-html/fig-chains_DEB_refit-1.png){#fig-chains_DEB_refit width=768}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPotential scale reduction factors:\n\n           Point est. Upper C.I.\nE_coc.1.         1.00       1.00\nkapA.1.          1.01       1.01\npAm.1.           1.01       1.01\nSigma_W.1.       1.06       1.10\n\nMultivariate psrf\n\n1.01\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Chains convergence.](H_DEBTKTD_prep_files/figure-html/fig-chainsconvergence_DEB_refit-1.png){#fig-chainsconvergence_DEB_refit width=768}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfile_rds <- here::here(\"fig/DEBTKTD_Models/DEB_refit_ipairs_plot.png\")\nf_Plot_ipairs(MCMC_out_DEB_refit, file_rds, 1)\n```\n\n::: {.cell-output-display}\n![Parameter correlations.](H_DEBTKTD_prep_files/figure-html/fig-corrDEBrefitipairs-1.png){#fig-corrDEBrefitipairs width=576}\n:::\n:::\n\n\n\n\n\n\nThe joint posterior distributions and MCMC trajectories showes no apparent correlation between $\\{\\dot{p}_{Am}\\}$ and $E_{coc}$, suggesting that the two parameters were independently identifiable from the control growth and reproduction data.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distributions of the priors and the posteriors.](H_DEBTKTD_prep_files/figure-html/fig-post_DEB_refit-1.png){#fig-post_DEB_refit width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npath_DEB_refit <- here::here(\"mod/Z_DEB-TKTD/DEB_refit\")\ndf_tab_setpoint_old_raw <- f_Read_fichier2(file.path(path_DEB_refit, \"tab_setpoint_old_raw.out\"))\n\ndf_tab_setpoint_old <- df_tab_setpoint_old_raw |> \n  dplyr::select(c(\"pAm.1.\", \"kapA.1.\", \"E_coc.1.\")) |> \n  mutate(\n    Iter = dplyr::row_number(), .before = 1\n  )\n\nentete <- paste(names(df_tab_setpoint_old)[-1], collapse = \" \")\n\nlignes <- apply(\n  df_tab_setpoint_old,\n  1,\n  function(x) paste(x, collapse = \" \")\n)\n\nwriteLines(\n  c(entete, lignes),\n  con = file.path(path_DEB_refit, \"tab_setpoint_old.out\"),\n  useBytes = TRUE\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstep_sim <- 0.05\nmax_time <- 28\n\ndf_pred_old <- f_Read_setpoint_DEB_refit(path_DEB_refit, step_sim, max_time, \"old\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 1000 Columns: 1126\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \"\\t\"\ndbl (1126): Iter, pAm, kapA, E_coc, Weight_1.1, Weight_1.2, Weight_1.3, Weig...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\nRows: 1000 Columns: 1126\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \"\\t\"\ndbl (1126): Iter, pAm, kapA, E_coc, Weight_1.1, Weight_1.2, Weight_1.3, Weig...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ndf_pred_new <- f_Read_setpoint_DEB_refit(path_DEB_refit, step_sim, max_time, \"new\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 1000 Columns: 1126\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \"\\t\"\ndbl (1126): Iter, pAm, E_coc, kapA, Weight_1.1, Weight_1.2, Weight_1.3, Weig...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\nRows: 1000 Columns: 1126\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \"\\t\"\ndbl (1126): Iter, pAm, E_coc, kapA, Weight_1.1, Weight_1.2, Weight_1.3, Weig...\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ndf_pred_old_G <- df_pred_old   |> \n  filter(Endpt == \"Weight\") |> \n  mutate(\n    Name_experiment = factor(case_when(\n      No_sim == 1 ~ \"Juveniles controles\",\n      No_sim == 2 ~ \"Adult controles\",\n    ), c(\"Juveniles controles\", \"Adult controles\")),\n    DEB_type = \"Old\"\n  )\n\ndf_pred_new_G <- df_pred_new |> \n  filter(Endpt == \"Weight\") |> \n  mutate(\n    Name_experiment = factor(case_when(\n      No_sim == 1 ~ \"Juveniles controles\",\n      No_sim == 2 ~ \"Adult controles\",\n    ), c(\"Juveniles controles\", \"Adult controles\")),\n    DEB_type = \"New\"\n  )\n\ndf_pred_old_R <- df_pred_old   |> \n  filter(Endpt == \"Reproduction\") |> \n  filter(No_sim == 2) |> \n  mutate(\n    Name_experiment = factor(case_when(\n      No_sim == 1 ~ \"Juveniles controles\",\n      No_sim == 2 ~ \"Adult controles\",\n    ), c(\"Juveniles controles\", \"Adult controles\")),\n    DEB_type = \"Old\"\n  )\ndf_pred_new_R <- df_pred_new   |> \n  filter(Endpt == \"Reproduction\") |> \n  filter(No_sim == 2) |> \n  mutate(\n    Name_experiment = factor(case_when(\n      No_sim == 1 ~ \"Juveniles controles\",\n      No_sim == 2 ~ \"Adult controles\",\n    ), c(\"Juveniles controles\", \"Adult controles\")),\n    DEB_type = \"New\"\n  )\n\ndf_pred_G <- rbind(df_pred_old_G, df_pred_new_G)\ndf_pred_R <- rbind(df_pred_old_R, df_pred_new_R)\n\n\ndf_data_Ctrl <- f_import_data_DEBTKTD() |> \n  filter(Condition == \"Ctrl\" & Molecule == \"IMD\") |> \n  mutate(\n    No_sim = case_when(\n      Molecule == \"IMD\" & Experiment_type == \"Growth\" ~ 1,\n      Molecule == \"IMD\" & Experiment_type == \"Repro\" ~ 2\n    )\n  )  |> \n  mutate(\n    Name_experiment = factor(case_when(\n      No_sim == 1 ~ \"Juveniles controles\",\n      No_sim == 2 ~ \"Adult controles\",\n    ), c(\"Juveniles controles\", \"Adult controles\"))\n  )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nalpha_ribbon <- 0.2\n\npW <- ggplot()+\n  \n  geom_ribbon(\n      data = df_pred_G,\n      aes(\n        x = Time,\n        ymax = up,\n        ymin = low,\n        fill = DEB_type\n      ),\n      alpha = alpha_ribbon\n    )+\n  \n  geom_line(\n    data = df_pred_G,\n    aes(\n      x = Time,\n      y = predict.endpoint,\n      color = DEB_type\n    )\n  )+\n  \n  geom_point(\n    data = df_data_Ctrl,\n    aes(\n      x = Time, \n      y = Weight\n    ),\n    color = Nord_polar[1]\n  )+\n  \n  scale_color_manual(values = c(Nord_frost[4], Nord_frost[2]), name = \"DEB\")+\n  scale_fill_manual(values = c(Nord_frost[4], Nord_frost[2]), name = \"DEB\")+\n  facet_wrap(~Name_experiment)+\n  labs(x = \"Time (days)\", y = \"Weight (g)\")+\n  theme_minimal()+\n  theme(\n    strip.text = element_text(face=\"bold\")\n  )\n\npR <- ggplot()+\n  \n  geom_ribbon(\n      data = df_pred_R,\n      aes(\n        x = Time,\n        ymax = up,\n        ymin = low,\n        fill = DEB_type\n      ),\n      alpha = alpha_ribbon\n    )+\n  \n  geom_line(\n    data = df_pred_R,\n    aes(\n      x = Time,\n      y = predict.endpoint,\n      color = DEB_type\n    )\n  )+\n  \n  geom_point(\n    data = df_data_Ctrl |> filter(Name_experiment == \"Adult controles\"),\n    aes(\n      x = Time, \n      y = Reproduction\n    ),\n    color = Nord_polar[1]\n  )+\n  scale_color_manual(values = c(Nord_frost[4], Nord_frost[2]), name = \"DEB\")+\n  scale_fill_manual(values = c(Nord_frost[4], Nord_frost[2]), name = \"DEB\")+\n  facet_wrap(~Name_experiment)+\n  labs(x = \"Time (days)\", y = \"Reproduction (#)\")+\n  theme_minimal()+\n  theme(\n    strip.text = element_text(face=\"bold\")\n  )\n\np <- pW + pR + plot_layout(ncol = 2, guides = \"collect\", widths = c(2, 1),)\np\n```\n\n::: {.cell-output-display}\n![Observed growth and reproduction responses of control *Aporrectodea caliginosa* and corresponding predictions from the baseline DEB model before and after parameter recalibration. Points represent experimental treatment means. The original trajectories were generated using the posterior mode parameter values from the initial DEB calibration, whereas the recalibrated trajectories used the newly estimated values of the allocation energy fraction to soma in adults ($\\kappa_A$).](H_DEBTKTD_prep_files/figure-html/fig-refitrib-1.png){#fig-refitrib width=768}\n:::\n:::\n\n\n\n\n\n\nPredictions obtained with the original DEB parameterization showed a slight underestimation of both juvenile and adult growth, together with an overestimation of cocoon production (@fig-refitrib). To improve the description of the control trajectories before estimating toxicodynamic effects, three DEB parameters were therefore re-estimated: the maximum surface-area-specific assimilation rate, $\\{\\dot{p}_{Am}\\}$, the cocoon energy content, $E_{coc}$, and the adult allocation fraction, $\\kappa_A$.\n\nThe posterior mode of $\\{\\dot{p}_{Am}\\}$ increased from 259.0 \\[237.6; 280.0\\] to 292.8 \\[238.2; 323.5\\] J$\\cdot$cm$^{-2}\\cdot$d$^{-1}$, while $E_{coc}$ increased from 68.4 \\[58.4; 75.5\\] to 79.5 \\[53.2; 114.2\\] J. The posterior mode of $\\kappa_A$ also increased slightly, from 0.64 \\[0.56; 0.70\\] to 0.67 \\[0.64; 0.73\\]. The substantial overlap between the original and recalibrated credible intervals indicates that the updated estimates remained broadly consistent with the initial DEB parameterization. The posterior correlation between the parameters was weak, indicating that the parameters were estimated independently (@fig-corrDEBrefitipairs).\n\nUsing the recalibrated parameter values improved the agreement between predicted and observed juvenile and adult growth trajectories. Reproduction was also more closely reproduced than with the original parameterization, although cocoon production remained slightly overestimated. The posterior mode estimates of $\\{\\dot{p}_{Am}\\}$, $E_{coc}$, and $\\kappa_A$ were therefore retained and fixed for all subsequent DEB-TKTD analyses.\n\n\n\n\n\n\n\n\n\n## Construction of the DEB-TKTD models\n\n### Toxicokinetic models\n\nInternal concentrations of epoxiconazole and imidacloprid are simulated using previously developed toxicokinetic models (more details [here](https://lisagllt.github.io/Ew-Mix-TK/)). For both compounds, two-compartment TK formulations were retained and parameterized using the median of posterior parameter distributions estimated from dedicated bioaccumulation experiments. External exposure concentrations corresponded to analytically measured soil concentrations rather than nominal concentrations. The TK models were originally calibrated under nominal exposure conditions of 100 ng.g$^{-1}$ dry soil for imidacloprid and 1000 ng.g$^{-1}$ dry soil for epoxiconazole.\n\nBecause previous toxicokinetic analyses found no evidence for mixture-related TK interactions between epoxiconazole and imidacloprid, single-substance TK models are used unchanged to simulate internal concentrations under co-exposure scenarios. Consequently, each compound is assumed to follow independent uptake and elimination dynamics in mixture conditions.\n\nPrevious toxicokinetic analyses identified concentration-dependent deviations for imidacloprid, with evidence of saturation occurring at internal concentrations around 1676 ng.g$^{-1}$. Under the original first-order formulation, this saturation implied a restricted application domain, corresponding to external concentrations below approximately 80 ng.g$^{-1}$ dry soil assuming a bioaccumulation factor of 21. However, because several exposure concentrations used in the toxicity experimental data exceeded the external concentration range over which the initial TK model could be applied, this saturation process is explicitly incorporated into the imidacloprid toxicokinetic module. The TK model for imidacloprid is therefore modified to account for a plateau in internal concentrations at high exposure levels, preventing unrealistic linear increases in internal exposure beyond the observed saturation range. This extended formulation is used for all imidacloprid-related simulations and parameter inferences in the DEB-TKTD model.\n\n### Toxicodynamic model and physiological modes of action\n\nToxicodynamic processes is modeled following a standard DEB-TKTD formulation in which internal concentrations generate a damage variable that translates into physiological stress affecting DEB energetic fluxes [@jager_2006; @baas_2018; @jager_2023] (@eq-chap4TKTD). Because no toxicokinetic interactions are assumed, separate damage dynamics are modeled for epoxiconazole and imidacloprid, each compound being characterized by its own toxicodynamic parameters.\n\n$$\n\\begin{aligned}\n\\frac{\\mathrm d D}{\\mathrm d t} &= k_r (C_{\\mathrm{int}} - D) \\\\ \\\\\ns &= b(D−c_0)\n\\end{aligned}\n$$ {#eq-chap4TKTD}\n\n\\noindent with :\n\n-   $C_{\\mathrm{int}}$ : the internal concentration,\n-   $D$ : the internal damage scaled in the same unit as $C_{\\mathrm{int}}$,\n-   $k_r$ : Recuperation or repair constant of damage.\\$,\n-   $s$ : the stress factor,\n-   $b$ : damage sensitivity ($b = 1/c_T$ with $c_T$ the tolerance concentration),\n-   $c_0$ : the no-effect concentration.\n\nTo reduce parameter identifiability issues, the damage recovery constant ($k_r$) was fixed to 1, so that damage instantaneously followed the internal concentration ($D=C_{\\mathrm{int}}$).\n\nFor each pesticide, multiple physiological modes of action (pMoA) are evaluated individually by allowing toxic stress to alter different DEB processes, including assimilation, maintenance, growth, maturation, and reproduction (@tbl-chap4pMoA).\n\n| Physiological mode of action (pMoA) | Affected parameters | Effect on parameters |\n|----|----|----|\n| Ingestion and/or assimilation | $\\{\\dot{p}_{Am}\\}$: Surface-area-specific assimilation flux (J d$^{-1}$ cm$^{-2}$) | $\\{\\dot{p}_{Am}\\} \\rightarrow (1-s)\\{\\dot{p}_{Am}\\}$ |\n|  | or |  |\n|  | $f$: Functional response (-) | $f \\rightarrow f_0 \\max(0,1-s)$ |\n| Maintenance costs | $[\\dot{p}_M]$: Volume-specific somatic maintenance flux (J d$^{-1}$ cm$^{-3}$) | $[\\dot{p}_M] \\rightarrow (1+s)[\\dot{p}_M]$ |\n|  | $\\dot{k}_J$: Maturity maintenance rate coefficient (d$^{-1}$) | $\\dot{k}_J \\rightarrow (1+s)\\dot{k}_J$ |\n| Growth and maturity costs | $E_G$: Volume-specific cost of structure (J g$^{-1}$) | $E_G \\rightarrow (1+s)E_G$ |\n|  | $\\kappa_H$: Maturation efficiency (= 1 in the standard DEB model) | $\\kappa_H \\rightarrow \\kappa_H/(1+s)$ |\n| Reproduction costs | $\\kappa_R$: Reproduction efficiency | $\\kappa_R \\rightarrow \\kappa_R/(1+s)$ |\n| Embryo damage | $\\kappa_R$: Reproduction efficiency | $\\kappa_R \\rightarrow \\exp(-s)\\kappa_R$ |\n\n: **Accounting for the different possible physiological modes of action in a DEB model.** The stress factor $s$ is defined as a linear threshold damage function based on a no-effect concentration ($c_0$), whose inverse slope is commonly referred to as the tolerance concentration ($c_T$) [@kooijman_2009b]. Adapted from Table 2 in @jager_2023. {#tbl-chap4pMoA}\n\nCandidate pMoAs are first evaluated independently for each compound and subsequently combined for the most supported hypotheses. Competing models are compared using the Bayesian Information Criterion (BIC), allowing comparison among alternative physiological hypotheses while penalizing model complexity.\n\nModels are designated in the code with combinaison of letters corresponding to the pMoA(s) considered in a given model :\n\n-   A : Ingestion and/or Assimilation costs,\n-   M : Maintenance costs,\n-   G : Growth and maturity costs,\n-   R : Reproduction costs.\n\nOnly toxicodynamic parameters are estimated in the present study, whereas all DEB and toxicokinetic parameters remained fixed to previously estimated posterior modes Parameter estimation is performed using Bayesian inference implemented in MCSim [@bois_2009]. Three independent Markov Chain Monte Carlo (MCMC) chains of 30,000 iterations were run, with only the last 10,000 retained for inference. Growth endpoints are modeled assuming normally distributed residuals, whereas cocoon production is modeled using a Poisson likelihood. Convergence diagnostics includes inspection of chain mixing and agreement among posterior distributions across chains. The point estimates correspond to the posterior distributions mode.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}